import {test} from 'node:test';
import assert from 'node:assert/strict';
import {openStore,importDemo} from '../demo-server/slash/store.mjs';
import {seedPortal,portalState,portalAction} from '../demo-server/slash/portal.mjs';
import {seedCardAdmin,requestCardOperation,reviewCardOperation,processCardJob,cardAdminRead} from '../demo-server/slash/card-admin.mjs';
import {readCardWorkspace,readCardTransactions} from '../demo-server/slash/card-workspace.mjs';
import {cleanCardAdmin} from '../demo-server/slash/card-admin-cli.mjs';
const ns='card-workspace-test',maker='demo-operator',checker='demo-reviewer';
function setup(){const db=openStore(':memory:');importDemo(db,{namespace:ns,persist:false});seedPortal(db,ns);seedCardAdmin(db,ns);return db;}
function freeze(db,id='CARDOPS-001'){const c=cardAdminRead(db,ns,maker,`cards/${id}`).card;const o=requestCardOperation(db,ns,maker,id,{requestId:crypto.randomUUID(),kind:'freeze',cardRevision:c.revision,reason:'INTERNAL-RISK-SECRET',internalNote:'INTERNAL-INVESTIGATION',customerReason:'请补充交易用途'});processCardJob(db,ns,o.id);return o;}
function apply(db,id='CARDOPS-001',extra={}){const s=portalState(db,ns),c=s.cards.find(c=>c.id===id);return portalAction(db,ns,{requestId:`DEMO-${crypto.randomUUID()}`,revision:s.revision,action:{type:'unfreeze-request',id,freezeRevision:c.management.revision,reason:'交易用途已说明',evidence:'TEST-DOC-1',...extra}});}
test('customer freeze reason is separate from internal investigation, including activity entries',()=>{const db=setup();freeze(db);const state=JSON.stringify(portalState(db,ns));assert(!state.includes('INTERNAL-RISK-SECRET'));assert(!state.includes('INTERNAL-INVESTIGATION'));assert(state.includes('请补充交易用途'));db.close();});
test('client applies, duplicate is blocked, reviewer approves and confirmation removes only risk restriction',()=>{const db=setup();freeze(db);const a=apply(db);assert.throws(()=>apply(db),/已有待处理/);assert.equal(cardAdminRead(db,ns,maker,`cards/CARDOPS-001`).unfreezeRequests.length,1);reviewCardOperation(db,ns,checker,a.id,{decision:'approve',note:'用途核实'});assert.equal(portalState(db,ns).cards.find(c=>c.id==='CARDOPS-001').riskFrozen,true);processCardJob(db,ns,a.id);assert.equal(portalState(db,ns).cards.find(c=>c.id==='CARDOPS-001').riskFrozen,false);db.close();});
test('returned application can be supplemented; review history is kept; repeat rejection is idempotent',()=>{const db=setup();freeze(db);const a=apply(db);reviewCardOperation(db,ns,checker,a.id,{decision:'return',note:'补充凭证'});assert.equal(portalState(db,ns).cards.find(c=>c.id==='CARDOPS-001').unfreezeRequest.approval_status,'returned');assert.equal(apply(db,'CARDOPS-001',{reason:'已补充凭证'}).id,a.id);const decision={decision:'reject',note:'资料不符'};reviewCardOperation(db,ns,checker,a.id,decision);reviewCardOperation(db,ns,checker,a.id,decision);const d=cardAdminRead(db,ns,maker,`operations/${a.id}`);assert(d.audit.some(a=>a.action==='return'));assert(d.audit.some(a=>a.action==='customer_resubmitted'));assert.equal(d.operation.execution_status,'not_executed');assert.equal(portalState(db,ns).cards.find(c=>c.id==='CARDOPS-001').riskFrozen,true);cleanCardAdmin(db,ns);db.close();});
test('new freeze revision invalidates old approval and stale client application',()=>{const db=setup();freeze(db);const a=apply(db);db.prepare('UPDATE ca_cards SET revision=revision+1 WHERE namespace=? AND id=?').run(ns,'CARDOPS-001');reviewCardOperation(db,ns,checker,a.id,{decision:'approve',note:'旧审批'});assert.equal(cardAdminRead(db,ns,maker,`operations/${a.id}`).operation.execution_status,'failed');assert.throws(()=>apply(db,'CARDOPS-001',{freezeRevision:1}),/冻结记录已变化/);assert.equal(portalState(db,ns).cards.find(c=>c.id==='CARDOPS-001').riskFrozen,true);db.close();});
test('client cannot apply for another owner or bypass risk freeze via direct self-unfreeze',()=>{const db=setup();freeze(db);db.prepare("UPDATE ca_cards SET owner_id='someone-else' WHERE namespace=? AND id=?").run(ns,'CARDOPS-001');assert.throws(()=>apply(db),/不属于当前客户/);db.close();});
test('readonly approval is rejected and source status is not an internal restriction',()=>{const db=setup();freeze(db);const a=apply(db);assert.throws(()=>reviewCardOperation(db,ns,'demo-viewer',a.id,{decision:'approve',note:'非法'}),/权限/);let calls=0;const live={authorize(){calls++},config:()=>({connectionId:'test-connection'}),read:()=>({row:{id:'card_1',cardName:'Upstream name',maskedCardNumber:'**** 4321',cardStatus:'paused',internal:{customerId:null}}})};const d=readCardWorkspace(db,ns,maker,'card_1',{},live);assert.equal(d.card.status,'unmanaged');assert.equal(d.card.balance,null);assert.equal(d.card.owner,null);assert(Object.values(d.card.actions).every(a=>!a.allowed));assert(calls);db.prepare("UPDATE ca_principals SET owner_scope='different' WHERE namespace=? AND actor=?").run(ns,maker);assert.throws(()=>readCardWorkspace(db,ns,maker,'card_1',{},live),/授权范围/);db.close();});
test('local transaction query is scoped by internal card permission; administrative funding is not a consumption',()=>{const db=setup();assert.equal(readCardTransactions(db,ns,maker,'CARDOPS-001',{},null).total,0);assert.throws(()=>readCardTransactions(db,ns,'demo-controller','CARDOPS-001',{},null),/权限/);db.close();});
test('unfreeze cannot execute while freeze result is unknown; rejected execution retains restriction',()=>{const db=setup();freeze(db,'CARDOPS-003');const a=apply(db,'CARDOPS-003');reviewCardOperation(db,ns,checker,a.id,{decision:'approve',note:'检查用途'});const o=cardAdminRead(db,ns,maker,`operations/${a.id}`).operation;assert.equal(o.approval_status,'approved');assert.equal(o.execution_status,'failed');assert.match(o.error,/待确认/);assert.equal(portalState(db,ns).cards.find(c=>c.id==='CARDOPS-003').riskFrozen,true);db.close();});
test('forced debit during risk restriction needs a separate permission in addition to debit',()=>{const db=setup();freeze(db);const p=db.prepare('SELECT permissions_json FROM ca_principals WHERE namespace=? AND actor=?').get(ns,maker);db.prepare('UPDATE ca_principals SET permissions_json=? WHERE namespace=? AND actor=?').run(JSON.stringify(JSON.parse(p.permissions_json).filter(p=>p!=='card.frozen_debit')),ns,maker);const c=cardAdminRead(db,ns,maker,'cards/CARDOPS-001').card;assert.equal(c.actions.debit.allowed,false);db.close();});
