import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';
import React from 'react';
import Renderer,{act} from 'react-test-renderer';
import ts from 'typescript';
const require=createRequire(import.meta.url), uri=s=>'data:text/javascript;base64,'+Buffer.from(s).toString('base64');
const state=globalThis.__security={};
const ui=uri(`export const ${['Alert','Box','Button','Chip','Divider','MenuItem','Paper','Stack','TextField','Typography','Icon','QRCodeSVG'].map(n=>`${n}='${n}'`).join(',')};export const useNavigate=()=>globalThis.__security.navigate;`);
const firebase=uri(`const s=globalThis.__security;export const multiFactor=()=>s.mfa;export const updatePassword=(...a)=>s.password(...a),verifyBeforeUpdateEmail=(...a)=>s.email(...a),sendEmailVerification=(...a)=>s.verify(...a),sendPasswordResetEmail=(...a)=>s.reset(...a);export const TotpMultiFactorGenerator={FACTOR_ID:'totp',generateSecret:(...a)=>s.secret(...a),assertionForEnrollment:(...a)=>a};`);
const other=uri(`export const useAuth=()=>globalThis.__security.auth;export const loginPath='/portal/login';export const getFirebaseAuth=()=>({});export const authMessage=e=>e.code||e.message;`);
let {outputText}=ts.transpileModule(readFileSync('packages/shared/src/auth/AccountSecurity.tsx','utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext,jsx:ts.JsxEmit.ReactJSX}});
outputText=outputText.replace(/from ["']([^"']+)["']/g,(_,n)=>`from ${JSON.stringify(n==='react'||n==='react/jsx-runtime'?pathToFileURL(require.resolve(n)).href:n==='firebase/auth'?firebase:['@mui/material','@iconify/react','react-router-dom','qrcode.react'].includes(n)?ui:other)}`);
const {default:Security}=await import(uri(outputText));
globalThis.window={location:{origin:'http://localhost'}};
let user;
function reset(){user={uid:'one',email:'old@example.invalid',emailVerified:true,providerData:[{providerId:'password'}],reload:async()=>{}};Object.assign(state,{auth:{session:{mfaVerified:true},signOut:()=>{state.signedOut=true;},refreshSession:async()=>{}},signedOut:false,navigate:(...a)=>{state.route=a;},mfa:{enrolledFactors:[{uid:'old',displayName:'Old phone',factorId:'totp'}],getSession:async()=>({}),enroll:async()=>{},unenroll:async()=>{}},password:async()=>{},email:async()=>{},verify:async()=>{},reset:async()=>{},secret:async()=>({secretKey:'synthetic',generateQrCodeUrl:()=> 'otpauth://synthetic'})});}
async function mount(){let v;await act(async()=>{v=Renderer.create(React.createElement(Security,{user}));});return v;}
const button=(v,label)=>v.root.findAllByType('Button').find(b=>b.props.children===label);
const field=(v,label)=>v.root.findAllByType('TextField').find(f=>f.props.label===label);
async function change(v,label,value){await act(async()=>field(v,label).props.onChange({target:{value}}));}
async function open(v,id){await act(async()=>v.root.findAllByType('Button').find(b=>b.props['aria-controls']===`security-${id}`).props.onClick());}
const submit=v=>v.root.findAllByType('Box').find(b=>b.props.component==='form').props.onSubmit({preventDefault(){}});
test('password requires matching confirmation; successful write signs out, duplicate submission is blocked',async()=>{reset();let resolve,calls=0;state.password=()=>{calls++;return new Promise(r=>resolve=r);};const v=await mount();await open(v,'password');await change(v,'新密码','Example-123');await change(v,'确认新密码','different');assert.equal(button(v,'保存新密码').props.disabled,true);await act(async()=>submit(v));assert.equal(calls,0);await change(v,'确认新密码','Example-123');await act(async()=>{submit(v);submit(v);});assert.equal(calls,1);assert.equal(state.signedOut,false);await act(async()=>resolve());assert.equal(state.signedOut,true);v.unmount();});
test('email submission sends verification but does not optimistically replace identity',async()=>{reset();let target;state.email=async(u,email)=>target=email;const v=await mount();await open(v,'email');await change(v,'新邮箱地址','new@example.invalid');await act(async()=>submit(v));assert.equal(target,'new@example.invalid');assert.equal(user.email,'old@example.invalid');assert.match(v.root.findByType('Alert').props.children,/完成新邮箱验证前/);v.unmount();});
test('recent-login rejection clears secrets and provides explicit login recovery',async()=>{reset();state.password=async()=>{throw {code:'auth/requires-recent-login'};};const v=await mount();await open(v,'password');await change(v,'新密码','Example-123');await change(v,'确认新密码','Example-123');await act(async()=>submit(v));assert.equal(field(v,'新密码').props.value,'');assert.equal(state.signedOut,false);await act(async()=>v.root.findByType('Alert').props.action.props.onClick());assert.equal(state.signedOut,true);v.unmount();});
test('one factor cannot be removed, replacement enrolls before any removal and clears code on failure',async()=>{reset();let removed=0;state.mfa.unenroll=async()=>removed++;const v=await mount();await open(v,'mfa');assert.equal(button(v,'确认移除并重新登录'),undefined);await act(async()=>button(v,'绑定新验证器').props.onClick());state.mfa.enroll=async()=>{throw {code:'auth/invalid-verification-code'};};await change(v,'六位验证码','123456');await act(async()=>submit(v));assert.equal(field(v,'六位验证码').props.value,'');assert.equal(state.signedOut,false);state.mfa.enroll=async()=>{};await change(v,'六位验证码','654321');await act(async()=>submit(v));assert.equal(state.signedOut,true);assert.equal(removed,0);v.unmount();});
test('removal rechecks server factors and refuses when another device was removed concurrently',async()=>{reset();state.mfa.enrolledFactors.push({uid:'new',displayName:'New phone',factorId:'totp'});let removed=0;state.mfa.unenroll=async()=>removed++;user.reload=async()=>{state.mfa.enrolledFactors=[state.mfa.enrolledFactors[0]];};const v=await mount();await open(v,'mfa');await change(v,'选择不再使用的验证器','old');await act(async()=>button(v,'确认移除并重新登录').props.onClick());assert.equal(removed,0);assert.equal(state.signedOut,false);assert.match(v.root.findByType('Alert').props.children,/状态已变化/);v.unmount();});
test('Google-only identity does not expose a password mutation form; cancellation removes enrollment secret',async()=>{reset();user.providerData=[{providerId:'google.com'}];const v=await mount();await open(v,'password');assert.equal(field(v,'新密码'),undefined);await open(v,'mfa');await act(async()=>button(v,'绑定新验证器').props.onClick());assert.equal(v.root.findAllByType('QRCodeSVG').length,1);await act(async()=>button(v,'取消绑定').props.onClick());assert.equal(v.root.findAllByType('QRCodeSVG').length,0);v.unmount();});
test('failed email change keeps the pending address and never claims that a verification mail was sent',async()=>{reset();state.email=async()=>{throw {code:'auth/network-request-failed'};};const v=await mount();await open(v,'email');await change(v,'新邮箱地址','new@example.invalid');await act(async()=>submit(v));assert.equal(field(v,'新邮箱地址').props.value,'new@example.invalid');assert.equal(user.email,'old@example.invalid');assert.equal(v.root.findByType('Alert').props.severity,'error');v.unmount();});
test('removal uses selected enrollment ID and signs out only after Firebase confirms',async()=>{reset();state.mfa.enrolledFactors.push({uid:'new',displayName:'New phone',factorId:'totp'});let removed;state.mfa.unenroll=async id=>{removed=id;};const v=await mount();await open(v,'mfa');await change(v,'选择不再使用的验证器','old');await act(async()=>button(v,'确认移除并重新登录').props.onClick());assert.equal(removed,'old');assert.equal(state.signedOut,true);assert.equal(state.route[0],'/portal/login');v.unmount();});
