// Isolated synthetic preview; every write and live API request is blocked.
import {createServer} from 'vite';
import ts from 'typescript';
import {resolve} from 'node:path';
const customerId='10000000-0000-0000-0000-000000000001';
const auth=`export const useAuth=()=>({ready:true,authenticated:true,user:{uid:'preview',email:'operator@example.invalid'},profile:{displayName:'Preview operator'},session:{id:'preview',operator:true,mfaVerified:true,customers:[]},signOut:()=>{}});`;
const fixture=`export const manualError=e=>e.message;export class SessionError extends Error{};export async function manualRequest(path,body){if(body!==undefined)throw new Error('合成预览禁止资金写入');if(sessionStorage.getItem('balance-preview-error')==='1')throw new Error('预览：读取失败，请重试');await new Promise(r=>setTimeout(r,150));const currency=new URL(path,'http://fixture.invalid').searchParams.get('currency')||'USD';const row={userId:'preview',customerId:'${customerId}',name:'Moventra operator',email:'operator@example.invalid',status:'active',service:'active',onboarding:'approved',walletMinor:'9',heldMinor:'0',cardsMinor:'0',totalMinor:'9',coverage:'journal_only',pendingOperations:0};const order={id:'20000000-0000-0000-0000-000000000001',customerId:'${customerId}',actorId:'preview',source:'platform_advance',direction:'credit',state:'pending_review',currency:'USD',amountMinor:'100000',createdAt:'2026-09-19T03:48:57Z',walletBeforeMinor:null,walletAfterMinor:null,revision:1,note:'合成记录',evidenceRef:'preview-only'};if(path.includes('/orders/'))return {order,events:[],mode:'live',enabled:false};if(path.includes('manual-funds'))return {orders:[order],total:1,page:0,mode:'live',enabled:false};return {rows:[{...row,currency}],summary:row,currency,total:1,page:0,mode:'live',observedAt:'2026-09-19T03:53:02Z',permissions:['read'],movements:[],cards:[],movementTotal:0,cardTotal:0};}`;
const entry=`import React from 'react';import{createRoot}from'react-dom/client';import{BrowserRouter,Routes,Route}from'react-router-dom';import{ThemeProvider,CssBaseline}from'@mui/material';import theme from '/packages/shared/src/theme.ts';import BalancesPage from '/apps/admin/src/operations/BalancesPage.tsx';import '@fontsource/public-sans/400.css';import '@fontsource/public-sans/600.css';import '@fontsource/public-sans/700.css';import '/packages/shared/src/styles.css';createRoot(document.getElementById('root')).render(<ThemeProvider theme={theme}><CssBaseline/><BrowserRouter><Routes>{['/finance/balances','/finance/balances/:customerId','/finance/balances/:customerId/orders/:orderId'].map(path=><Route key={path} path={path} element={<BalancesPage/>}/>)}</Routes></BrowserRouter></ThemeProvider>);`;
const server=await createServer({root:process.cwd(),configFile:false,cacheDir:'/tmp/moventra-balances-preview-cache',publicDir:resolve('packages/assets/public'),resolve:{dedupe:['react','react-dom']},esbuild:{jsx:'automatic'},server:{host:'127.0.0.1',port:8906,strictPort:true},plugins:[{name:'balance-preview',enforce:'pre',resolveId(id){if(id==='/balance-preview.tsx')return '\0balance-entry';if(id.endsWith('/AuthContext'))return '\0balance-auth';if(id.endsWith('/manualFundsApi')||id.endsWith('/liveApi'))return '\0balance-api'},load(id){if(id==='\0balance-auth')return auth;if(id==='\0balance-api')return fixture;if(id==='\0balance-entry')return ts.transpileModule(entry,{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText},configureServer(s){s.middlewares.use((req,res,next)=>{if(req.url?.startsWith('/admin-api')||req.url?.startsWith('/client-api')){res.statusCode=403;res.end('No live API in preview');return}if(req.headers.accept?.includes('text/html')){res.setHeader('Content-Type','text/html');res.end('<!doctype html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>资金详情 · 合成预览</title></head><body><div id="root"></div><div style="position:fixed;bottom:8px;right:12px;font:12px sans-serif;background:#f5f7fa;padding:6px;z-index:1600">本地合成预览 · 禁止资金写入</div><script type="module" src="/balance-preview.tsx"></script></body></html>')}else next()})}}]});await server.listen();console.log('http://127.0.0.1:8906/finance/balances/'+customerId);
