import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync}from'node:fs';import{createRequire}from'node:module';import{pathToFileURL}from'node:url';import React from'react';import Renderer,{act}from'react-test-renderer';import{MemoryRouter}from'react-router-dom';import ts from'typescript';
const require=createRequire(import.meta.url),resolve=s=>pathToFileURL(require.resolve(s)).href,uri=s=>'data:text/javascript;base64,'+Buffer.from(s).toString('base64'),compile=p=>ts.transpileModule(readFileSync(new URL(p,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;
const state=globalThis.__fundsFlowFixture={reads:[],writes:[]},memory=new Map();globalThis.sessionStorage={getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v),removeItem:k=>memory.delete(k)};globalThis.document={hidden:false};
const shell=uri(`import React from ${JSON.stringify(resolve('react'))};const Pass=({children,...p})=>React.createElement('div',p,children);export const Box=Pass,Paper=Pass,Stack=Pass,Table=Pass,TableContainer=Pass,TableBody=Pass,TableCell=Pass,TableHead=Pass,TableRow=Pass,Typography=Pass,MenuItem=Pass;export const TextField=p=>React.createElement('input',p);export const Chip=({label})=>React.createElement('span',null,label);export const Alert=({children,action})=>React.createElement('div',null,children,action);export const Button=({children,...p})=>React.createElement('button',p,children);`);
const api=uri(`export const cryptoError=e=>e.message;export const cryptoRequest=(path,body,key)=>new Promise((resolve,reject)=>globalThis.__fundsFlowFixture[body===undefined?'reads':'writes'].push({path,body,key,resolve,reject}));`),auth=uri('export const useAuth=()=>({session:{id:"actor"}})'),live=uri('export class SessionError extends Error{}'),qr=uri(`import React from ${JSON.stringify(resolve('react'))};export const QRCodeSVG=p=>React.createElement('svg',{'data-value':p.value});`),contract=uri(compile('../../packages/shared/src/auth/cryptoContract.ts'));
const component=uri(compile('../../packages/shared/src/finance/CustomerFunds.tsx').replace(/from ["']([^"']+)["']/g,(_,n)=>'from '+JSON.stringify(n==='@mui/material'?shell:n==='qrcode.react'?qr:n.endsWith('/cryptoContract')?contract:n.endsWith('/cryptoApi')?api:n.endsWith('/AuthContext')?auth:n.endsWith('/liveApi')?live:resolve(n))));const Funds=(await import(component)).default;
const id='10000000-0000-0000-0000-000000000001',base={mode:'live',executionEligible:true,customerId:id,canOperate:true,settings:{},ledger:{accounts:[]},addresses:[],addressJobs:{},orders:[],total:0,networks:[{network:'TRC20',depositEnabled:true,withdrawEnabled:true},{network:'ERC20',depositEnabled:true,withdrawEnabled:true}]};const flush=()=>new Promise(r=>setImmediate(r));
async function mount(path='/portal/funds/deposit'){let tree;await act(async()=>{tree=Renderer.create(React.createElement(MemoryRouter,{initialEntries:[path]},React.createElement(Funds,{customerId:id})));await flush()});return tree}
async function reply(call,v){await act(async()=>{call.resolve(v);await flush()})}
test('opened customer entering deposit requests one Cregis address, reuses it and clears QR on chain change',async()=>{state.reads=[];state.writes=[];memory.clear();let tree=await mount();assert.match(state.reads[0].path,/limit=5/);assert.match(state.reads[0].path,/kind=deposit/);await reply(state.reads[0],base);assert.equal(state.writes.length,1);assert.deepEqual(state.writes[0].body,{currency:'USDT',network:'TRC20'});assert.equal(tree.root.findAllByType('svg').length,0);await reply(state.writes[0],{state:'queued'});
const saved={...base,addresses:[{network:'TRC20',mode:'live',address:'cregis-customer-tron'}],addressJobs:{TRC20:'completed'}};await reply(state.reads.at(-1),saved);assert.equal(tree.root.findAllByType('svg')[0].props['data-value'],'cregis-customer-tron');await act(()=>tree.unmount());tree=await mount();await reply(state.reads.at(-1),saved);assert.equal(state.writes.length,1,'refresh must not request a new address');await act(()=>tree.root.findAllByType('input').find(n=>n.props.label==='网络').props.onChange({target:{value:'ERC20'}}));assert.equal(tree.root.findAllByType('svg').length,0,'wrong-chain QR cleared synchronously');await reply(state.reads.at(-1),saved);assert.deepEqual(state.writes.at(-1).body,{currency:'USDT',network:'ERC20'});await act(()=>tree.unmount())});
test('unopened customers, unavailable chains and overview never create addresses',async()=>{for(const [path,data]of [['/portal/funds/deposit',{...base,canOperate:false}],['/portal/funds/deposit',{...base,networks:[]}],['/portal/funds',base]]){state.reads=[];state.writes=[];memory.clear();const tree=await mount(path);await reply(state.reads[0],data);assert.equal(state.writes.length,0);await act(()=>tree.unmount())}});
test('OTC has two local currency logos, quote invalidates on direction change',async()=>{state.reads=[];state.writes=[];memory.clear();const tree=await mount('/portal/funds/exchange');await reply(state.reads[0],base);assert.match(state.reads[0].path,/kind=otc/);const logos=tree.root.findAll(n=>n.props.role==='img');assert.deepEqual(logos.map(n=>n.props['aria-label']).filter((v,i,a)=>a.indexOf(v)===i),['USDT Logo','USD Logo']);await act(()=>tree.root.findAllByType('input').find(n=>n.props.label==='卖出金额').props.onChange({target:{value:'1.234567'}}));const button=tree.root.findAllByType('button').find(n=>n.props.children==='获取报价');await act(async()=>{button.props.onClick();await flush()});assert.deepEqual(state.writes[0].body,{currency:'USDT',amountMinor:'1234567'});await reply(state.writes[0],{id,amountMinor:'1234567',receiveMinor:'123',feeMinor:'0',currency:'USDT',toCurrency:'USD',rate:'1',expiresAt:new Date(Date.now()+60000).toISOString()});assert.ok(tree.root.findAllByType('button').find(n=>n.props.children==='确认兑换'));await act(()=>tree.root.findAllByType('button').find(n=>n.props['aria-label']==='切换兑换方向').props.onClick());assert.equal(tree.root.findAllByType('button').filter(n=>n.props.children==='确认兑换').length,0);await act(()=>tree.unmount())});
test('disabled deployment shows four flows without inventing available money or sending writes',async()=>{for(const path of ['/portal/funds','/portal/funds/deposit','/portal/funds/fiat','/portal/funds/withdraw','/portal/funds/exchange']){state.reads=[];state.writes=[];memory.clear();const tree=await mount(path);const E=(await import(live)).SessionError;const error=new E('disabled');error.code='crypto_disabled';await act(async()=>{state.reads[0].reject(error);await flush()});const text=JSON.stringify(tree.toJSON());assert.match(text,/资金服务尚未启用/);assert.doesNotMatch(text,/0\.000000 USDT/);assert.equal(state.writes.length,0);const submitButtons=tree.root.findAllByType('button').filter(n=>['查看费用','获取报价','重新查询地址'].includes(n.props.children));assert.ok(submitButtons.every(n=>n.props.disabled));await act(()=>tree.unmount())}});
