// Synthetic presentation fixture. All mutations and real API requests are blocked.
import {createServer} from 'vite';
import ts from 'typescript';
import {resolve} from 'node:path';
const customerId='10000000-0000-0000-0000-000000000001',productId='30000000-0000-0000-0000-000000000001';
async function read(path,body){
 if(body!==undefined)throw new Error('本地合成预览禁止保存或执行资金操作');
 await new Promise(r=>setTimeout(r,80));
 const url=new URL(path,'http://fixture.invalid'),p=url.pathname,q=url.searchParams;
 const customerId='10000000-0000-0000-0000-000000000001',productId='30000000-0000-0000-0000-000000000001',at='2026-09-19T03:53:02Z';
 const currency=q.get('currency')||'USD';
 const row={userId:'preview',customerId,name:'Northstar Commerce',email:'finance@example.invalid',status:'active',service:'active',onboarding:'approved',currency,walletMinor:currency==='USD'?'248050':'350250000',heldMinor:'0',cardsMinor:'0',totalMinor:currency==='USD'?'248050':'350250000',coverage:'journal_only',pendingOperations:0};
 const manual={id:'20000000-0000-0000-0000-000000000001',customerId,actorId:'preview',source:'platform_advance',direction:'credit',state:'completed',currency:'USD',amountMinor:'100000',createdAt:at,walletBeforeMinor:'148050',walletAfterMinor:'248050',revision:1,note:'合成入金记录，仅供版式核对',evidenceRef:'preview-only'};
 const settings={revision:3,usdtToUsd:'0.99',usdToUsdt:'1.01',withdrawalFeeMinor:'1000000',networkFees:{TRC20:'1000000',ERC20:'3000000'},cardDepositFeeMinor:'0',cardWithdrawFeeMinor:'50',otcEnabled:true,withdrawEnabled:false};
 const orders=['deposit','otc','withdrawal','withdrawal'].map((kind,i)=>({id:'40000000-0000-0000-0000-00000000000'+i,customerId,kind,state:['completed','completed','pending_review','unknown'][i],revision:1,currency:'USDT',toCurrency:kind==='otc'?'USD':'USDT',amountMinor:'100000000',receiveMinor:kind==='otc'?'9900':'99000000',feeMinor:'1000000',address:kind==='withdrawal'?'PREVIEW-ONLY-DO-NOT-TRANSFER':'',network:'TRC20',approvalStatus:kind==='withdrawal'?'pending':'not_required',providerStatus:'not_submitted',chainStatus:'not_verified',postingStatus:i<2?'posted':'reserved',createdAt:at,updatedAt:at,quote:kind==='otc'?{rate:'0.99',policyRevision:3}:undefined}));
 if(p.endsWith('/crypto-scopes'))return [{id:customerId,name:'Northstar Commerce',permissions:['read','configure','review','recover']}];
 if(p.includes('/crypto/orders/'))return {order:orders.find(o=>p.endsWith(o.id))||orders[2],events:[{action:'created',createdAt:at},{action:'worker',createdAt:at}],postings:[{id:'preview-posting',amountMinor:'100000000',currency:'USDT',state:'reserved',reference:'preview-ledger-reference'}]};
 if(p.endsWith('/crypto')){const rows=orders.filter(o=>(!q.get('kind')||o.kind===q.get('kind'))&&(!q.get('status')||o.state===q.get('status')));return {mode:'live',executionEligible:false,customerId,settings,ledger:{accounts:[{id:'a',kind:'wallet',currency:'USD',ledgerAvailableMinor:'248050',heldMinor:'0'},{id:'b',kind:'wallet',currency:'USDT',ledgerAvailableMinor:'350250000',heldMinor:'0'}],reconciliation:'matched'},pendingDepositsMinor:{USD:'0',USDT:'0'},orders:rows,total:rows.length,page:0,addresses:[]};}
 if(p.includes('/manual-funds/orders/'))return {order:manual,events:[{action:'create',createdAt:at},{action:'worker',createdAt:at}],mode:'live',enabled:false,approvalRequired:false};
 if(p.includes('/manual-funds'))return {orders:[manual],total:1,page:0,mode:'live',enabled:false};
 if(p.includes('/balances'))return {rows:[row],summary:row,total:1,currency,page:0,mode:'live',observedAt:at,permissions:['read'],movements:[],cards:[],movementTotal:0,cardTotal:0};
 if(p.includes('/card-issuing/products')){const products=[{id:productId,name:'Business USD',bin:'43612080',network:'visa',feeMinor:'1000',minimumMinor:'2000',revision:1,status:'active'},{id:'30000000-0000-0000-0000-000000000002',name:'Business Plus',bin:'43612078',network:'visa',feeMinor:'1500',minimumMinor:'5000',revision:1,status:'active'}];if(p.includes('/products/'))return {product:products.find(v=>p.endsWith(v.id))||products[0],prices:[{scopeKind:'group',scopeId:'preview-group',feeMinor:'800'},{scopeKind:'customer',scopeId:customerId,feeMinor:'500'}]};return products.filter(v=>!q.get('q')||(v.name+' '+v.bin).includes(q.get('q')));}
 if(p.includes('/ops/overview')){const daily=Array.from({length:Number(q.get('days')||7)},(_,i)=>({date:'2026-09-'+String(i+1).padStart(2,'0'),incomingMinor:String((i+2)*120000),outgoingMinor:String((i+1)*75000),netMinor:String((i+2)*120000-(i+1)*75000),posted:12+i,pending:2,failed:1,total:15+i}));return {mode:'production',asOf:at,revision:'preview',range:{timezone:'Asia/Hong_Kong'},coverage:{complete:false,reason:'仅合成数据。真实数据覆盖完整性需要独立核验。'},totals:{incomingMinor:daily.reduce((n,r)=>n+BigInt(r.incomingMinor),0n).toString(),outgoingMinor:daily.reduce((n,r)=>n+BigInt(r.outgoingMinor),0n).toString(),netMinor:daily.reduce((n,r)=>n+BigInt(r.netMinor),0n).toString(),transactions:daily.reduce((n,r)=>n+r.total,0),pending:14,failed:7},daily,statuses:[{status:'succeeded',count:105},{status:'pending',count:14},{status:'failed',count:7}],merchants:[],availability:{merchants:false,cards:false},sync:{lastSuccessAt:null,mode:'manual'}};}
 if(p.includes('/fund-records')){const rows=orders.map(o=>({...o,id:'crypto_'+o.id+'_principal',source:'crypto',orderId:o.id,status:o.state,customerName:'Northstar Commerce',fundingSource:'funds_wallet',direction:o.kind==='otc'?'exchange':o.kind==='deposit'?'in':'out'}));const row=rows.find(o=>decodeURIComponent(p).endsWith(o.id));return {mode:'live',records:rows,total:rows.length,page:0,record:row,evidence:[],coverage:'本地合成记录，仅验证界面。'};}
 throw new Error('预览尚未配置此关联页面');
}
const api=`export const manualRequest=${read.toString()};export const cryptoRequest=manualRequest,issuingRequest=manualRequest,liveGet=manualRequest;export const fundRecordsGet=(path)=>manualRequest(path);export const manualError=e=>e.message,cryptoError=manualError,authMessage=manualError;export class SessionError extends Error{};export class IssuingError extends Error{};`;
const auth=`const session={id:'preview',operator:true,mfaVerified:true,customers:[]};export const useAuth=()=>({ready:true,authenticated:true,user:{uid:'preview',email:'operator@example.invalid'},profile:{displayName:'Preview operator'},session,signOut:()=>{}});`;
const entry=`import React from 'react';import{createRoot}from'react-dom/client';import{BrowserRouter,Routes,Route}from'react-router-dom';import{ThemeProvider,CssBaseline}from'@mui/material';import theme from '/packages/shared/src/theme.ts';import BalancesPage from '/apps/admin/src/operations/BalancesPage.tsx';import CryptoFundsPage from '/apps/admin/src/operations/CryptoFundsPage.tsx';import PricingPage from '/apps/admin/src/operations/PricingPage.tsx';import OperationsPage from '/apps/admin/src/operations/OperationsPage.tsx';import FundRecordsPage from '/apps/admin/src/operations/FundRecordsPage.tsx';import '@fontsource/public-sans/400.css';import '@fontsource/public-sans/600.css';import '@fontsource/public-sans/700.css';import '/packages/shared/src/styles.css';createRoot(document.getElementById('root')).render(<ThemeProvider theme={theme}><CssBaseline/><BrowserRouter><Routes>{['/finance/balances','/finance/balances/:customerId','/finance/balances/:customerId/orders/:orderId'].map(path=><Route key={path} path={path} element={<BalancesPage/>}/>)}{['/finance/crypto-flows','/finance/otc','/finance/withdrawals'].flatMap(path=>[path,path+'/orders/:orderId']).map(path=><Route key={path} path={path} element={<CryptoFundsPage/>}/>)}{['/pricing','/pricing/products/:productId'].map(path=><Route key={path} path={path} element={<PricingPage/>}/>)}<Route path="/reports" element={<OperationsPage report/>}/><Route path="/finance/fund-records" element={<FundRecordsPage/>}/></Routes></BrowserRouter></ThemeProvider>);`;
const server=await createServer({root:process.cwd(),configFile:false,cacheDir:'/tmp/moventra-finance-preview-cache',publicDir:resolve('packages/assets/public'),resolve:{dedupe:['react','react-dom']},esbuild:{jsx:'automatic'},server:{host:'127.0.0.1',port:8907,strictPort:true},plugins:[{name:'finance-preview',enforce:'pre',resolveId(id){if(id==='/finance-preview.tsx')return '\0finance-entry';if(id.endsWith('/AuthContext'))return '\0finance-auth';if(['/manualFundsApi','/cryptoApi','/issuing/api','/liveApi','/fundRecordsApi'].some(s=>id.endsWith(s)))return '\0finance-api'},load(id){if(id==='\0finance-auth')return auth;if(id==='\0finance-api')return api;if(id==='\0finance-entry')return ts.transpileModule(entry,{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText},configureServer(s){s.middlewares.use((req,res,next)=>{if(req.url?.startsWith('/admin-api')||req.url?.startsWith('/client-api')){res.statusCode=403;res.end('No live API');return}if(req.headers.accept?.includes('text/html')){res.setHeader('Content-Type','text/html');res.end('<!doctype html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>资金与财务 · 合成预览</title></head><body><div id="root"></div><div style="position:fixed;bottom:6px;right:8px;font:11px sans-serif;background:#f5f7fa;padding:5px;z-index:1600">合成预览 · 所有写入已禁用 · <a href="/finance/fund-records">资金记录</a></div><script type="module" src="/finance-preview.tsx"></script></body></html>')}else next()})}}]});await server.listen();console.log('http://127.0.0.1:8907/finance/balances');
