import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';
import React from 'react';
import Renderer,{act} from 'react-test-renderer';
import {MemoryRouter} from 'react-router-dom';
import ts from 'typescript';
const require=createRequire(import.meta.url),uri=s=>'data:text/javascript;base64,'+Buffer.from(s).toString('base64'),resolve=s=>pathToFileURL(require.resolve(s)).href;
const compile=p=>ts.transpileModule(readFileSync(new URL(p,import.meta.url),'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext,jsx:ts.JsxEmit.ReactJSX}}).outputText;
const fixture=globalThis.__checkout={calls:[],timeout:true,products:[]};
globalThis.document={hidden:false,addEventListener(){},removeEventListener(){}};
const storage=new Map();globalThis.sessionStorage={getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k),key:i=>[...storage.keys()][i],get length(){return storage.size}};
const shell=uri(`import React from ${JSON.stringify(resolve('react'))};const Pass=({children,...p})=>React.createElement('div',p,children);export const Box=Pass,Paper=Pass,Stack=Pass,Typography=Pass,CircularProgress=()=>null;export const Alert=({children,action})=>React.createElement('div',null,children,action);export const Button=({children,...p})=>React.createElement('button',p,children);export const TextField=p=>React.createElement('input',p),Checkbox=p=>React.createElement('input',{...p,type:'checkbox'});export const FormControlLabel=({control,label})=>React.createElement('label',null,control,label);`);
const api=uri(`export class IssuingError extends Error{};export async function issuingRequest(path,body,key){let f=globalThis.__checkout;f.calls.push({path,body,key});if(path.endsWith('/products'))return f.products;if(path.includes('/products?'))return f.products;if(path.includes('/products/'))return f.products[0];if(path.endsWith('/wallet'))return {availableMinor:'10000',currency:'USD',mode:'isolated'};if(path.endsWith('/terms'))return {version:'v1',text:'fixture terms',digest:'digest'};if(path.endsWith('/quotes'))return {id:'quote1',termsVersion:'v1',feeMinor:'500',fundingMinor:body.fundingMinor,totalMinor:String(BigInt(body.fundingMinor)+500n),expiresAt:new Date(Date.now()+300000).toISOString()};if(body&&path.endsWith('/orders')){if(f.timeout)throw new Error('结果尚未确认');return {id:'order1',state:'active'}};if(path.includes('/orders/'))return {id:'order1',state:'active',feeMinor:'500',fundingMinor:'1000',cardName:'Alex',productName:'BIN A',bin:'990001'};return [];}`);
const contract=uri(compile('../../packages/shared/src/issuing/contract.ts'));
const pending=uri(compile('../../packages/shared/src/issuing/pending.ts'));
const rewrite=code=>code.replace(/from ["']([^"']+)["']/g,(_,s)=>'from '+JSON.stringify(s==='@mui/material'?shell:s==='./api'||s.endsWith('/issuing/api')?api:s==='./contract'||s.endsWith('/issuing/contract')?contract:s.endsWith('/issuing/pending')?pending:s.endsWith('/issuing/ui')?ui:resolve(s)));
const ui=uri(rewrite(compile('../../packages/shared/src/issuing/ui.tsx')));
const App=(await import(uri(rewrite(compile('../../apps/client/src/issuing/CardIssuing.tsx'))))).default;
const flush=()=>new Promise(r=>setImmediate(r));
const id='10000000-0000-4000-8000-000000000001';
async function mount(){let tree;await act(async()=>{tree=Renderer.create(React.createElement(MemoryRouter,{initialEntries:['/portal/cards/new?product='+id]},React.createElement(App,{customerId:id,uid:'alice'})));await flush();await flush()});return tree}
const buttons=t=>t.root.findAllByType('button');
const text=t=>JSON.stringify(t.toJSON());
test('checkout requires both declarations, resets on amount change, and restores identical payment after timeout/remount',async()=>{
 fixture.calls=[];fixture.timeout=true;storage.clear();fixture.products=[{id,name:'BIN A',bin:'990001',network:'visa',minimumMinor:'1000',feeMinor:'500',blockedReason:'',status:'active'}];
 let tree=await mount();
 await act(async()=>{buttons(tree).find(b=>b.props.children==='获取最新费用').props.onClick();await flush()});
 const pay=()=>buttons(tree).find(b=>String(b.props.children).startsWith('确认支付'));
 assert.equal(pay().props.disabled,true);
 const check=()=>tree.root.findAllByType('input').filter(n=>n.props.type==='checkbox');
 await act(()=>check()[0].props.onChange({target:{checked:true}}));assert.equal(pay().props.disabled,true);
 await act(()=>check()[1].props.onChange({target:{checked:true}}));assert.equal(pay().props.disabled,false);
 await act(()=>tree.root.findAllByType('input').find(n=>n.props.label==='首充金额 · USD').props.onChange({target:{value:'20'}}));
 assert.equal(pay().props.disabled,true);assert.equal(check()[0].props.checked,false);
 await act(async()=>{buttons(tree).find(b=>b.props.children==='获取最新费用').props.onClick();await flush()});
 await act(()=>{check()[0].props.onChange({target:{checked:true}});check()[1].props.onChange({target:{checked:true}})});
 await act(async()=>{pay().props.onClick();await flush()});
 assert.match(text(tree),/结果尚未确认/);
 const first=fixture.calls.find(c=>c.path.endsWith('/orders')&&c.body);assert.equal(first.body.acceptedTerms,true);assert.equal(first.body.lawfulUse,true);assert.equal(storage.size,1);
 await act(()=>tree.unmount());fixture.timeout=false;tree=await mount();
 await act(async()=>{buttons(tree).find(b=>b.props.children==='查询并恢复原请求').props.onClick();await flush()});
 const writes=fixture.calls.filter(c=>c.path.endsWith('/orders')&&c.body);assert.equal(writes.length,2);assert.deepEqual(writes[0],writes[1]);assert.equal(storage.size,0);assert.match(text(tree),/开卡成功/);
 await act(()=>tree.unmount());
});
test('pending payment is isolated by identity and cleared on logout',async()=>{
 const m=await import(pending);storage.clear();m.savePending(m.pendingKey('alice',id),{key:'key',path:'path',body:{}});
 assert.equal(m.readPending(m.pendingKey('bob',id)),null);m.clearIssuingPending();assert.equal(storage.size,0);
});
