import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';
import React from 'react';
import Renderer, { act } from 'react-test-renderer';
import ts from 'typescript';
const require = createRequire(import.meta.url);
const uri = text => 'data:text/javascript;base64,' + Buffer.from(text).toString('base64');
const source = readFileSync(new URL('../../packages/shared/src/pages/LoginPage.tsx', import.meta.url), 'utf8');
const ui = uri(`export const ${['Alert','Box','Button','CircularProgress','Dialog','DialogActions','DialogContent','DialogTitle','Divider','IconButton','InputAdornment','Link','MenuItem','Stack','TextField','Typography','Icon','Navigate'].map(n => `${n}='${n}'`).join(',')}; export const useLocation=()=>({state:null});`);
const state = globalThis.__loginDialog = {};
const auth = uri('export const usesFirebaseAuth=true;export const useAuth=()=>globalThis.__loginDialog;');
const other = uri(`export const isAdminSite=false;export const useLocale=()=>({t:s=>s});export const authMessage=e=>e.message;export default ({children})=>children;`);
let { outputText } = ts.transpileModule(source, { compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ESNext, jsx: ts.JsxEmit.ReactJSX } });
outputText = outputText.replace(/from ["']([^"']+)["']/g, (_, name) => `from ${JSON.stringify(name==='react'||name==='react/jsx-runtime'?pathToFileURL(require.resolve(name)).href:name.includes('AuthContext')?auth:name==='@mui/material'||name==='@iconify/react'||name==='react-router-dom'?ui:other)}`);
const { LoginPage } = await import(uri(outputText));
globalThis.requestAnimationFrame = fn => fn();
const event = { preventDefault() {} };
const fields = view => view.root.findAllByType('TextField');
const buttons = view => view.root.findAllByType('Button');
const form = view => view.root.findByType('Dialog').findByType('Box');
function reset() { Object.assign(state, { authenticated:false,user:null,ready:true,loginError:null,factors:[],signIn:async()=>{},completeMfa:async()=>{},signInWithGoogle:async()=>{},signOut:()=>{state.factors=[];} }); }
test('login retains credentials form behind a modal; cancel discards challenge and entered code', async () => {
  reset(); state.factors=[{uid:'factor-1',name:'Authenticator'}];
  let view; await act(async()=>{view=Renderer.create(React.createElement(LoginPage));});
  assert.equal(view.root.findByType('Dialog').props.open,true);
  assert.equal(fields(view).find(f=>f.props.autoComplete==='username').props.disabled,true);
  await act(async()=>fields(view).find(f=>f.props.autoComplete==='one-time-code').props.onChange({target:{value:'12a3456'}}));
  assert.equal(fields(view).find(f=>f.props.autoComplete==='one-time-code').props.value,'123456');
  await act(async()=>buttons(view).find(b=>b.props.children==='取消').props.onClick());
  assert.equal(state.factors.length,0);
  assert.equal(view.root.findByType('Dialog').props.open,false);
  assert.equal(fields(view).find(f=>f.props.autoComplete==='one-time-code').props.value,'');
  view.unmount();
});
test('MFA blocks duplicate submits and cancellation while verifying, then supports error retry', async () => {
  reset(); state.factors=[{uid:'factor-1',name:'Authenticator'}];
  const calls=[]; let reject;
  state.completeMfa=(...args)=>{calls.push(args);return new Promise((_,r)=>{reject=r;});};
  let view; await act(async()=>{view=Renderer.create(React.createElement(LoginPage));});
  await act(async()=>fields(view).find(f=>f.props.autoComplete==='one-time-code').props.onChange({target:{value:'123456'}}));
  let attempt;
  await act(async()=>{attempt=form(view).props.onSubmit(event);void form(view).props.onSubmit(event);});
  assert.deepEqual(calls,[['factor-1','123456']]);
  await act(async()=>view.root.findByType('Dialog').props.onClose());
  assert.equal(state.factors.length,1);
  await act(async()=>{reject(new Error('invalid-code'));await attempt;});
  assert.equal(view.root.findByType('Dialog').props.open,true);
  assert.equal(view.root.findByType('Alert').props.children,'invalid-code');
  assert.equal(fields(view).find(f=>f.props.autoComplete==='one-time-code').props.value,'');
  state.completeMfa=async (...args)=>{calls.push(args);state.factors=[];state.user={uid:'verified'};};
  await act(async()=>fields(view).find(f=>f.props.autoComplete==='one-time-code').props.onChange({target:{value:'654321'}}));
  await act(async()=>form(view).props.onSubmit(event));
  assert.deepEqual(calls[1],['factor-1','654321']);
  assert.equal(view.root.findByType('Navigate').props.to,'/session');
  view.unmount();
});
test('multiple enrolled authenticators use selected factor and clear stale code on switch', async()=>{
  reset(); state.factors=[{uid:'one',name:'One'},{uid:'two',name:'Two'}];
  let submitted;state.completeMfa=async(...args)=>{submitted=args;};
  let view;await act(async()=>{view=Renderer.create(React.createElement(LoginPage));});
  await act(async()=>fields(view).find(f=>f.props.autoComplete==='one-time-code').props.onChange({target:{value:'111111'}}));
  await act(async()=>fields(view).find(f=>f.props.select).props.onChange({target:{value:'two'}}));
  assert.equal(fields(view).find(f=>f.props.autoComplete==='one-time-code').props.value,'');
  await act(async()=>fields(view).find(f=>f.props.autoComplete==='one-time-code').props.onChange({target:{value:'222222'}}));
  await act(async()=>form(view).props.onSubmit(event));assert.deepEqual(submitted,['two','222222']);view.unmount();
});
