// Local UI fixture only. No Firebase, production API, or real credentials.
import { createServer } from 'vite';
import ts from 'typescript';
import { resolve } from 'node:path';
const transpile = source => ts.transpileModule(source, { compilerOptions: { jsx: ts.JsxEmit.ReactJSX, module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 } }).outputText;
const auth = `import {useState} from 'react';export const usesFirebaseAuth=true;
export function useAuth(){const [factors,setFactors]=useState([]),[user,setUser]=useState(null);return {ready:true,user,authenticated:false,loginError:null,factors,signIn:async()=>setFactors([{uid:'preview',name:'Authenticator'}]),signInWithGoogle:async()=>setFactors([{uid:'preview',name:'Authenticator'}]),completeMfa:async(_,code)=>{await new Promise(r=>setTimeout(r,700));if(code!=='123456')throw new Error('验证码无效，请重试。');setFactors([]);setUser({uid:'local-fixture'});},signOut:()=>{setFactors([]);setUser(null);}}}`;
const entry = `import React from 'react';import{createRoot}from'react-dom/client';import{BrowserRouter,Routes,Route}from'react-router-dom';import{ThemeProvider,CssBaseline}from'@mui/material';import theme from '/packages/shared/src/theme.ts';import{LoginPage}from'/packages/shared/src/pages/LoginPage.tsx';import '@fontsource/public-sans/400.css';import '@fontsource/public-sans/600.css';import '@fontsource/public-sans/700.css';createRoot(document.getElementById('root')).render(<ThemeProvider theme={theme}><CssBaseline/><BrowserRouter><Routes><Route path='/session' element={<p>隔离验证完成，不代表真实登录</p>}/><Route path='*' element={<LoginPage/>}/></Routes></BrowserRouter></ThemeProvider>);`;
const server = await createServer({ root: resolve('.'), publicDir: resolve('packages/assets/public'), configFile:false, esbuild:{jsx:'automatic'}, server:{host:'127.0.0.1',port:8866,strictPort:true}, plugins:[{name:'isolated-login-preview',enforce:'pre',resolveId(id){if(id==='/login-preview.tsx')return '\0login-entry';if(id.endsWith('/AuthContext'))return '\0login-auth';if(id.endsWith('/liveApi'))return '\0login-api';if(id.endsWith('/site'))return '\0login-site';},load(id){if(id==='\0login-entry')return transpile(entry);if(id==='\0login-auth')return auth;if(id==='\0login-api')return 'export const authMessage=e=>e.message;';if(id==='\0login-site')return "export const isAdminSite=location.pathname.startsWith('/admin');";},configureServer(s){s.middlewares.use((req,res,next)=>{if(req.url?.startsWith('/client-api')||req.url?.startsWith('/admin-api')){res.statusCode=403;res.end('Preview only');return;}if(req.headers.accept?.includes('text/html')){res.setHeader('Content-Type','text/html');res.end('<!doctype html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>隔离登录预览</title></head><body><div id="root"></div><script type="module" src="/login-preview.tsx"></script></body></html>');}else next();});}}] });
await server.listen();console.log('Isolated login UI: http://127.0.0.1:8866/portal/login (synthetic code 123456)');
