// Real message components + the explicitly enabled local PostgreSQL test API.
// No Firebase credentials or financial endpoints are used in this harness.
import {createServer} from 'vite';
import ts from 'typescript';
import {resolve} from 'node:path';
const root=resolve('.');
const auth=`const isAdmin=()=>location.pathname.startsWith('/operations');export const useAuth=()=>({ready:true,authenticated:true,user:{uid:isAdmin()?'staff':'alice',email:'fixture@example.invalid'},session:{id:isAdmin()?'00000000-0000-0000-0000-000000000003':'00000000-0000-0000-0000-000000000001',operator:isAdmin(),mfaVerified:true,customers:[],staffScopes:[]},signOut:async()=>{}});`;
const api=`export const messageError=e=>e.message;export async function messageRequest(path,body,key){const res=await fetch(path,{method:body===undefined?'GET':'POST',headers:{Authorization:'Bearer '+(location.pathname.startsWith('/operations')?'staff':'alice'),'Content-Type':'application/json','Idempotency-Key':key||''},body:body===undefined?undefined:JSON.stringify(body)});const v=await res.json();if(!res.ok)throw new Error(v.error?.code||'unavailable');return v.data;}`;
const entry=`import React from 'react';import{createRoot}from'react-dom/client';import{BrowserRouter,Link,useLocation}from'react-router-dom';import{ThemeProvider,CssBaseline,Container,Stack,Typography,Alert,Button}from'@mui/material';import theme from '/packages/shared/src/theme.ts';import Center,{MessageBell}from'/packages/shared/src/messages/MessageCenter.tsx';import Admin from '/apps/admin/src/operations/MessagesPage.tsx';import '@fontsource/public-sans/400.css';import '@fontsource/public-sans/600.css';import '@fontsource/public-sans/700.css';const customerId='10000000-0000-0000-0000-000000000001';function App(){const {pathname,state}=useLocation();return pathname.startsWith('/operations')?<Admin/>:<Container maxWidth="lg" sx={{py:4}}><Stack direction="row" justifyContent="space-between"><Typography variant="h4">消息中心</Typography><MessageBell customerId={customerId}/></Stack><Alert severity="info" sx={{my:2}}>本地合成身份 · 隔离 PostgreSQL · 不执行真实资金操作</Alert>{pathname.startsWith('/portal/funds/orders/')?<><Typography>隔离订单关联：{pathname.split('/').at(-1)}</Typography><Button component={Link} to={state?.messageReturn||'/portal/messages'}>返回消息详情</Button></>:<Center customerId={customerId}/>}</Container>};createRoot(document.getElementById('root')).render(<ThemeProvider theme={theme}><CssBaseline/><BrowserRouter><App/></BrowserRouter></ThemeProvider>);`;
const server=await createServer({root,configFile:false,cacheDir:'/tmp/moventra-messages-vite-cache',resolve:{dedupe:['react','react-dom']},publicDir:resolve('packages/assets/public'),esbuild:{jsx:'automatic'},server:{host:'127.0.0.1',port:8876,strictPort:true,proxy:{'/client-api':{target:'http://127.0.0.1:18746'},'/admin-api':{target:'http://127.0.0.1:18746'}}},plugins:[{name:'message-fixture',enforce:'pre',resolveId(id){if(id==='/message-preview.tsx')return '\0message-entry';if(id.endsWith('/AuthContext'))return '\0message-auth';if(id.endsWith('/messageApi'))return '\0message-api'},load(id){if(id==='\0message-auth')return auth;if(id==='\0message-api')return api;if(id==='\0message-entry')return ts.transpileModule(entry,{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText},configureServer(s){s.middlewares.use((req,res,next)=>{if(req.headers.accept?.includes('text/html')){res.setHeader('Content-Type','text/html');res.end('<!doctype html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Moventra · 消息隔离验收</title></head><body><div id="root"></div><script type="module" src="/message-preview.tsx"></script></body></html>')}else next()})}}]});await server.listen();console.log('Message browser fixture: http://127.0.0.1:8876/portal/messages');
