import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';
import React from 'react';
import Renderer,{act} from 'react-test-renderer';
import ts from 'typescript';
import {handle} from '../../deploy/cloudflare/gateway.mjs';
const require=createRequire(import.meta.url),resolve=s=>pathToFileURL(require.resolve(s)).href;
const uri=s=>'data:text/javascript;base64,'+Buffer.from(s).toString('base64');
const state=globalThis.__testWalletFixture={requests:[]};
const shell=uri(`import React from ${JSON.stringify(resolve('react'))};const Pass=({children})=>React.createElement('div',null,children);export const Box=Pass,Paper=Pass,Stack=Pass,Table=Pass,TableBody=Pass,TableCell=Pass,TableContainer=Pass,TableHead=Pass,TableRow=Pass,Typography=Pass;export const Chip=({label})=>React.createElement('span',null,label);export const Alert=({children,action})=>React.createElement('div',null,children,action);export const Button=({children,...p})=>React.createElement('button',p,children);`);
const api=uri(`export const liveGet=path=>new Promise((resolve,reject)=>globalThis.__testWalletFixture.requests.push({path,resolve,reject}));export const authMessage=()=> '读取失败';`);
const raw=readFileSync(new URL('../../apps/client/src/portal/TestWallet.tsx',import.meta.url),'utf8');
const code=ts.transpileModule(raw,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext,jsx:ts.JsxEmit.ReactJSX}}).outputText.replace(/from ["']([^"']+)["']/g,(_,name)=>'from '+JSON.stringify(name==='@mui/material'?shell:name.endsWith('/liveApi')?api:resolve(name)));
const {default:Wallet,testMoney}=await import(uri(code));
const flush=()=>new Promise(r=>setImmediate(r));
const content=n=>typeof n==='string'?n:Array.isArray(n)?n.map(content).join(''):n?.children?content(n.children):'';
const text=t=>content(t.toJSON());
const fixture=id=>({customerId:id,mode:'online_test',enabled:true,executionEligible:false,withdrawalEligible:false,balances:[{currency:'USD',scale:2,amountMinor:'10000000'},{currency:'USDT',scale:6,amountMinor:'20009000000'}],grants:[{requestId:'fixture-grant',usdMinor:'10000000',usdtMinor:'20009000000',createdAt:'2026-09-18T00:00:00Z',reason:'用户授权线上测试'}],hasMore:false});
test('测试余额精确显示、加载失败重试、跨客户旧响应隔离',async()=>{
 assert.equal(testMoney('9007199254740993',6),'9,007,199,254.740993');
 let tree;await act(async()=>{tree=Renderer.create(React.createElement(Wallet,{customerId:'A'}));await flush();});
 assert.ok(text(tree).includes('正在读取'));assert.ok(!text(tree).includes('0.00'));
 await act(async()=>{state.requests[0].resolve(fixture('A'));await flush();});
 for(const s of ['100,000.00','20,009.000000','测试资金','不可提现'])assert.ok(text(tree).includes(s),s);
 await act(async()=>{tree.update(React.createElement(Wallet,{customerId:'B'}));await flush();});assert.ok(!text(tree).includes('100,000.00'));
 const old=state.requests[1];await act(async()=>{tree.update(React.createElement(Wallet,{customerId:'C'}));await flush();old.resolve(fixture('B'));state.requests[2].reject(new Error('down'));await flush();});
 assert.ok(text(tree).includes('读取失败'));assert.ok(!text(tree).includes('100,000.00'));
 await act(async()=>{tree.root.findByType('button').props.onClick();await flush();});
 await act(async()=>{state.requests[3].resolve({...fixture('C'),enabled:false,balances:[],grants:[]});await flush();});assert.ok(text(tree).includes('尚未配置测试余额'));
 await act(()=>tree.unmount());
});
test('test wallet gateway rejects all writes and cross-site requests',async()=>{
 const path='/client-api/v1/customers/10000000-0000-0000-0000-000000000001/test-wallet',env={SITE_KIND:'client',API_ORIGIN:'https://api.invalid'};
 for(const method of ['POST','PUT','PATCH','DELETE'])assert.equal((await handle(new Request('https://web.invalid'+path,{method}),env,()=>assert.fail('write forwarded'))).status,405);
 assert.equal((await handle(new Request('https://web.invalid'+path),env)).status,401);
 assert.equal((await handle(new Request('https://web.invalid'+path),{...env,SITE_KIND:'admin'})).status,404);
 const res=await handle(new Request('https://web.invalid'+path,{headers:{Authorization:'Bearer fixture'}}),env,async(url,options)=>{assert.equal(url.pathname,path);assert.equal(options.method,'GET');return Response.json({data:fixture('A')});});assert.equal(res.status,200);assert.equal(res.headers.get('Cache-Control'),'no-store');
});
