import FinanceWorkspace from './FinanceWorkspace';
import {useEffect,useState} from 'react';
import {Box,Chip,Tab,Tabs,Alert,Button,MenuItem,Paper,Stack,Table,TableBody,TableCell,TableContainer,TableHead,TableRow,TextField,Typography} from '@mui/material';
import {Link,Navigate,useLocation,useParams,useSearchParams} from 'react-router-dom';
import {DashboardLayout} from '../components/DashboardLayout';
import {PageSkeleton} from '../../../../packages/shared/src/components/AsyncState';
import {useAuth} from '../../../../packages/shared/src/auth/AuthContext';
import {manualRequest,manualError} from '../../../../packages/shared/src/auth/manualFundsApi';
import {manualLabels,type BalanceData} from '../../../../packages/shared/src/auth/manualFundsContract';
import {cryptoMoney} from '../../../../packages/shared/src/auth/cryptoContract';
import ManualFunds from '../../../../packages/shared/src/finance/ManualFunds';
import './balances.css';
const money=(v:string|null,c:string)=>v===null?'—':cryptoMoney(v,c);
export default function BalancesPage(){const {ready,authenticated,user,session}=useAuth();if(!ready)return <PageSkeleton/>;if(!authenticated||!session?.operator||!session.mfaVerified)return <Navigate to={user?'/session?security=1':'/admin/login'} replace/>;return <BalanceContent key={user?.uid}/>}
export function BalanceContent(){
 const {customerId,orderId}=useParams(),location=useLocation();const [params,setParams]=useSearchParams();
 const currency=params.get('currency')||'USD',page=Math.max(0,Number(params.get('page'))||0),q=params.get('q')||'',status=params.get('status')||'',tab=params.get('tab')||'orders',detailPage=Math.max(0,Number(params.get('detailPage'))||0);
 const [search,setSearch]=useState(q),[data,setData]=useState<BalanceData|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[tick,setTick]=useState(0);
 useEffect(()=>setSearch(q),[q]);
 useEffect(()=>{let active=true,running=false;setData(null);setError('');async function load(){if(running)return;running=true;setLoading(true);try{const query=new URLSearchParams({currency,...(!customerId?{page:String(page),q,status}:{page:String(detailPage)})});const v=await manualRequest<BalanceData>(`/admin-api/v1/balances${customerId?'/'+customerId:''}?${query}`);if(active){setData(v);setError('')}}catch(e){if(active){setError(manualError(e));setData(null)}}finally{running=false;if(active)setLoading(false)}}void load();const timer=setInterval(()=>{if(!document.hidden)void load()},10000);return()=>{active=false;clearInterval(timer)}},[customerId,currency,page,q,status,tick,detailPage]);
 function update(k:string,v:string){const next=new URLSearchParams(params);v?next.set(k,v):next.delete(k);if(k!=='page')next.delete('page');setParams(next,{state:location.state})}
 const row=data?.rows[0],base=customerId?`/finance/balances/${customerId}`:'/finance/balances';
 const returnPath=typeof location.state?.balanceReturn==='string'&&/^\/finance\/balances(?:\?|$)/.test(location.state.balanceReturn)?location.state.balanceReturn:'/finance/balances';
 return <DashboardLayout production><FinanceWorkspace><Stack spacing={2.5} className={customerId?'balance-detail':'finance-balances'}>
 <Stack direction={{xs:'column',sm:'row'}} gap={2} alignItems={{sm:'center'}} justifyContent="space-between">
 <Box>{customerId&&<Button component={Link} to={returnPath} className="balance-back">← 余额查询</Button>}<Typography variant="h4" sx={{fontSize:customerId?26:undefined,letterSpacing:'-.5px'}}> {customerId?'用户资金详情':'余额查询'}</Typography></Box>
 <Stack direction="row" spacing={1} alignItems="center">{customerId&&<TextField size="small" select label="查看币种" value={currency} onChange={e=>update('currency',e.target.value)} sx={{width:120}}><MenuItem value="USD">USD</MenuItem><MenuItem value="USDT">USDT</MenuItem></TextField>}<Button variant="outlined" disabled={loading} onClick={()=>setTick(n=>n+1)}>{loading?'读取中…':'刷新余额'}</Button></Stack>
 </Stack>
 {!customerId&&<div className="finance-toolbar"><TextField size="small" className="finance-search" label="邮箱、姓名或客户 ID" value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')update('q',search.trim())}}/><TextField size="small" select label="用户状态" value={status} onChange={e=>update('status',e.target.value)}><MenuItem value="">全部</MenuItem><MenuItem value="active">正常</MenuItem><MenuItem value="disabled">已停用</MenuItem></TextField><TextField size="small" select label="币种" value={currency} onChange={e=>update('currency',e.target.value)}><MenuItem value="USD">USD</MenuItem><MenuItem value="USDT">USDT</MenuItem></TextField><Button variant="contained" onClick={()=>update('q',search.trim())}>查询</Button></div>}
 {error&&<Alert severity="error" action={<Button onClick={()=>setTick(n=>n+1)}>重试</Button>}>{error}</Alert>}
 {loading&&!data&&<Typography>正在读取账户资金…</Typography>}
 {data&&<>
 {data.mode!=='live'&&<Alert severity="info">{data.mode==='shadow'?'当前为隔离账本，不代表线上真实余额。':'正式账本尚未启用，账户资料仍可查询。'}</Alert>}
 {customerId&&row&&<Box className="balance-identity">
 <Box className="balance-avatar" aria-hidden="true">{row.name.slice(0,1).toUpperCase()}</Box>
 <Box sx={{minWidth:0,flex:1}}><Stack direction="row" gap={1} alignItems="center" flexWrap="wrap"><Typography variant="h6" sx={{fontSize:18}}>{row.name}</Typography><Chip size="small" variant="outlined" color={row.service==='active'?'success':'default'} label={row.service==='active'?'服务已启用':row.service==='suspended'?'服务已暂停':'服务未启用'}/></Stack><Typography variant="body2" color="text.secondary" sx={{mt:.5,overflowWrap:'anywhere'}}>{row.email??'身份资料未找到'}</Typography><Typography variant="caption" color="text.secondary" sx={{display:'block',mt:.5,overflowWrap:'anywhere'}}>客户 ID · {row.customerId}</Typography></Box>
 <Button component={Link} to={`/finance/crypto-flows?customer=${customerId}`} size="small">其他资金流水 ↗</Button>
 </Box>}
 <Paper variant="outlined" className="balance-summary" sx={{p:0}}>
 <Box className="balance-metrics">{[['钱包可用',customerId?row?.walletMinor:data.summary.walletMinor],['预占资金',customerId?row?.heldMinor:data.summary.heldMinor],['卡资金',customerId?row?.cardsMinor:data.summary.cardsMinor],['已登记资金合计',customerId?row?.totalMinor:data.summary.totalMinor]].map(([title,value])=><Box key={String(title)} className="balance-metric"><Typography variant="body2" color="text.secondary">{title}</Typography><Typography className="balance-amount" sx={{fontSize:24,fontWeight:700,mt:1,fontVariantNumeric:'tabular-nums',overflowWrap:'anywhere'}}>{money(value??null,currency)}</Typography></Box>)}</Box>
 <Box className="balance-scope"><Box component="details"><Box component="summary" sx={{cursor:'pointer'}}>账本口径 · 仅含已登记资金</Box><Typography variant="caption" component="p" sx={{mt:1,maxWidth:760}}>{customerId?'本账户':'当前筛选范围'} · 钱包、卡分户及预占分别计入合计。仅含已登记账本资金，尚未登记的历史卡不计入；不代表上游资金池余额。</Typography></Box><Typography variant="caption">更新于 {new Date(data.observedAt).toLocaleString()}</Typography></Box>
 </Paper>
 {!customerId&&<><TableContainer component={Paper} variant="outlined"><Table size="small" className="finance-balance-table"><TableHead><TableRow>{['用户','邮箱','钱包可用','预占资金','卡资金','已登记合计','资金状态',''].map((s,i)=><TableCell key={i}>{s}</TableCell>)}</TableRow></TableHead><TableBody>{data.rows.map(r=><TableRow key={r.userId}><TableCell>{r.name}<Typography variant="caption" display="block" color="text.secondary">{r.status==='active'?'正常':'已停用'}</Typography></TableCell><TableCell>{r.email??'身份资料未找到'}</TableCell><TableCell>{money(r.walletMinor,currency)}</TableCell><TableCell>{money(r.heldMinor,currency)}</TableCell><TableCell>{money(r.cardsMinor,currency)}</TableCell><TableCell>{money(r.totalMinor,currency)}</TableCell><TableCell>{manualLabels[r.coverage]||r.coverage}{r.pendingOperations>0?` · ${r.pendingOperations} 笔待核对`:''}</TableCell><TableCell>{r.customerId?<Button component={Link} to={`/finance/balances/${r.customerId}?currency=${currency}`} state={{balanceReturn:location.pathname+location.search}}>详情</Button>:<Typography variant="caption">未建立客户账户</Typography>}</TableCell></TableRow>)}</TableBody></Table></TableContainer>{!data.rows.length&&<Typography>没有符合条件的用户</Typography>}<Stack direction="row" spacing={2}><Button disabled={page===0||loading} onClick={()=>update('page',String(page-1))}>上一页</Button><Typography>第 {page+1} 页 · 共 {data.total} 位用户</Typography><Button disabled={(page+1)*20>=data.total||loading} onClick={()=>update('page',String(page+1))}>下一页</Button></Stack></>}
 {customerId&&row&&<><Box className="balance-records">
 <Tabs value={orderId?'orders':(['orders','ledger','cards'].includes(tab)?tab:false)} onChange={(_,key)=>{const n=new URLSearchParams(params);n.set('tab',key);n.delete('detailPage');setParams(n,{state:location.state})}} variant="scrollable" scrollButtons="auto" aria-label="客户资金视图" sx={{borderBottom:1,borderColor:'divider',mb:2.5}}>{[['orders','人工出入金'],['ledger','资金流水'],['cards','关联卡片']].map(([key,title])=><Tab key={key} value={key} label={title} disabled={!!orderId&&key!=='orders'}/>)}</Tabs>
 <Box className="balance-record-content">
 {(tab==='orders'||orderId)&&<ManualFunds key={`${customerId}:${orderId||''}`} customerId={customerId} admin basePath={base} orderId={orderId} permissions={data.permissions} canOperate={row.status==='active'&&row.service==='active'&&row.onboarding==='approved'} onChanged={()=>setTick(n=>n+1)}/>}
 {!orderId&&tab==='ledger'&&<><Typography color="text.secondary">按正式分录显示转入、转出及预占，不将内部划转重复计作外部收支。</Typography><TableContainer component={Paper}><Table size="small"><TableHead><TableRow>{['时间','方向','金额','关联'].map(x=><TableCell key={x}>{x}</TableCell>)}</TableRow></TableHead><TableBody>{data.movements?.map(m=><TableRow key={m.id}><TableCell>{new Date(m.createdAt).toLocaleString()}</TableCell><TableCell>{({wallet:'钱包',card:'卡分户',escrow:'预占',transit:'在途',clearing:'清算',fee:'费用'} as Record<string,string>)[m.from]||m.from} → {({wallet:'钱包',card:'卡分户',escrow:'预占',transit:'在途',clearing:'清算',fee:'费用'} as Record<string,string>)[m.to]||m.to}</TableCell><TableCell>{cryptoMoney(m.amountMinor,currency)}</TableCell><TableCell>{m.evidenceRef.startsWith('manual-order:')?<Button component={Link} state={location.state} to={base+'/orders/'+m.evidenceRef.slice(13)+'?tab=orders'}>人工出入金订单</Button>:m.operationId}</TableCell></TableRow>)}</TableBody></Table></TableContainer>{!data.movements?.length&&<Typography>{data.mode==='disabled'?'资金流水尚未启用':'暂无资金流水'}</Typography>}</>}
 {!orderId&&tab==='cards'&&<><Typography color="text.secondary">仅显示已建立正式卡资金映射的卡片，不以渠道限额代替余额。</Typography><TableContainer component={Paper}><Table size="small"><TableHead><TableRow><TableCell>卡片</TableCell><TableCell>账面资金</TableCell><TableCell>操作</TableCell></TableRow></TableHead><TableBody>{data.cards?.map(c=><TableRow key={c.id}><TableCell>{c.name}</TableCell><TableCell>{cryptoMoney(c.amountMinor,currency)}</TableCell><TableCell><Button component={Link} to={'/cards/'+encodeURIComponent(c.cardId)+'?connection='+encodeURIComponent(c.connection)}>卡片详情</Button></TableCell></TableRow>)}</TableBody></Table></TableContainer>{!data.cards?.length&&<Typography>{data.mode==='disabled'?'卡资金尚未启用':'暂无已登记卡分户'}</Typography>}</>}
 {!orderId&&['ledger','cards'].includes(tab)&&<Stack direction="row" spacing={2}><Button disabled={detailPage===0||loading} onClick={()=>update('detailPage',String(detailPage-1))}>上一页</Button><Typography>第 {detailPage+1} 页 · 共 {tab==='ledger'?data.movementTotal||0:data.cardTotal||0} 条</Typography><Button disabled={loading||(detailPage+1)*20>=(tab==='ledger'?data.movementTotal||0:data.cardTotal||0)} onClick={()=>update('detailPage',String(detailPage+1))}>下一页</Button></Stack>}
 </Box></Box></>}
 </>}
 </Stack></FinanceWorkspace></DashboardLayout>;
}
