import {lazy,Suspense,useCallback,useEffect,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {Alert,Box,Button,Card,CardContent,CardHeader,Chip,CircularProgress,Collapse,Divider,Grid,LinearProgress,List,ListItem,ListItemText,MenuItem,Select,Stack,Table,TableBody,TableCell,TableContainer,TableHead,TableRow,Typography,useTheme} from '@mui/material';
import type {ApexOptions} from 'apexcharts';
import {Icon} from '@iconify/react';
import {liveGet,authMessage} from '../../../../packages/shared/src/auth/liveApi';
import {get} from '../../../../packages/shared/src/management/api';
import {money,maximum,ratio,percent,safeCsv,type Overview,type Daily} from './model';
const Chart=lazy(()=>import('react-apexcharts'));
const labels:Record<string,string>={posted:'来源已入账',succeeded:'投影已完成',pending:'待处理',failed:'失败',unknown:'其他'};
const time=(s:string|null|undefined)=>s?new Date(s).toLocaleString('zh-CN',{timeZone:'Asia/Hong_Kong',hour12:false}):'未连接';
function Empty({text,caption,height=240}:{text:string;caption?:string;height?:number}){return <Stack alignItems="center" justifyContent="center" gap={1} sx={{height,color:'text.secondary'}}><Icon icon="solar:chart-2-linear" width={32}/><Typography variant="body2">{text}</Typography>{caption&&<Typography variant="caption" sx={{maxWidth:300,textAlign:'center'}}>{caption}</Typography>}</Stack>;}
function useOptions():ApexOptions{const theme=useTheme();return {chart:{fontFamily:theme.typography.fontFamily,foreColor:theme.palette.text.secondary,toolbar:{show:false},animations:{enabled:false},zoom:{enabled:false}},colors:[theme.palette.primary.main,theme.palette.warning.main,theme.palette.error.main],grid:{borderColor:theme.palette.divider,strokeDashArray:3},stroke:{width:0},dataLabels:{enabled:false},legend:{position:'top',horizontalAlign:'right',fontSize:'12px',markers:{size:4}},tooltip:{theme:theme.palette.mode},xaxis:{axisTicks:{show:false},axisBorder:{show:false},labels:{style:{fontSize:'11px'}}},yaxis:{labels:{style:{fontSize:'11px'}}},plotOptions:{bar:{borderRadius:3,columnWidth:'42%'}},noData:{text:'当前范围暂无记录'}};}
function FundChart({rows,onSelect}:{rows:Daily[];onSelect:(day:string)=>void}){
 const theme=useTheme(),base=useOptions(),max=maximum(rows);
 const options:ApexOptions={...base,colors:[theme.palette.primary.main,theme.palette.warning.main],chart:{...base.chart,events:{dataPointSelection:(_e,_c,c)=>{const row=rows[c.dataPointIndex];if(row)onSelect(row.date);}}},xaxis:{...base.xaxis,categories:rows.map(r=>r.date),labels:{...base.xaxis?.labels,formatter:s=>String(s).slice(5).replace('-','/'),rotate:0,hideOverlappingLabels:true}},yaxis:{min:0,max:1,tickAmount:4,labels:{formatter:v=>money(String(max*BigInt(Math.round(v*1000000))/1000000n)).replace('.00','')}},tooltip:{shared:true,intersect:false,y:{formatter:(_v,{seriesIndex,dataPointIndex})=>money(rows[dataPointIndex]?.[seriesIndex===0?'incomingMinor':'outgoingMinor'])+' USD'}}};
 return <Box role="img" aria-label="每日资金流入流出柱形图，精确金额可在下方每日明细查看"><Suspense fallback={<Empty text="正在加载图表"/>}><Chart type="bar" height={295} options={options} series={[{name:'流入',data:rows.map(r=>r.incomingMinor===null?null:ratio(r.incomingMinor,max))},{name:'流出',data:rows.map(r=>r.outgoingMinor===null?null:ratio(r.outgoingMinor,max))}]}/></Suspense></Box>;
}
function VolumeChart({data}:{data:Overview}){
 const base=useOptions(),theme=useTheme();
 const options:ApexOptions={...base,colors:[theme.palette.primary.main,theme.palette.warning.main,theme.palette.error.main],chart:{...base.chart,stacked:true},xaxis:{...base.xaxis,categories:data.daily.map(r=>r.date.slice(5)),labels:{rotate:0,hideOverlappingLabels:true}},yaxis:{labels:{formatter:v=>Math.round(v).toLocaleString()}},tooltip:{shared:true,intersect:false,y:{formatter:v=>v+' 笔'}}};
 return <Box role="img" aria-label={data.mode==='production'?'每日交易笔数，按已完成、待处理和失败区分':'每日交易笔数，按已入账、待处理和失败区分'}><Suspense fallback={<Empty text="正在加载图表"/>}><Chart type="bar" height={270} options={options} series={[{name:data.mode==='production'?'已完成':'已入账',data:data.daily.map(r=>r.posted)},{name:'待处理',data:data.daily.map(r=>r.pending)},{name:'失败',data:data.daily.map(r=>r.failed)}]}/></Suspense></Box>;
}
export default function FundsOverview({source='production'}:{source?:'local'|'production'}){
 const theme=useTheme(),[params,setParams]=useSearchParams(),days=[7,14,30].includes(Number(params.get('days')))?Number(params.get('days')):7;
 const [data,setData]=useState<Overview>(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[refresh,setRefresh]=useState(0),[selected,setSelected]=useState<string|null>(null),[detail,setDetail]=useState(false),[basis,setBasis]=useState(false);
 useEffect(()=>{let active=true;setBusy(true);setError('');setData(undefined);setSelected(null);
 (source==='local'?get<Overview>('live/overview',{days}):liveGet<Overview>('/admin-api/v1/ops/overview?days='+days)).then(d=>{if(active)setData(d);}).catch(e=>{if(active)setError(source==='local'?e.message:e.code==='scope_required'?'当前账号没有交易统计范围，请检查客户交易读取授权。':authMessage(e));}).finally(()=>{if(active)setBusy(false);});
 return()=>{active=false;};},[days,source,refresh]);
 const exportRows=useCallback(()=>{if(!data)return;const lines=[['日期（香港时间）','流入USD分','流出USD分','净流量USD分',source==='local'?'来源已入账笔数':'投影已完成笔数','待处理笔数','失败笔数','全部笔数','覆盖完整'],...data.daily.map(r=>[r.date,r.incomingMinor,r.outgoingMinor,r.netMinor,r.posted,r.pending,r.failed,r.total,String(data.coverage.complete)])];const blob=new Blob(['\uFEFF'+lines.map(row=>row.map(safeCsv).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='moventra-funds-'+data.asOf.slice(0,10)+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);},[data,source]);
 const total=data?.totals,hasData=!!total?.transactions,rows=selected?data?.daily.filter(r=>r.date===selected):data?.daily;
 const statusColor=(s:string)=>s==='failed'?theme.palette.error.main:s==='pending'?theme.palette.warning.main:s==='posted'||s==='succeeded'?theme.palette.primary.main:theme.palette.grey[500];
 return <Stack spacing={3} component="section" aria-label="资金与运营总览" aria-busy={busy}>
 <Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" alignItems={{xs:'flex-start',sm:'center'}} gap={2}>
 <Box><Typography variant="h5">资金流与运营</Typography><Typography variant="body2" color="text.secondary" mt={.5}>查看收支趋势、交易状态与消费结构</Typography></Box>
 <Stack direction="row" gap={1.5}><Select size="small" value={days} inputProps={{'aria-label':'统计周期'}} onChange={e=>{const p=new URLSearchParams(params);p.set('days',String(e.target.value));setParams(p);}}>{[7,14,30].map(n=><MenuItem key={n} value={n}>最近 {n} 天</MenuItem>)}</Select><Button variant="outlined" onClick={()=>setRefresh(n=>n+1)} disabled={busy} startIcon={busy?<CircularProgress size={14}/>:<Icon icon="solar:refresh-linear"/>}>刷新</Button></Stack></Stack>
 <Stack direction="row" justifyContent="space-between" gap={1} flexWrap="wrap" alignItems="center"><Stack direction="row" gap={1} flexWrap="wrap"><Chip size="small" color="info" variant="outlined" label={source==='local'?'Slash 真实数据':'已授权交易投影'}/><Chip size="small" variant="outlined" label="USD · 香港时间"/><Chip size="small" variant="outlined" color="warning" label="覆盖尚未完整核实"/></Stack><Typography variant="caption" color="text.secondary">统计生成：{data?time(data.asOf):'—'}</Typography></Stack>
 {error&&<Alert severity="error" action={<Button color="inherit" onClick={()=>setRefresh(n=>n+1)}>重试</Button>}>{error}</Alert>}
 {!error&&data&&!hasData&&<Alert severity="info">当前周期没有已入库的 USD 交易。接入交易投影后将显示资金趋势；当前不推断真实资金流为零。</Alert>}
 {busy&&<LinearProgress aria-label="正在读取统计"/>}
 <Card><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr 1fr',md:'repeat(4,1fr)'}}}>{[
 {label:'流入',value:hasData?money(total?.incomingMinor):'—',unit:'USD',sub:source==='local'?'来源 posted 金额合计':'投影已完成金额',icon:'solar:arrow-down-linear'},
 {label:'流出',value:hasData?money(total?.outgoingMinor):'—',unit:'USD',sub:source==='local'?'来源 posted 金额合计':'投影已完成金额',icon:'solar:arrow-up-linear'},
 {label:'净流量',value:hasData?money(total?.netMinor):'—',unit:'USD',sub:'流入 − 流出',icon:'solar:transfer-horizontal-linear'},
 {label:'交易记录',value:total?total.transactions.toLocaleString():'—',unit:'笔',sub:'全部交易状态',icon:'solar:document-text-linear'}].map((m,i)=><Stack key={m.label} spacing={1} sx={{p:3,borderRight:{md:i<3?'1px dashed':'none'},borderColor:'divider'}}><Stack direction="row" gap={1} color="text.secondary" alignItems="center"><Icon icon={m.icon} width={18}/><Typography variant="body2">{m.label}</Typography><Typography variant="caption">{m.unit}</Typography></Stack><Typography variant="h4" sx={{fontVariantNumeric:'tabular-nums',fontSize:{xs:23,lg:30},overflowWrap:'anywhere'}}>{m.value}</Typography><Typography variant="caption" color="text.secondary">{m.sub}</Typography></Stack>)}</Box></Card>
 <Grid container spacing={3} sx={{width:'calc(100% + 24px) !important',ml:'-24px !important'}}>
 <Grid item xs={12} md={8}><Card sx={{height:'100%'}}><CardHeader title="每日资金流" subheader={source==='local'?'按来源 date · posted 状态汇总':'按交易发生时间 occurred_at · 已完成状态'} action={<Button size="small" onClick={()=>setDetail(v=>!v)} disabled={!data}>{detail?'收起明细':'每日明细'}</Button>}/><Box sx={{px:2,pt:1}}>{data&&hasData?<FundChart rows={data.daily} onSelect={day=>{setSelected(day);setDetail(true);}}/>:<Empty text={error?'统计暂不可用':'等待交易数据'} caption="有记录的日期将显示资金流；空白日期不视为零。"/>}</Box><Divider sx={{borderStyle:'dashed'}}/><Typography variant="caption" color="text.secondary" component="p" sx={{px:3,py:1.5}}>USD · {source==='local'?'来源 posted':'投影 succeeded'} · 空白日期无已导入记录，点击柱形可查看当日明细</Typography></Card></Grid>
 <Grid item xs={12} md={4}><Card sx={{height:'100%'}}><CardHeader title="需要关注" subheader="交易进度与来源质量"/><List sx={{px:3}}>{[
 {label:'待处理交易',sub:'尚未计入收支统计',value:total?.pending,color:'warning' as const,icon:'solar:clock-circle-linear'},
 {label:'失败交易',sub:'检查渠道拒绝与失败原因',value:total?.failed,color:'error' as const,icon:'solar:danger-circle-linear'},
 {label:'状态待核实',sub:source==='local'?'来源状态组合存在疑问':'当前投影不提供两层渠道状态',value:source==='local'?total?.review:undefined,color:'default' as const,icon:'solar:shield-warning-linear'}].map(m=><ListItem key={m.label} disableGutters sx={{gap:1.5,py:1.5}}><Box color={m.color==='default'?'text.secondary':m.color+'.main'}><Icon icon={m.icon} width={24}/></Box><ListItemText primary={m.label} secondary={m.sub} primaryTypographyProps={{variant:'subtitle2'}} secondaryTypographyProps={{variant:'caption'}}/><Chip size="small" variant="outlined" color={m.color} label={m.value??'—'}/></ListItem>)}</List><Divider sx={{borderStyle:'dashed'}}/><CardContent sx={{pt:2}}><Typography variant="caption" color="text.secondary">当前是已捕获数据，不能据此确认全量结算或账户可用资金。</Typography>{source==='local'&&<Button sx={{mt:1}} component={Link} to="/transactions?source=slash" endIcon={<Icon icon="solar:arrow-right-linear"/>}>进入交易列表</Button>}</CardContent></Card></Grid>
 </Grid>
 <Collapse in={detail} unmountOnExit><Card><CardHeader title={selected?selected+' 收支明细':'每日统计明细'} subheader="USD 精确汇总 · 未捕获日期显示 —" action={<Stack direction="row">{selected&&<Button onClick={()=>setSelected(null)}>全部日期</Button>}<Button onClick={exportRows} startIcon={<Icon icon="solar:download-linear"/>}>导出 CSV</Button></Stack>}/><TableContainer><Table size="small" aria-label="每日收支精确明细"><TableHead><TableRow>{['日期（香港时间）','流入 USD','流出 USD','净流量 USD','记录笔数'].map((c,i)=><TableCell key={c} align={i?'right':'left'}>{c}</TableCell>)}</TableRow></TableHead><TableBody>{rows?.map(r=><TableRow key={r.date} hover><TableCell>{r.date}</TableCell><TableCell align="right">{money(r.incomingMinor)}</TableCell><TableCell align="right">{money(r.outgoingMinor)}</TableCell><TableCell align="right">{money(r.netMinor)}</TableCell><TableCell align="right">{r.total}</TableCell></TableRow>)}</TableBody></Table></TableContainer></Card></Collapse>
 <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'1fr 1fr',xl:'1.15fr 1fr 1.15fr'},gap:3}}>
 <Card><CardHeader title="交易活跃度" subheader="按日查看各状态的交易笔数"/><Box sx={{px:2,pb:1}}>{data&&hasData?<VolumeChart data={data}/>:<Empty text="暂无可绘制的交易记录" height={270}/>}</Box></Card>
 <Card><CardHeader title="交易状态分布" subheader="各状态笔数占当前记录的比例"/><CardContent><Stack spacing={2.5}>{data?.statuses.map(s=><Box key={s.status}><Stack direction="row" justifyContent="space-between" mb={1}><Typography variant="body2">{labels[s.status]||s.status}</Typography><Typography variant="body2" sx={{fontVariantNumeric:'tabular-nums'}}>{s.count.toLocaleString()} <Typography component="span" variant="caption" color="text.secondary" ml={1}>{percent(s.count,total?.transactions||0)}</Typography></Typography></Stack><LinearProgress variant="determinate" value={total?.transactions?s.count/total.transactions*100:0} aria-label={(labels[s.status]||s.status)+'占比'} sx={{height:8,borderRadius:1,bgcolor:'grey.200','& .MuiLinearProgress-bar':{bgcolor:statusColor(s.status)}}}/></Box>)}</Stack><Typography variant="caption" color="text.secondary" component="p" mt={3}>待处理单列，不用当前状态分布推算授权成功率。</Typography></CardContent></Card>
 <Card sx={{gridColumn:{md:'1 / -1',xl:'auto'}}}><CardHeader title="消费商户排行" subheader="USD · 仅已入账且 settled 的卡消费"/><CardContent>{data?.availability.merchants&&data.merchants.length?<List disablePadding>{data.merchants.slice(0,5).map((m,i)=><ListItem key={m.name} disableGutters sx={{gap:1.5,py:1.2}}><Typography variant="caption" color="text.disabled">{String(i+1).padStart(2,'0')}</Typography><ListItemText primary={m.name} secondary={m.count+' 笔消费'} sx={{minWidth:0}} primaryTypographyProps={{variant:'subtitle2',noWrap:true,title:m.name}} secondaryTypographyProps={{variant:'caption'}}/><Typography variant="subtitle2" sx={{fontVariantNumeric:'tabular-nums'}}>{money(m.amountMinor)}</Typography></ListItem>)}</List>:<Empty height={225} text={data?.availability.merchants?'本周期暂无已入账消费':'商户明细尚未接入'} caption="有来源商户与消费类型后展示排行。"/>}</CardContent></Card>
 </Box>
 <Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" gap={1}><Box><Typography variant="body2" color="text.secondary">{data?.availability.cards?(String(total?.activeCards??'—')+' / '+String(total?.selectedCards??'—')+' 张选定卡为启用状态'):'卡片数据尚未接入当前统计源'}</Typography><Typography variant="caption" color="text.secondary">渠道最近成功读取：{time(data?.sync.lastSuccessAt)}{data?.sync.mode==='manual'?' · 手动同步':''}</Typography></Box><Button size="small" onClick={()=>setBasis(v=>!v)} endIcon={<Icon icon={basis?'solar:alt-arrow-up-linear':'solar:alt-arrow-down-linear'}/>}>统计口径与覆盖</Button></Stack>
 <Collapse in={basis}><Alert severity="info">{data?.coverage.reason||'正在读取统计范围。'} 收支是记录流量，不是账户余额；未抵消未经确认的内部转账，不代表营收、利润或可用资金。原币不折算混加，费用注释不重复计数。</Alert></Collapse>
 </Stack>;
}
