import {useEffect,useState} from 'react';
import {Alert,Autocomplete,Button,CircularProgress,Stack,TextField,Typography} from '@mui/material';
import {get,post} from '../../../../packages/shared/src/management/api';
type UserOption={id:string;name:string;email:string};
export type CardOwnership={platform:string;customerId:string|null;customerName:string|null;email:string|null;ownershipStatus:string;ownershipRevision:number;ownershipSource:string;ownershipUpdatedAt:string|null};
export function CardOwnerEditor({cardId,onSaved}:{cardId:string;onSaved:(owner:CardOwnership)=>void}){
 const [owner,setOwner]=useState<CardOwnership|null>(null),[users,setUsers]=useState<UserOption[]>([]),[selected,setSelected]=useState<UserOption|null>(null),[keyword,setKeyword]=useState(''),[reason,setReason]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[searching,setSearching]=useState(false),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false);
 useEffect(()=>{let active=true;setLoading(true);get<CardOwnership>(`card-ownership/cards/${encodeURIComponent(cardId)}`).then(value=>{if(active)setOwner(value);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[cardId]);
 useEffect(()=>{let active=true;const timer=setTimeout(()=>{setSearching(true);get<{rows:UserOption[]}>('users',{keyword,pageSize:25,page:0}).then(value=>{if(active)setUsers(value.rows);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setSearching(false);});},250);return()=>{active=false;clearTimeout(timer);};},[keyword]);
 const save=async()=>{if(!owner||!selected)return;setBusy(true);setError('');setSaved(false);try{const next=await post<CardOwnership>(`card-ownership/cards/${encodeURIComponent(cardId)}`,{userId:selected.id,revision:owner.ownershipRevision,reason});setOwner(next);setReason('');setSaved(true);onSaved(next);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <Stack gap={2} sx={{py:2}}><Typography variant="h6">所属用户</Typography><Typography variant="body2">{loading?'正在读取内部用户归属…':owner?.customerName||owner?.customerId||'未绑定'}{owner?.email?` · ${owner.email}`:''}</Typography><Typography variant="caption" color="text.secondary">归属来自内部用户数据库。绑定不修改 Slash 卡片、余额或资金权限。</Typography>{error&&<Alert severity="error">{error}</Alert>}{saved&&<Alert severity="success">内部用户绑定已保存</Alert>}<Autocomplete options={users} value={selected} loading={searching} disabled={loading||busy||!owner} filterOptions={options=>options} isOptionEqualToValue={(a,b)=>a.id===b.id} getOptionLabel={u=>`${u.name} · ${u.email}`} onInputChange={(_,value,why)=>{if(why==='input'||why==='clear')setKeyword(value);}} onChange={(_,value)=>{setSelected(value);setSaved(false);}} noOptionsText="无匹配用户，请输入姓名或邮件地址搜索" renderInput={params=><TextField {...params} size="small" label="选择内部用户"/>}/><TextField size="small" label="绑定或变更原因" value={reason} onChange={e=>setReason(e.target.value)} disabled={busy} inputProps={{maxLength:500}}/><Button sx={{alignSelf:'flex-start'}} variant="contained" disabled={loading||busy||!owner||!selected||selected.id===owner.customerId||!reason.trim()} onClick={()=>void save()} startIcon={busy?<CircularProgress size={16}/>:undefined}>{busy?'保存中…':'保存用户绑定'}</Button></Stack>;
}
