import {useState} from 'react';
import {Alert,Button,Dialog,DialogTitle,DialogContent,DialogActions,Stack,TextField,Typography} from '@mui/material';
import {apiPost,unwrapData} from '../../../../packages/shared/src/api/client';
import type {Card,State} from './model';
export function UnfreezeRequestDialog({card,state,onClose}:{card:Card;state:State;onClose:()=>void}){
 const [reason,setReason]=useState(card.unfreezeRequest?.approval_status==='returned'?card.unfreezeRequest.reason:''),[evidence,setEvidence]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false),[requestId]=useState(()=>`DEMO-${crypto.randomUUID()}`);
 const pending=card.unfreezeRequest&&(card.unfreezeRequest.approval_status==='pending'||card.unfreezeRequest.execution_status==='processing')&&card.unfreezeRequest.freeze_revision===card.management?.revision;
 return <Dialog open fullWidth maxWidth="sm" onClose={busy?undefined:onClose}><DialogTitle>申请解除风控</DialogTitle><DialogContent><Stack gap={2} sx={{pt:1}}><Typography>{card.name} · •••• {card.last4}</Typography><Alert severity="info">申请仅提交后台审核。审批通过且执行确认后，才会解除对应风控限制。</Alert>{pending&&<Alert severity="warning">本次冻结已有待处理申请，请等待审核。</Alert>}{error&&<Alert severity="error">{error}</Alert>}{done?<Alert severity="success">申请已提交，可在卡片详情查看审核进度。</Alert>:<><TextField label="申请原因" multiline minRows={3} value={reason} onChange={e=>setReason(e.target.value)} disabled={busy||!!pending} inputProps={{maxLength:500}}/><TextField label="补充材料编号（选填）" value={evidence} onChange={e=>setEvidence(e.target.value)} disabled={busy||!!pending} inputProps={{maxLength:500}}/><Typography variant="caption" color="text.secondary">此处填写已有业务材料编号；尚未接入附件上传。</Typography></>}</Stack></DialogContent><DialogActions><Button disabled={busy} onClick={onClose}>{done?'关闭':'取消'}</Button>{!done&&<Button variant="contained" disabled={busy||!!pending||!reason.trim()||!card.management} onClick={async()=>{setBusy(true);setError('');try{unwrapData(await apiPost('/local-slash-demo/portal/action',{requestId,revision:state.revision,action:{type:'unfreeze-request',id:card.id,freezeRevision:card.management?.revision,reason,evidence}}));setDone(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{busy?'提交中…':'提交申请'}</Button>}</DialogActions></Dialog>;
}
