import {forwardRef,useEffect,useState} from 'react';
import {Icon} from '@iconify/react';
import {Alert,Box,Breadcrumbs,Button,Card,CardContent,Chip,CircularProgress,Divider,Grid,Link,MenuItem,Stack,Tab,Tabs,Table,TableBody,TableCell,TableHead,TableRow,TextField,Typography} from '@mui/material';
import {zhCN} from '@mui/x-data-grid/locales';
import {DataGrid,GridToolbarColumnsButton,GridToolbarContainer,type GridColDef,type GridSortModel} from '@mui/x-data-grid';
import {Link as ReactRouterLink,useLocation,useNavigate,useSearchParams,type LinkProps} from 'react-router-dom';
import AccountDetail,{accountTime,AccountStatus} from './AccountDetail';
import {MetricCard} from '../components/MetricCard';
import {ChartCard} from '../components/ChartCard';
import {readDemo,money,statusLabels,detailLabels,matchingLabels} from './api';
import {portalHref,sourceViewPath,sourceApiBase,clientDetailHref,safeClientReturn} from './portalRouting';
const RouterLink=forwardRef<HTMLAnchorElement,LinkProps>((props,ref)=>{
 const portal=useLocation().pathname.startsWith('/portal');
 const to=portal&&typeof props.to==='string'?portalHref(props.to):props.to;
 return <ReactRouterLink {...props} to={to} ref={ref}/>;
});
import type {SourceRecord,SourceDetail,Scenario,Page,DemoSummary} from './types';
function useRemote<T>(path:string,query:Record<string,unknown>={}){
 const portal=useLocation().pathname.startsWith('/portal');
 const key=JSON.stringify(query);const [data,setData]=useState<T>();const [error,setError]=useState('');const [loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;setLoading(true);setError('');readDemo<T>(path,JSON.parse(key),portal).then(v=>{if(active)setData(v);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[path,key,portal]);
 return {data,error,loading};
}
function Notice({error,loading}:{error:string;loading:boolean}){return error?<Alert severity="error">{error}</Alert>:loading?<Stack direction="row" gap={1} alignItems="center"><CircularProgress size={18}/><Typography>正在查询本地 Demo 数据…</Typography></Stack>:null;}
function Field({label,value}:{label:string;value:React.ReactNode}){return <Box sx={{minWidth:0}}><Typography variant="caption" color="text.secondary">{label}</Typography><Typography component="div" variant="body2" sx={{mt:0.5,overflowWrap:'anywhere'}}>{value==null||value===''?'—':value}</Typography></Box>;}
function Section({title,children}:{title:string;children:React.ReactNode}){return <Card variant="outlined"><CardContent><Typography variant="h6" sx={{mb:2}}>{title}</Typography>{children}</CardContent></Card>;}
function Fields({children}:{children:React.ReactNode}){return <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'repeat(2,minmax(0,1fr))'},gap:2.5}}>{children}</Box>;}
function RecordLink({kind,id,label,href}:{kind:string;id?:string;label?:string;href?:string}){const portal=useLocation().pathname.startsWith('/portal');if(!id)return <>—</>;if(portal&&kind==='account')return <>{label||id}</>;return <Link component={RouterLink} title={id} to={href||`/${kind==='account'?'customers':kind==='card'?'cards':'transactions'}/${encodeURIComponent(id)}`} >{label||id}</Link>;}
function Status({raw,detailed=false}:{raw?:string;detailed?:boolean}){const label=raw?(detailed?detailLabels:statusLabels)[raw]:null;return <Chip size="small" variant="outlined" color={!label?'warning':raw==='failed'||raw==='declined'?'error':'default'} label={raw?`${label||'未知状态'} · ${raw}`:'—'}/>;}
function Toolbar(){return <GridToolbarContainer><GridToolbarColumnsButton/><Typography variant="caption" color="text.secondary" sx={{ml:1}}>点击行查看详情 · 后端筛选与分页</Typography></GridToolbarContainer>;}
const blankPage={rows:[],total:0,page:0,pageSize:25};
function RecordList({kind='transactions',risk=false,cardId,accountId}:{kind?:string;risk?:boolean;cardId?:string;accountId?:string}){
 const location=useLocation();const navigate=useNavigate();const portal=location.pathname.startsWith('/portal');
 const demoBase=sourceApiBase(portal);
 const href=(id:string)=>portal?clientDetailHref(kind,id,location.pathname+location.search,cardId):`/${kind==='accounts'?'customers':kind}/${encodeURIComponent(id)}${kind==='accounts'?'?returnTo='+encodeURIComponent(location.pathname+location.search):''}`;
 const [params,setParams]=useSearchParams();const [keyword,setKeyword]=useState(params.get('keyword')||'');
 const query=Object.fromEntries(params);const scope={...(cardId?{cardId}:{}),...(accountId?{accountId}:{})};const pagination={page:Number(query.page||0),pageSize:Number(query.pageSize||25)};
 const {data,error,loading}=useRemote<Page<SourceRecord>>(kind,{...query,...pagination,...(risk?{risk:'1'}:{}),...scope});
 const update=(change:Record<string,string>)=>setParams({...query,page:'0',...change});
 const tx=kind==='transactions';
 const action:GridColDef<SourceRecord>={field:'detail',headerName:'操作',width:112,align:'right',headerAlign:'right',sortable:false,hideable:false,disableColumnMenu:true,renderCell:p=><Button component={RouterLink} to={href(p.row.id)} aria-label={`查看${kind==='cards'?'卡片':kind==='accounts'?'账户':'交易'}详情 ${p.row.id}`} size="small" endIcon={<Icon icon="solar:alt-arrow-right-linear"/>}>查看详情</Button>};
 const common:GridColDef<SourceRecord>[]=[{field:'id',headerName:tx?'平台交易 ID':kind==='cards'?'卡片 ID':'账户 ID',width:255,renderCell:p=><RecordLink kind={tx?'transaction':kind==='cards'?'card':'account'} id={p.row.id} href={href(p.row.id)}/>},
 {field:'scenario',headerName:'场景',width:125,valueGetter:(_,r)=>r.internal.scenarioId,sortable:false},
 {field:'status',headerName:kind==='cards'?'状态':'来源状态',width:145,renderCell:p=><Status raw={p.row.source.status}/>},
 ];
 const baseColumns:GridColDef<SourceRecord>[]=tx?[...common,
 {field:'detailedStatus',headerName:'详细状态',width:155,renderCell:p=><Status raw={p.row.source.detailedStatus} detailed/>},
 {field:'amount',headerName:'账户币金额',width:175,type:'number',valueGetter:(_,r)=>r.source.amountCents,renderCell:p=>money(p.row.source.amountCents,p.row.currency)},
 {field:'merchant',headerName:'商户',width:220,sortable:false,valueGetter:(_,r)=>r.source.merchantData?.description??'—'},
 {field:'date',headerName:'来源日期（UTC）',width:225,valueGetter:(_,r)=>r.source.date},
 {field:'dateMeaning',headerName:'日期含义',width:115,sortable:false,valueGetter:(_,r)=>r.dateMeaning},
 {field:'authorizedAt',headerName:'授权时间（UTC）',width:230,valueGetter:(_,r)=>r.source.authorizedAt??'—'},
 {field:'accountId',headerName:'平台账户',width:330,sortable:false,valueGetter:(_,r)=>r.source.accountId},
 {field:'virtualAccountId',headerName:'虚拟账户',width:300,sortable:false,valueGetter:(_,r)=>r.source.virtualAccountId??'—'},
 {field:'cardId',headerName:'卡片',width:300,sortable:false,valueGetter:(_,r)=>r.source.cardId??'—'},
 {field:'originalCurrency',headerName:'原币',width:95,valueGetter:(_,r)=>r.source.originalCurrency?.code??'—'},
 {field:'originalAmount',headerName:'原币金额',width:165,sortable:false,valueGetter:(_,r)=>money(r.source.originalCurrency?.amountCents,r.source.originalCurrency?.code)},
 {field:'conversionRate',headerName:'转换汇率',width:120,sortable:false,valueGetter:(_,r)=>r.source.originalCurrency?.conversionRate??'—'},
 ...(['orderId','referenceNumber','providerAuthorizationId'] as const).map(field=>({field,headerName:field,width:290,sortable:false,valueGetter:(_:unknown,r:SourceRecord)=>r.source[field]??'—'})),
 {field:'mcc',headerName:'MCC',width:90,sortable:false,valueGetter:(_,r)=>r.source.merchantData?.categoryCode??'—'},
 {field:'platform',headerName:'平台',width:110,sortable:false,valueGetter:(_,r)=>r.internal.platform},
 {field:'matching',headerName:'对账关联',width:190,sortable:false,valueGetter:(_,r)=>matchingLabels[r.internal.matchingStatus||'']||'待确认'},
 ]:[...common,{field:'name',headerName:'卡片名称',width:230,sortable:false,valueGetter:(_,r)=>r.source.name},
 ...(kind==='cards'?[{field:'last4',headerName:'卡号后四位',width:115,sortable:false,valueGetter:(_:unknown,r:SourceRecord)=>r.source.last4},{field:'expiry',headerName:'有效期',width:110,sortable:false,valueGetter:(_:unknown,r:SourceRecord)=>`${r.source.expiryMonth??'—'}/${r.source.expiryYear??'—'}`}]:[{field:'type',headerName:'账户类型',width:130,sortable:false,valueGetter:(_:unknown,r:SourceRecord)=>r.source.type}]),
 {field:'customer',headerName:'所属用户',width:240,sortable:false,valueGetter:(_,r)=>r.internal.email}];
 const accountColumns:GridColDef<SourceRecord>[]=[
 {field:'name',headerName:'账户名称',minWidth:190,flex:1,sortable:false,valueGetter:(_,r)=>r.source.name??'—'},
 {field:'email',headerName:'邮件地址',minWidth:250,flex:1,sortable:false,valueGetter:(_,r)=>r.internal.email||'—'},
 {field:'status',headerName:'状态',width:120,renderCell:p=><AccountStatus value={p.row.source.status}/>},
 {field:'balance',headerName:'余额',description:'可用余额 available；按币种和余额类型分别展示，已入账余额见详情。',minWidth:200,flex:0.8,align:'right',headerAlign:'right',sortable:false,renderCell:p=><Stack gap={0.5} sx={{width:'100%',py:1,textAlign:'right',fontVariantNumeric:'tabular-nums'}}>{p.row.balances?.length?p.row.balances.map(b=><Typography key={b.id} variant="body2" title={`可用余额 · ${b.source.type||'类型未提供'} · ${accountTime(b.source.timestamp)} UTC`}>{b.internal.currency?money(b.source.available?.amountCents,b.internal.currency):'—'}{p.row.balances!.length>1?` · ${b.source.type||'类型未提供'}`:''}</Typography>):'—'}</Stack>},
 ];
 const cardOrder=['name','last4','status','expiry','customer','id','scenario'];
 const orderedColumns=kind==='cards'?[...baseColumns].sort((a,b)=>cardOrder.indexOf(a.field)-cardOrder.indexOf(b.field)):baseColumns;
 const columns=[...(kind==='accounts'?accountColumns:orderedColumns),action];
 const reset=()=>{setKeyword('');setParams({...((cardId||accountId)&&query.tab?{tab:query.tab}:{}),...(query.returnTo?{returnTo:query.returnTo}:{})});};
 const select=(label:string,key:string,values:Record<string,string>)=><TextField select size="small" label={label} value={query[key]||''} onChange={e=>update({[key]:e.target.value})} sx={{minWidth:155}}><MenuItem value="">全部</MenuItem>{Object.entries(values).map(([v,l])=><MenuItem key={v} value={v}>{l}</MenuItem>)}</TextField>;
 return <Stack gap={2.5}>
  {risk&&<Alert severity="warning">仅展示待确认或未匹配记录。Demo关联证据不代表生产对账成功；原始已入账金额仍参与资金统计。</Alert>}
  <Card variant="outlined"><CardContent><Stack component="form" onSubmit={e=>{e.preventDefault();update({keyword});}} gap={2}>
   <Stack direction={{xs:'column',sm:'row'}} gap={1.5}><TextField size="small" label={kind==='accounts'?'搜索账户名称、账户 ID 或用户邮箱':kind==='cards'?'搜索卡片名称、尾号或卡片 ID':'ID、场景、订单、商户或事件 ID'} value={keyword} onChange={e=>setKeyword(e.target.value)} fullWidth/>{kind==='accounts'&&select('状态','status',{open:'已开立',closed:'已关闭'})}<Button type="submit" variant="contained" sx={{minWidth:88,whiteSpace:'nowrap',flexShrink:0}} startIcon={<Icon icon="solar:magnifer-linear"/>}>查询</Button><Button sx={{minWidth:64,flexShrink:0}} onClick={reset}>重置</Button></Stack>
   {kind!=='accounts'&&<Stack direction="row" gap={1.5} flexWrap="wrap">
    {select('状态','status',tx?{pending:'处理中',posted:'已入账',failed:'未入账 / 失败'}:kind==='cards'?{active:'启用',paused:'暂停',inactive:'未激活',closed:'关闭'}:{open:'已开立',closed:'关闭'})}
    {tx&&<>{select('详细状态','detailedStatus',detailLabels)}{select('入账币种','currency',{USD:'USD'})}{select('原币','originalCurrency',{EUR:'EUR',USD:'USD（显式提供）'})}{select('平台','platform',{slash:'Slash'})}{select('时间口径','timeBasis',{date:'来源日期',authorizedAt:'授权时间'})}
    <TextField type="date" size="small" label="开始日期 UTC" InputLabelProps={{shrink:true}} value={query.from||''} onChange={e=>update({from:e.target.value})}/><TextField type="date" size="small" label="结束日期 UTC" InputLabelProps={{shrink:true}} value={query.to||''} onChange={e=>update({to:e.target.value})}/></>}
   </Stack>}
   {query.scenario&&<Chip sx={{alignSelf:'flex-start'}} label={`场景 ${query.scenario}`} onDelete={()=>update({scenario:''})}/>}
  </Stack></CardContent></Card>
  <Notice error={error} loading={loading}/>
  <Stack direction="row" justifyContent="space-between" alignItems="center"><Typography variant="caption" color="text.secondary">{tx?'负数为支出，正数为收入。处理中金额不计入已入账支出。':kind==='accounts'?'余额为可用余额；不同币种与余额类型分别展示，未采集显示 —。':'来源状态独立保留；未提供的信息显示 —。'}</Typography><Button component="a" href={`${demoBase}/${kind}.csv?${new URLSearchParams({...query,...(risk?{risk:'1'}:{}),...scope})}`} startIcon={<Icon icon="solar:download-linear"/>}>导出筛选结果 CSV</Button></Stack>
  <Card variant="outlined"><DataGrid localeText={zhCN.components.MuiDataGrid.defaultProps.localeText} autoHeight rows={(data||blankPage).rows} getRowHeight={kind==='accounts'?()=> 'auto':undefined} rowCount={data?.total||0} loading={loading} columns={columns} onRowClick={(p,e)=>{if(!(e.target as HTMLElement).closest('a,button,input,[role=checkbox]'))navigate(href(String(p.id)));}} disableRowSelectionOnClick disableColumnFilter paginationMode="server" sortingMode="server" paginationModel={pagination} onPaginationModelChange={m=>update({page:String(m.page),pageSize:String(m.pageSize)})} pageSizeOptions={[10,25,50,100]} sortModel={query.sort?[{field:query.sort,sort:query.order==='desc'?'desc':'asc'}]:[]} onSortModelChange={(m:GridSortModel)=>update({sort:m[0]?.field||'',order:m[0]?.sort||''})} slots={{toolbar:Toolbar}} initialState={{columns:{columnVisibilityModel:{scenario:false,merchant:false,dateMeaning:false,authorizedAt:false,accountId:false,virtualAccountId:false,cardId:false,originalCurrency:false,originalAmount:false,conversionRate:false,orderId:false,referenceNumber:false,providerAuthorizationId:false,mcc:false,platform:kind==='accounts',...(['accounts','cards'].includes(kind)?{id:false,lastSyncedAt:false}:{})}}}} sx={{border:0,'& .MuiDataGrid-cell':{display:'flex',alignItems:'center'},'& .MuiDataGrid-row':{cursor:'pointer'},'& .MuiDataGrid-cell:focus-within':{outlineOffset:-2}}}/></Card>
 </Stack>;
}
function ScenarioList(){
 const [params,setParams]=useSearchParams();const [keyword,setKeyword]=useState(params.get('keyword')||'');const page=Number(params.get('page')||0);const {data,error,loading}=useRemote<Page<Scenario>>('scenarios',{keyword:params.get('keyword')||'',page,pageSize:25});
 const columns:GridColDef<Scenario>[]=[{field:'id',headerName:'场景 ID',width:140,renderCell:p=><Link component={RouterLink} to={`/transactions?scenario=${p.row.id}`}>{p.row.id}</Link>},{field:'title',headerName:'测试场景',width:265},{field:'description',headerName:'预期页面结果',width:500},{field:'expected_net_cents',headerName:'预期净入账',width:170,valueFormatter:v=>money(v)},{field:'expected_hold_cents',headerName:'剩余冻结',width:150,valueFormatter:v=>money(v)},{field:'confirmation',headerName:'规则边界',width:170}];
 return <Stack gap={2}><Typography color="text.secondary">每个场景有独立账户、虚拟账户及卡片，期初均为 1000.00 USD。点击场景 ID 查询关联交易。</Typography><Stack direction="row" component="form" onSubmit={e=>{e.preventDefault();setParams({keyword,page:'0'});}} gap={1}><TextField size="small" label="搜索场景" value={keyword} onChange={e=>setKeyword(e.target.value)}/><Button type="submit" variant="contained">查询</Button></Stack><Notice error={error} loading={loading}/><Card variant="outlined"><DataGrid localeText={zhCN.components.MuiDataGrid.defaultProps.localeText} autoHeight rows={data?.rows||[]} columns={columns.map(c=>({...c,sortable:false}))} disableColumnFilter disableRowSelectionOnClick paginationMode="server" rowCount={data?.total||0} paginationModel={{page,pageSize:25}} onPaginationModelChange={m=>setParams({keyword:params.get('keyword')||'',page:String(m.page)})} pageSizeOptions={[25]} /></Card></Stack>;
}
export function DetailPage({kind,id}:{kind:string;id:string}){
 const location=useLocation();const [params,setParams]=useSearchParams();const portal=location.pathname.startsWith('/portal');
 const nestedCard=location.pathname.match(/^\/portal\/cards\/([^/]+)\/(?:transactions|records)\//)?.[1];
 const parentCard=nestedCard?decodeURIComponent(nestedCard):undefined;
 const fallback=parentCard?`/portal/cards/${encodeURIComponent(parentCard)}?tab=transactions`:`/portal/${kind==='accounts'?'customers':kind}`;
 const back=portal?safeClientReturn(params.get('returnTo'),fallback):`/${kind==='accounts'?'customers':kind}`;
 const cardTab=portal&&kind==='cards'&&params.get('tab')==='transactions';
 const {data:d,error,loading}=useRemote<SourceDetail>(`${kind}/${encodeURIComponent(id)}`);
 if(!d)return <Stack gap={2}><Button component={RouterLink} to={back}>返回列表</Button><Notice error={error} loading={loading}/></Stack>;
 if(parentCard&&d.source.cardId!==parentCard)return <Stack gap={2}><Alert severity="warning">该交易不属于当前卡片，请从卡片交易列表重新选择。</Alert><Button component={RouterLink} to={fallback}>返回卡片交易</Button></Stack>;
 if(kind==='accounts'&&!portal)return <AccountDetail data={d} renderRecords={resource=><RecordList key={`${id}-${resource}`} kind={resource} accountId={id}/>}/>;
 const s=d.source,i=d.internal,tx=kind==='transactions';
 const related=(d.relations||[]).map(r=>({...r,target:r.from_id===id?r.to_id:r.from_id}));
 return <Stack gap={2.5}>
  <Notice error={error} loading={loading}/>
  {portal&&<Breadcrumbs aria-label="详情页面层级"><Link component={RouterLink} to={parentCard?'/portal/cards':back}>{kind==='cards'||parentCard?'卡片中心':tx?'交易与账单':'账户余额'}</Link>{parentCard&&<Link component={RouterLink} to={back}>卡片详情 · 交易账单</Link>}<Typography color="text.primary">{kind==='cards'?'卡片详情':tx?'交易详情':'账户详情'}</Typography></Breadcrumbs>}
  <Stack direction="row" gap={1} flexWrap="wrap"><Button component={RouterLink} to={back} startIcon={<Icon icon="solar:arrow-left-linear"/>}>{parentCard?'返回卡片交易':'返回列表'}</Button>{!portal&&<Button component={RouterLink} to={`/transactions?scenario=${i.scenarioId}`}>查看场景 {i.scenarioId}</Button>}{!tx&&!(portal&&kind==='cards')&&<Button component={RouterLink} to={`/transactions?${kind==='cards'?'cardId':'accountId'}=${encodeURIComponent(id)}`}>查询关联交易</Button>}</Stack>
  {portal&&<Section title={kind==='cards'?(s.name||'卡片详情'):tx?'交易详情':'账户详情'}><Stack direction="row" gap={2} flexWrap="wrap" alignItems="center"><Typography variant="body2" sx={{overflowWrap:'anywhere'}}>{id}</Typography><Status raw={s.status}/>{tx&&<><Status raw={s.detailedStatus} detailed/><Typography variant="h5">{money(s.amountCents,d.currency)}</Typography></>}{kind==='cards'&&<Typography>尾号 {s.last4??'—'} · 有效期 {s.expiryMonth??'—'}/{s.expiryYear??'—'}</Typography>}</Stack></Section>}
  {portal&&kind==='cards'&&<Tabs value={cardTab?'transactions':'overview'} aria-label="卡片详情导航" onChange={(_,tab)=>setParams({...Object.fromEntries(params),tab,page:'0'})}><Tab value="overview" label="卡片资料"/><Tab value="transactions" label="交易与账单"/></Tabs>}
  {cardTab?<Section title="本卡交易与账单"><Typography color="text.secondary" sx={{mb:2}}>点击“查看详情”打开本卡交易的三级详情页。</Typography><RecordList key={id} kind="transactions" cardId={id}/></Section>:<>

  <Alert severity={i.matchingStatus==='demo_verified'?'info':'warning'}>{matchingLabels[i.matchingStatus||'']||'待确认'} · {i.assumption}</Alert>
  {tx?<>
   <Section title="1 · 金额与状态"><Fields><Field label="账户币金额（signed amountCents）" value={money(s.amountCents,d.currency)}/><Field label="方向（按符号派生）" value={d.direction==='debit'?'支出 / debit':d.direction==='credit'?'收入 / credit':d.direction==='zero'?'真实零值 / zero':'—'}/><Field label="status" value={<Status raw={s.status}/>}/><Field label="detailedStatus" value={<Status raw={s.detailedStatus} detailed/>}/><Field label="账户子类型" value={s.accountSubtype}/><Field label="原币金额（未提供时原币为USD）" value={s.originalCurrency?money(s.originalCurrency.amountCents,s.originalCurrency.code):'未提供 originalCurrency；来源文档默认 USD'}/><Field label="原币转账户币种汇率" value={s.originalCurrency?.conversionRate}/><Field label="授权金额" value="见下方来源版本；不从最终入账金额反推"/><Field label="拒绝原因" value={s.declineReason}/><Field label="批准原因" value={s.approvalReason}/></Fields></Section>
   <Section title="2 · 授权与来源日期"><Fields><Field label="authorizedAt · 授权时间 UTC" value={s.authorizedAt}/><Field label={`date · ${d.dateMeaning} UTC`} value={s.date}/><Field label="已入账时间（仅posted派生）" value={d.postedAt}/><Field label="来源对象更新时间" value="—（官方未提供通用updatedAt）"/></Fields></Section>
   <Section title="3 · 商户信息"><Fields><Field label="商户描述" value={s.merchantData?.description}/><Field label="MCC" value={s.merchantData?.categoryCode}/><Field label="城市 / 州 / 国家 / 邮编" value={s.merchantData?.location?Object.values(s.merchantData.location).join(' / '):null}/><Field label="来源交易描述" value={s.description}/><Field label="memo" value={s.memo}/></Fields></Section>
   <Section title="4 · 平台与订单关联"><Fields><Field label="平台交易 ID" value={id}/><Field label="平台账户 ID" value={<RecordLink kind="account" id={s.accountId}/>}/><Field label="虚拟账户 ID" value={s.virtualAccountId}/><Field label="卡片 ID" value={<RecordLink kind="card" id={s.cardId}/>}/><Field label="orderId（非唯一）" value={s.orderId}/><Field label="referenceNumber" value={s.referenceNumber}/><Field label="providerAuthorizationId" value={s.providerAuthorizationId}/></Fields></Section>
   <Section title="5 · 费用、退款、撤销及争议关联"><Stack gap={2}><Fields><Field label="外汇费信息（不重复扣款）" value={money(s.fxFeeInfo?.amountCents)}/><Field label="返现信息（不自动入账）" value={money(s.cashbackInfo?.amountCents)}/><Field label="返现比例" value={s.cashbackInfo?.rate}/><Field label="feeInfo.relatedTransaction（amount单位未明确）" value={s.feeInfo?.relatedTransaction?`${s.feeInfo.relatedTransaction.id} / 原值 ${s.feeInfo.relatedTransaction.amount}`:null}/></Fields>
    {related.length?related.map(r=><Box key={r.id}><Stack direction="row" gap={1} flexWrap="wrap"><Chip size="small" label={r.relation_type}/><RecordLink kind="transaction" id={r.target}/><Chip size="small" color="warning" label={r.confirmation}/></Stack><Typography variant="caption" color="text.secondary">{r.evidence}</Typography></Box>):<Typography color="text.secondary">没有可靠关联证据；未自动匹配。</Typography>}
    {d.fees.map(f=><Alert severity="info" key={f.id}>费用明细：{f.source.feeType} · {money(f.source.feeAmountCents)} · {f.source.dateCharged}。费用交易已单独入账，本明细不重复累计。</Alert>)}
    {d.adjustments.map(a=><Box key={a.id}><Typography>{a.reason} · {money(a.amount_cents)}</Typography><Typography variant="caption">{a.occurred_at} · {a.confirmation} · 内部记录 {a.id}</Typography></Box>)}
   </Stack></Section>
  </>:<Section title={kind==='cards'?'卡片来源信息':'账户来源信息'}><Fields><Field label="来源 ID" value={id}/><Field label="名称" value={s.name}/><Field label="状态" value={<Status raw={s.status}/>}/><Field label="类型" value={kind==='cards'?(s.isPhysical==null?'—':s.isPhysical?'实体卡':'虚拟卡'):s.type}/>{kind==='cards'&&<><Field label="后四位" value={s.last4}/><Field label="有效期 MM/YYYY" value={s.expiryMonth&&s.expiryYear?`${s.expiryMonth}/${s.expiryYear}`:null}/><Field label="所属账户" value={<RecordLink kind="account" id={s.accountId}/>}/><Field label="虚拟账户" value={s.virtualAccountId}/><Field label="卡组" value={`${s.cardGroupName??'—'} / ${s.cardGroupId??'—'}`}/><Field label="卡产品 ID" value={s.cardProductId}/><Field label="卡片余额" value="—（Slash Card未提供；限额不是余额）"/><Field label="消费限额" value={s.spendingConstraint?.spendingRule?.utilizationLimitV2?.map((l,n)=><Typography key={n}>{l.preset} · {money(l.limitAmount?.amountCents)} · {l.timezone??'—'}</Typography>)}/></>}</Fields></Section>}
  <Section title="所属账户余额 · 与卡片限额分开"><Stack gap={2}>{d.balances.map(b=><Fields key={b.id}><Field label={`可用 available · ${b.source.type} · ${b.source.accountId}`} value={money(b.source.available?.amountCents,b.internal.currency)}/><Field label={`已入账 posted · ${b.source.type}`} value={money(b.source.posted?.amountCents,b.internal.currency)}/><Field label="余额时间戳 UTC" value={b.source.timestamp}/><Field label="余额来源" value="按Demo模型计算的合成来源余额，非实时Slash余额"/></Fields>)}{!d.balances.length&&<Typography>—（未采集余额）</Typography>}</Stack></Section>
  {!tx&&d.virtualAccounts.length>0&&<Section title="虚拟账户归属"><Stack gap={2}>{d.virtualAccounts.map(v=><Fields key={v.id}><Field label="虚拟账户 ID" value={v.id}/><Field label="名称" value={v.source.name}/><Field label="accountType（default为主账户下的虚拟账户）" value={v.source.accountType}/><Field label="所属来源账户" value={v.source.accountId}/></Fields>)}</Stack></Section>}
  <Section title="6 · 数据来源、同步与对账"><Fields><Field label="平台 / 实体" value={`${i.platform} / ${i.entityId}`}/><Field label="内部客户映射" value={`${i.customerId??'—'} / ${i.email??'—'}`}/><Field label="首次采集时间" value={i.firstCollectedAt}/><Field label="最近同步时间" value={i.lastSyncedAt}/><Field label="同步错误" value={i.syncError??'—（未记录错误）'}/><Field label="内部版本（非Slash字段）" value={i.version}/><Field label="对账关联" value={matchingLabels[i.matchingStatus||'']||'待确认'}/><Field label="命名空间" value={i.namespace}/></Fields></Section>
  {tx&&<Section title="来源版本历史 · 授权金额与最终金额分别保留"><Box sx={{overflowX:'auto'}}><Table size="small"><TableHead><TableRow>{['内部版本','来源日期 / 含义','金额','status / detailedStatus','采集时间'].map(h=><TableCell key={h}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{d.versions.map(v=><TableRow key={v.version}><TableCell>{v.version}</TableCell><TableCell>{v.source.date}<br/>{v.source.status==='posted'?'入账时间':'创建时间'}</TableCell><TableCell>{money(v.source.amountCents)}</TableCell><TableCell>{v.source.status} / {v.source.detailedStatus}</TableCell><TableCell>{v.collectedAt}</TableCell></TableRow>)}</TableBody></Table></Box></Section>}
  {d.snapshots.length>0&&<><ChartCard title="账户可用与已入账余额变化" subheader="USD · 内部事件快照；折线仅用于展示，账务按整数分计算" height={220} series={[{name:'可用',data:d.snapshots.map(b=>b.available_cents/100)},{name:'已入账',data:d.snapshots.map(b=>b.posted_cents/100)}]} categories={d.snapshots.map(b=>b.timestamp)}/><Section title="余额快照明细"><Box sx={{overflowX:'auto'}}><Table size="small"><TableHead><TableRow>{['时间 UTC','变化步骤','available','posted'].map(h=><TableCell key={h}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{d.snapshots.map(b=><TableRow key={b.id}><TableCell>{b.timestamp}</TableCell><TableCell>{b.step}</TableCell><TableCell>{money(b.available_cents)}</TableCell><TableCell>{money(b.posted_cents)}</TableCell></TableRow>)}</TableBody></Table></Box></Section></>}
  {tx&&<Section title="来源事件与投递记录"><Stack gap={2}>{d.events.map(e=><Box key={e.eventId}><Typography variant="body2" sx={{overflowWrap:'anywhere'}}>{e.eventId} · {e.event}</Typography><Typography variant="caption">来源事件时间 {e.eventTimestamp} · 本系统采集 {e.collectedAt}</Typography></Box>)}<Divider/>{d.deliveries.map(v=><Typography key={v.id} variant="body2">{v.result} · {v.received_at} · {v.event_id??'内部补同步，无来源eventId'}</Typography>)}<Alert severity="info">Webhook只有事件元数据；对象内容来自模拟GET。没有执行真实Webhook签名校验或调用Slash。</Alert></Stack></Section>}
 </>}
 </Stack>;
}
function Overview({report=false}:{report?:boolean}){
 const demoBase=sourceApiBase(useLocation().pathname.startsWith('/portal'));
 const {data,error,loading}=useRemote<DemoSummary>('summary');if(!data)return <Notice error={error} loading={loading}/>;
 return <Stack gap={3}><Notice error={error} loading={loading}/><Typography color="text.secondary">{data.timeBasis} · 数据时点 {data.asOf}</Typography>
 {data.totals.map(t=><Box key={`${t.currency}-${t.account_subtype}`}><Typography variant="subtitle1" sx={{mb:2}}>{t.currency} · 交易账户子类型 {t.account_subtype}</Typography><Grid container spacing={2}><Grid item xs={12} sm={6} lg={6} xl={3}><MetricCard label="已入账支出" value={money(t.postedDebitCents,t.currency)} helper="包含独立费用交易，不含pending" icon="solar:card-send-bold-duotone"/></Grid><Grid item xs={12} sm={6} lg={6} xl={3}><MetricCard label="已入账收入" value={money(t.postedCreditCents,t.currency)} helper="独立退款按各自记录累计" icon="solar:card-recive-bold-duotone"/></Grid><Grid item xs={12} sm={6} lg={6} xl={3}><MetricCard label="来源交易净额" value={money(t.postedNetCents,t.currency)} helper="内部调整在下方单列" icon="solar:transfer-horizontal-bold-duotone"/></Grid><Grid item xs={12} sm={6} lg={6} xl={3}><MetricCard label="未释放授权冻结" value={money(t.holdCents,t.currency)} helper="pending_approval不占用余额" icon="solar:lock-keyhole-bold-duotone" tone="warning"/></Grid></Grid></Box>)}
 <Grid container spacing={2.5}><Grid item xs={12} md={7}><ChartCard title="每月来源交易净额" subheader="按posted交易date统计 · USD/cash · 净额为负表示支出" type="line" height={240} series={[{name:'净入账 USD',data:data.monthly.map(m=>m.netCents/100)}]} categories={data.monthly.map(m=>m.month)}/></Grid><Grid item xs={12} md={5}><Section title="本批数据与验证入口"><Stack gap={2}><Typography>{data.counts.scenarios} 个独立场景 · {data.counts.source_events} 个来源事件</Typography><Typography>{data.counts.source_versions} 个来源版本 · {data.counts.balance_snapshots} 个余额快照</Typography><Button variant="contained" component={RouterLink} to="/demo/scenarios" startIcon={<Icon icon="solar:checklist-minimalistic-bold-duotone"/>}>打开场景清单</Button><Button variant="outlined" component={RouterLink} to="/risk">查看待确认 / 未匹配记录</Button><Typography variant="caption" color="text.secondary">无真实渠道调用。Demo规则通过不等于Slash业务规则已确认。</Typography></Stack></Section></Grid></Grid>
 <Section title="月度净额与内部调整"><Box sx={{overflowX:'auto'}}><Table><TableHead><TableRow><TableCell>入账月 UTC</TableCell><TableCell>币种 / 子类型</TableCell><TableCell>来源交易净额</TableCell><TableCell>内部Demo调整（待确认）</TableCell></TableRow></TableHead><TableBody>{data.monthly.map(m=><TableRow key={`${m.month}-${m.currency}-${m.account_subtype}`}><TableCell><Link component={RouterLink} to={`/transactions?status=posted&from=${m.month}-01&to=${m.month}-${new Date(Number(m.month.slice(0,4)),Number(m.month.slice(5)),0).getDate()}`}>{m.month}</Link></TableCell><TableCell>{m.currency} / {m.account_subtype}</TableCell><TableCell>{money(m.netCents,m.currency)}</TableCell><TableCell>{money(data.adjustments.find(a=>a.month===m.month)?.amountCents??0)}</TableCell></TableRow>)}</TableBody></Table></Box></Section>
 {report&&<Section title="账户余额快照 · 各账户独立展示"><Button component="a" href={`${demoBase}/balances.csv`}>导出账户余额 CSV</Button><Typography variant="caption">USD/debit；不跨账户类型或币种求和。此处最多显示前100个账户，全部账户通过目录分页查询。</Typography><Box sx={{overflowX:'auto'}}><Table size="small"><TableHead><TableRow><TableCell>所属账户</TableCell><TableCell>available</TableCell><TableCell>posted</TableCell><TableCell>余额时间</TableCell></TableRow></TableHead><TableBody>{data.balances.map(b=><TableRow key={b.id}><TableCell><RecordLink kind="account" id={b.source.accountId}/></TableCell><TableCell>{money(b.source.available?.amountCents,b.internal.currency)}</TableCell><TableCell>{money(b.source.posted?.amountCents,b.internal.currency)}</TableCell><TableCell>{b.source.timestamp}</TableCell></TableRow>)}</TableBody></Table></Box></Section>}
 </Stack>;
}
export default function SourceDemoPage(){
 const {pathname}=useLocation();const portal=pathname.startsWith('/portal');const parts=sourceViewPath(pathname).split('/').filter(Boolean);let title=portal?'工作台':'运营工作台',view:React.ReactNode=<Overview/>;
 if(parts[0]==='demo'){title='清算 Demo 场景';view=<ScenarioList/>;}
 if(['transactions','cards','customers'].includes(parts[0])){const kind=parts[0]==='customers'?'accounts':parts[0];title=kind==='transactions'?'卡交易流水':kind==='cards'?'卡片中心':'账户目录';view=parts[1]?<DetailPage key={pathname} kind={kind} id={decodeURIComponent(parts[1])}/>:<RecordList key={pathname} kind={kind}/>;if(parts[1])title=kind==='accounts'?'账户详情':title+' · 详情';}
 if(parts[0]==='risk'||parts[0]==='reconciliation'){title=parts[0]==='risk'?'风险与待确认事项':'对账关联调查';view=<RecordList risk/>;}
 if(parts[0]==='reports'){title=portal?'资金中心':'资金经营报表';view=<Overview report/>;}
 return <Stack gap={3}>{!portal&&parts[0]!=='customers'&&<Button component={RouterLink} to={parts[0]==='reports'?'/transactions/report':'/transactions?crossCurrency=cross'} sx={{alignSelf:'flex-start'}} startIcon={<Icon icon="solar:transfer-horizontal-linear"/>}>卡交易流水 · 跨币种筛选</Button>}<Box><Stack direction="row" alignItems="center" gap={1.5}><Typography variant="h4">{title}</Typography><Chip color="primary" variant="outlined" label="Demo / 模拟数据"/></Stack><Typography variant="body2" color="text.secondary" sx={{mt:1}}>{parts[0]==='customers'?'查询账户归属、余额及关联卡片与交易':'Slash 来源字段 · 独立本地命名空间 · 金额与关联证据可追溯'}</Typography></Box>{portal&&parts[0]==='reports'&&<Alert severity="info">本批 Slash 数据为 USD 账户与卡交易。USDT、充值、兑换与提现不在来源数据中，未提供的资产不显示为零；原资金流程可切换至独立流程演示。</Alert>}{view}</Stack>;
}
