-- Isolated Demo operations. Client groups are commercial groups, not administrator roles.
CREATE TABLE IF NOT EXISTS mg_groups(namespace TEXT NOT NULL REFERENCES demo_batches(namespace) ON DELETE CASCADE,id TEXT NOT NULL,name TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'active',description TEXT NOT NULL DEFAULT '',revision INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,PRIMARY KEY(namespace,id),UNIQUE(namespace,name));
CREATE TABLE IF NOT EXISTS mg_users(namespace TEXT NOT NULL,id TEXT NOT NULL,group_id TEXT NOT NULL,name TEXT NOT NULL,email TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',review_note TEXT,revision INTEGER NOT NULL DEFAULT 0,password_hash TEXT,credential_version INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,PRIMARY KEY(namespace,id),UNIQUE(namespace,email),FOREIGN KEY(namespace,group_id) REFERENCES mg_groups(namespace,id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS mg_users_group_status ON mg_users(namespace,group_id,status,created_at);
CREATE TABLE IF NOT EXISTS mg_fees(namespace TEXT NOT NULL REFERENCES demo_batches(namespace) ON DELETE CASCADE,scope TEXT NOT NULL,owner_id TEXT NOT NULL,kind TEXT NOT NULL,bps INTEGER NOT NULL CHECK(bps BETWEEN 0 AND 10000),fixed_minor INTEGER NOT NULL CHECK(fixed_minor>=0),PRIMARY KEY(namespace,scope,owner_id,kind));
CREATE TABLE IF NOT EXISTS mg_accounts(namespace TEXT NOT NULL,user_id TEXT NOT NULL,id TEXT NOT NULL,currency TEXT NOT NULL,available_minor INTEGER NOT NULL DEFAULT 0,posted_minor INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,PRIMARY KEY(namespace,id),UNIQUE(namespace,user_id,currency),FOREIGN KEY(namespace,user_id) REFERENCES mg_users(namespace,id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS mg_resets(namespace TEXT NOT NULL,user_id TEXT NOT NULL,id TEXT NOT NULL,token_hash TEXT NOT NULL UNIQUE,expires_at INTEGER NOT NULL,consumed_at INTEGER,created_at TEXT NOT NULL,PRIMARY KEY(namespace,id),FOREIGN KEY(namespace,user_id) REFERENCES mg_users(namespace,id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS mg_audit(namespace TEXT NOT NULL REFERENCES demo_batches(namespace) ON DELETE CASCADE,id TEXT NOT NULL,actor TEXT NOT NULL,action TEXT NOT NULL,target_id TEXT NOT NULL,description TEXT NOT NULL,created_at TEXT NOT NULL,PRIMARY KEY(namespace,id));
CREATE INDEX IF NOT EXISTS mg_audit_target ON mg_audit(namespace,target_id,created_at);
CREATE TABLE IF NOT EXISTS mg_sessions(namespace TEXT NOT NULL REFERENCES demo_batches(namespace) ON DELETE CASCADE,token_hash TEXT PRIMARY KEY,role TEXT NOT NULL,subject TEXT NOT NULL,expires_at INTEGER NOT NULL);
