-- Isolated card administration and ledger. No migration of legacy budgets into money.
CREATE TABLE IF NOT EXISTS ca_principals(namespace TEXT NOT NULL REFERENCES demo_batches(namespace) ON DELETE CASCADE,actor TEXT NOT NULL,permissions_json TEXT NOT NULL,owner_scope TEXT NOT NULL,PRIMARY KEY(namespace,actor));
CREATE TABLE IF NOT EXISTS ca_cards(namespace TEXT NOT NULL REFERENCES demo_batches(namespace) ON DELETE CASCADE,id TEXT NOT NULL,owner_id TEXT NOT NULL,name TEXT NOT NULL,last4 TEXT,provider_status TEXT NOT NULL,self_frozen INTEGER NOT NULL DEFAULT 0,risk_frozen INTEGER NOT NULL DEFAULT 0,reason TEXT,actor TEXT,operated_at TEXT,revision INTEGER NOT NULL DEFAULT 0,provider_mode TEXT NOT NULL DEFAULT 'unverified',PRIMARY KEY(namespace,id));
CREATE INDEX IF NOT EXISTS ca_cards_owner ON ca_cards(namespace,owner_id,id);
CREATE TABLE IF NOT EXISTS ca_accounts(namespace TEXT NOT NULL REFERENCES demo_batches(namespace) ON DELETE CASCADE,id TEXT NOT NULL,owner_id TEXT NOT NULL,card_id TEXT,currency TEXT NOT NULL,kind TEXT NOT NULL,PRIMARY KEY(namespace,id),UNIQUE(namespace,card_id),FOREIGN KEY(namespace,card_id) REFERENCES ca_cards(namespace,id));
CREATE TABLE IF NOT EXISTS ca_operations(namespace TEXT NOT NULL, id TEXT NOT NULL,card_id TEXT NOT NULL,kind TEXT NOT NULL,request_id TEXT NOT NULL,request_hash TEXT NOT NULL,requester TEXT NOT NULL,reason TEXT NOT NULL,evidence TEXT,amount_minor TEXT,currency TEXT,source_account TEXT,target_account TEXT,fee_minor TEXT NOT NULL DEFAULT '0',policy_version TEXT NOT NULL DEFAULT 'cardops-v1',approval_status TEXT NOT NULL,execution_status TEXT NOT NULL,reviewer TEXT,review_note TEXT,reviewed_at TEXT,executor TEXT,error TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,card_revision INTEGER NOT NULL,PRIMARY KEY(namespace,id),UNIQUE(namespace,requester,request_id),FOREIGN KEY(namespace,card_id) REFERENCES ca_cards(namespace,id),FOREIGN KEY(namespace,source_account) REFERENCES ca_accounts(namespace,id),FOREIGN KEY(namespace,target_account) REFERENCES ca_accounts(namespace,id));
CREATE INDEX IF NOT EXISTS ca_ops_card ON ca_operations(namespace,card_id,created_at,id);
CREATE INDEX IF NOT EXISTS ca_ops_status ON ca_operations(namespace,approval_status,execution_status,created_at);
CREATE TABLE IF NOT EXISTS ca_journals(namespace TEXT NOT NULL REFERENCES demo_batches(namespace) ON DELETE CASCADE,id TEXT NOT NULL,operation_id TEXT,kind TEXT NOT NULL,created_at TEXT NOT NULL,PRIMARY KEY(namespace,id),UNIQUE(namespace,operation_id),FOREIGN KEY(namespace,operation_id) REFERENCES ca_operations(namespace,id));
CREATE TABLE IF NOT EXISTS ca_entries(namespace TEXT NOT NULL,journal_id TEXT NOT NULL,account_id TEXT NOT NULL,amount_minor TEXT NOT NULL,PRIMARY KEY(namespace,journal_id,account_id),FOREIGN KEY(namespace,journal_id) REFERENCES ca_journals(namespace,id),FOREIGN KEY(namespace,account_id) REFERENCES ca_accounts(namespace,id));
CREATE INDEX IF NOT EXISTS ca_entries_account ON ca_entries(namespace,account_id,journal_id);
CREATE TABLE IF NOT EXISTS ca_holds(namespace TEXT NOT NULL,operation_id TEXT NOT NULL,account_id TEXT NOT NULL,amount_minor TEXT NOT NULL,PRIMARY KEY(namespace,operation_id),FOREIGN KEY(namespace,operation_id) REFERENCES ca_operations(namespace,id),FOREIGN KEY(namespace,account_id) REFERENCES ca_accounts(namespace,id));
CREATE TABLE IF NOT EXISTS ca_jobs(namespace TEXT NOT NULL,operation_id TEXT NOT NULL,status TEXT NOT NULL,provider_ref TEXT,result TEXT,attempts INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(namespace,operation_id),FOREIGN KEY(namespace,operation_id) REFERENCES ca_operations(namespace,id));
CREATE TABLE IF NOT EXISTS ca_audit(namespace TEXT NOT NULL REFERENCES demo_batches(namespace) ON DELETE CASCADE,id TEXT NOT NULL,card_id TEXT,operation_id TEXT,actor TEXT NOT NULL,action TEXT NOT NULL,note TEXT NOT NULL,created_at TEXT NOT NULL,PRIMARY KEY(namespace,id));
CREATE INDEX IF NOT EXISTS ca_audit_card ON ca_audit(namespace,card_id,created_at);
CREATE TRIGGER IF NOT EXISTS ca_entries_immutable_update BEFORE UPDATE ON ca_entries BEGIN SELECT RAISE(ABORT,'Ledger entries are immutable'); END;
CREATE TRIGGER IF NOT EXISTS ca_entries_immutable_delete BEFORE DELETE ON ca_entries BEGIN SELECT RAISE(ABORT,'Ledger entries are immutable'); END;
