import FundsFeeSettings from './FundsFeeSettings';
import {useEffect,useState} from 'react';
import {Alert,Box,Button,Chip,Divider,FormControlLabel,MenuItem,Paper,Stack,Switch,Table,TableBody,TableCell,TableHead,TableRow,TextField,Typography} from '@mui/material';
import {Link,useNavigate,useSearchParams} from 'react-router-dom';
import {cryptoRequest,cryptoError} from '../auth/cryptoApi';
import {cryptoMoney,cryptoUnits,type CryptoSnapshot,type CryptoOrder,type CryptoQuote,type CryptoSettings} from '../auth/cryptoContract';
import {useAuth} from '../auth/AuthContext';
import {SessionError} from '../auth/liveApi';
const names:Record<string,string>={deposit:'充值',withdrawal:'提现',otc:'OTC 兑换',reserving:'正在预占',pending_review:'待审核',processing:'处理中',releasing:'正在释放',completed:'已完成',failed:'已失败',rejected:'已拒绝',cancelled:'已取消',unknown:'结果待核查',pending:'待处理',reserved:'已预占',posted:'已入账',released:'已释放',not_posted:'未入账',not_required:'无需审批',not_applicable:'不适用',not_submitted:'未提交',not_verified:'未核验',approved:'已批准',simulated_success:'隔离模拟成功',simulated_verified:'隔离核验通过',simulated_unknown:'模拟结果未知',simulated_failed:'模拟失败',matched:'本地分录一致',mismatch:'待核对',insufficient_data:'数据不足',applied:'已记账',created:'订单创建',worker:'任务处理',approve:'批准提现',reject:'拒绝提现',cancel:'客户取消',synthetic_resolution:'隔离结果核查'};
const label=(v:string)=>names[v]||v;
type Posting={id:string;step:string;currency:string;amountMinor:string;state:string;reference:string;transactionId:string};
type Pending={path:string;body:Record<string,unknown>;key:string};
type Props={customerId:string;admin?:boolean;basePath:string;orderId?:string;kind?:string;permissions?:string[]};
export default function CryptoFunds({customerId,admin=false,basePath,orderId,kind='',permissions=[]}:Props){
 const {session}=useAuth(),navigate=useNavigate();const [params,setParams]=useSearchParams();const tab=params.get('tab')||'history',page=Number(params.get('page')||0),status=params.get('status')||'';
 const api=`/${admin?'admin':'client'}-api/v1/customers/${customerId}/crypto`,storageKey=`crypto-pending:${session?.id}:${customerId}:${admin}`;
 const [snapshot,setSnapshot]=useState<CryptoSnapshot|null>(null),[detail,setDetail]=useState<{order:CryptoOrder;events:{action:string;createdAt:string}[];postings?:Posting[]}|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reload,setReload]=useState(0),[pending,setPending]=useState<Pending|null>(null);
 const [currency,setCurrency]=useState<'USDT'|'USD'>('USDT'),[amount,setAmount]=useState(''),[address,setAddress]=useState(''),[quote,setQuote]=useState<CryptoQuote|null>(null),[note,setNote]=useState(''),[settings,setSettings]=useState<CryptoSettings|null>(null),[clock,setClock]=useState(Date.now()),[feeText,setFeeText]=useState<string|null>(null),[extraFeesValid,setExtraFeesValid]=useState(true),[feeReset,setFeeReset]=useState(0);
 useEffect(()=>{try{const raw=sessionStorage.getItem(storageKey);setPending(raw?JSON.parse(raw):null)}catch{setPending(null)}},[storageKey]);
 useEffect(()=>{let active=true;let running=false;const load=async()=>{if(running)return;running=true;try{const v=await cryptoRequest<CryptoSnapshot>(`${api}?page=${Number.isInteger(page)&&page>=0?page:0}&kind=${encodeURIComponent(kind)}&status=${encodeURIComponent(status)}`);if(!['shadow','live'].includes(v.mode)||v.mode==='shadow'&&v.executionEligible!==false||v.customerId!==customerId)throw new Error('资金响应不一致');if(active){setSnapshot(v);setSettings(old=>old||v.settings)}if(orderId){const d=await cryptoRequest<{order:CryptoOrder;events:{action:string;createdAt:string}[];postings?:Posting[]}>(`${api}/orders/${orderId}`);if(active)setDetail(d)}}catch(e){if(active)setError(cryptoError(e))}finally{running=false}};setError('');void load();const timer=setInterval(()=>{setClock(Date.now());if(!document.hidden)void load()},5000);return()=>{active=false;clearInterval(timer)}},[api,customerId,orderId,page,kind,status,reload]);
 const query=(changes:Record<string,string>)=>{const q=new URLSearchParams(params);for(const [k,v]of Object.entries(changes)){if(v)q.set(k,v);else q.delete(k)}setParams(q);setQuote(null)};
 const orderLink=(id:string)=>{const q=new URLSearchParams(params);if(admin)q.set('customer',customerId);return `${basePath}/orders/${id}?${q}`};
 const run=async(p:Pending)=>{setBusy(true);setError('');try{const v=await cryptoRequest<Record<string,unknown>>(p.path,p.body,p.key);sessionStorage.removeItem(storageKey);setPending(null);setReload(x=>x+1);if(p.path.endsWith('/quotes'))setQuote(v as unknown as CryptoQuote);else if(p.path.endsWith('/settings'))setSettings(v as unknown as CryptoSettings);else if(typeof v.id==='string'&&typeof v.state==='string')navigate(orderLink(v.id));return v}catch(e){setError(cryptoError(e));if(e instanceof SessionError&&e.status>=400&&e.status<500){sessionStorage.removeItem(storageKey);setPending(null)}return null}finally{setBusy(false)}};
 const submit=(suffix:string,body:Record<string,unknown>)=>{if(busy||pending)return;const p={path:api+'/'+suffix,body,key:crypto.randomUUID()};try{sessionStorage.setItem(storageKey,JSON.stringify(p));setPending(p);void run(p)}catch{setError('无法保存请求状态，请检查浏览器存储后再试。')}};
 const preview=()=>{try{submit(tab==='exchange'?'otc/quotes':'withdrawals/quotes',{currency:tab==='exchange'?currency:'USDT',amountMinor:cryptoUnits(amount,tab==='exchange'?currency:'USDT')})}catch(e){setError(cryptoError(e))}};
 const disabled=busy||!!pending;
 const o=detail?.order;
 return <Stack spacing={2} className={admin?'finance-crypto':undefined}>
  {snapshot&&(!admin||snapshot.mode!=='live'||orderId)&&<Alert severity="info" sx={admin&&snapshot?.mode==='live'?{py:0}:undefined}>{snapshot?.mode==='live'?'资金审核 · 请核对币种、网络、地址及金额。':'Cregis 隔离资金中心 · 使用独立影子账本，地址与出金为模拟。余额不能用于真实付款。'}</Alert>}
  <Stack direction="row" spacing={1} flexWrap="wrap" className={admin?'finance-subnav':undefined}>
   <Button component={Link} aria-current={!orderId&&tab!=='settings'?'page':undefined} to={`${basePath}?${(()=>{const q=new URLSearchParams(params);q.delete('tab');return q})()}`}>{orderId?'← 返回订单列表':'订单与余额'}</Button>
   {!admin&&['deposit','withdraw','exchange','history'].map(t=><Button key={t} onClick={()=>{if(orderId)navigate(`${basePath}?tab=${t}`);else query({tab:t,page:''})}}>{({deposit:'充值',withdraw:'提现',exchange:'OTC 兑换',history:'记录'} as Record<string,string>)[t]}</Button>)}
   {admin&&!orderId&&permissions.includes('configure')&&<Button aria-current={tab==='settings'?'page':undefined} onClick={()=>query({tab:tab==='settings'?'history':'settings'})}>费率与成交价</Button>}
   <Button className={admin?'finance-refresh':undefined} onClick={()=>{setError('');setReload(x=>x+1)}}>刷新</Button>
  </Stack>
  {error&&<Alert severity="error">{error}</Alert>}
  {pending&&<Alert severity="warning" action={<Button disabled={busy} onClick={()=>void run(pending)}>重试同一请求</Button>}>请求结果待确认。保留原请求标识，请勿重复新建订单。</Alert>}
  {!snapshot&&!error&&<Typography>正在读取资金账户…</Typography>}
  {snapshot&&<>
   {(!admin||tab!=='settings'||orderId)&&<Box component={admin&&orderId?'details':'div'} className={admin&&orderId?'finance-basis':undefined}>{admin&&orderId&&<summary>查看客户钱包与预占资金</summary>}<Box className={admin?'finance-wallets':undefined} sx={!admin?{display:'flex',flexDirection:{xs:'column',md:'row'},gap:2}:undefined}>{(['USDT','USD'] as const).map(c=>{const wallets=snapshot.ledger.accounts.filter(a=>a.currency===c&&a.kind==='wallet');const holds=snapshot.ledger.accounts.filter(a=>a.currency===c&&a.kind==='escrow').reduce((v,a)=>v+BigInt(a.heldMinor),0n);return <Paper key={c} className={admin?'finance-wallet':undefined} variant="outlined" sx={{p:2,flex:1}}><Typography variant="h6">{c} 钱包</Typography><Typography>{wallets.length?cryptoMoney(wallets.reduce((v,a)=>v+BigInt(a.ledgerAvailableMinor),0n).toString(),c):'尚未建立钱包'}</Typography><Typography color="text.secondary">资金在途 / 预占：{cryptoMoney(holds.toString(),c)}</Typography><Typography color="text.secondary">待入账：{snapshot.pendingDepositsMinor?cryptoMoney(snapshot.pendingDepositsMinor[c],c):'待查询'}</Typography></Paper>})}</Box></Box>}
   <Typography variant="body2" color="text.secondary" sx={{fontSize:12}}>账本核对：{label(snapshot.ledger.reconciliation)} · 仅核对本地分录与 Blnk，不代表上游资金池对平。</Typography>
   {o&&(admin?<Paper variant="outlined" sx={{p:3}}><Stack spacing={2}>
    <div className={admin?'finance-order-heading':undefined}><div><Typography variant="h5">{label(o.kind)}详情</Typography><Typography variant="caption" color="text.secondary" sx={{overflowWrap:'anywhere',display:'block',mt:1}}>订单 · {o.id}</Typography></div><Stack direction="row" spacing={1}><Chip size="small" label={label(o.state)}/><Chip size="small" variant="outlined" label={`记账：${label(o.postingStatus)}`}/></Stack></div>
    <dl className="finance-facts">
    <div><dt>申请金额</dt><dd className="finance-money">{cryptoMoney(o.amountMinor,o.currency)}</dd></div><div><dt>到账金额</dt><dd className="finance-money">{cryptoMoney(o.receiveMinor,o.toCurrency)}</dd></div><div><dt>手续费</dt><dd>{cryptoMoney(o.feeMinor,o.currency)}</dd></div>
    <div><dt>审核</dt><dd>{label(o.approvalStatus)}</dd></div><div><dt>渠道</dt><dd>{label(o.providerStatus)}</dd></div><div><dt>链上</dt><dd>{label(o.chainStatus)}</dd></div>
    {o.quote&&<div className="finance-wide"><dt>锁定成交价 / 配置版本</dt><dd>{o.quote.rate||'不适用'} · {o.quote.policyRevision}</dd></div>}
    {o.address&&<div className="finance-wide"><dt>收款地址{o.network?' · '+o.network:''}</dt><dd>{o.address}</dd></div>}
    </dl>
    {o.error&&<Alert severity="warning">{o.error==='insufficient_balance'?'钱包余额不足': '订单需要恢复或核查，资金状态以账本为准。'}</Alert>}
    {admin&&((permissions.includes('review')&&o.state==='pending_review')||(permissions.includes('recover')&&['reserving','processing','releasing'].includes(o.state)))&&<TextField label="操作说明" value={note} onChange={e=>setNote(e.target.value)} multiline/>}
    {admin&&permissions.includes('review')&&o.state==='pending_review'&&<Stack direction="row" spacing={2}>{['approve','reject'].map(action=><Button key={action} variant={action==='approve'?'contained':'outlined'} color={action==='approve'?'primary':'error'} disabled={disabled||!note.trim()||!extraFeesValid} onClick={()=>submit(action,{orderId:o.id,revision:o.revision,note})}>{action==='approve'?'批准出金':'拒绝并释放'}</Button>)}</Stack>}
    {admin&&permissions.includes('recover')&&['reserving','processing','releasing'].includes(o.state)&&<Button disabled={disabled||!note.trim()||!extraFeesValid} onClick={()=>submit('recover',{orderId:o.id,revision:o.revision,note})}>恢复原任务</Button>}
    {!admin&&o.state==='pending_review'&&<Button disabled={disabled} onClick={()=>submit('cancel',{orderId:o.id,revision:o.revision})}>取消申请</Button>}
    <div className={admin?'finance-order-audit':undefined}><div><Typography variant="h6">账本记录</Typography>{(detail.postings||[]).map((p,i)=><Box className="finance-timeline" key={p.id+':'+i}><Typography variant="body2">{cryptoMoney(p.amountMinor,p.currency)} · {label(p.state)}</Typography><Typography variant="caption" sx={{overflowWrap:'anywhere'}}>关联编号：{p.reference||p.id}</Typography></Box>)}{!detail.postings?.length&&<Typography variant="body2" color="text.secondary" sx={{mt:1}}>暂无账本记录，不能据此认定已入账。</Typography>}</div><div><Typography variant="h6">处理时间线</Typography>{detail.events.map((ev,i)=><Typography className="finance-timeline" key={i} variant="body2">{new Date(ev.createdAt).toLocaleString()} · {label(ev.action)}</Typography>)}{!detail.events.length&&<Typography variant="body2" color="text.secondary" sx={{mt:1}}>暂无处理记录</Typography>}</div></div>
   </Stack></Paper>:<Paper variant="outlined" sx={{p:3}}><Stack spacing={2}>
    <Typography variant="h5">{label(o.kind)}详情</Typography><Typography sx={{overflowWrap:'anywhere'}}>{o.id}</Typography>
    <Stack direction="row" spacing={1}><Chip label={label(o.state)}/><Chip label={`记账：${label(o.postingStatus)}`}/></Stack>
    <Typography>金额：{cryptoMoney(o.amountMinor,o.currency)} · 到账：{cryptoMoney(o.receiveMinor,o.toCurrency)} · 手续费：{cryptoMoney(o.feeMinor,o.currency)}</Typography>
    {o.quote&&<Typography>锁定成交价：{o.quote.rate||'不适用'} · 配置版本 {o.quote.policyRevision}</Typography>}
    {o.address&&<Typography sx={{overflowWrap:'anywhere'}}>地址：{o.address}</Typography>}
    <Typography>审核：{label(o.approvalStatus)} · 渠道：{label(o.providerStatus)} · 链上：{label(o.chainStatus)}</Typography>
    {o.error&&<Alert severity="warning">{o.error==='insufficient_balance'?'钱包余额不足': '订单需要恢复或核查，资金状态以账本为准。'}</Alert>}
    {admin&&<TextField label="操作说明" value={note} onChange={e=>setNote(e.target.value)} multiline/>}
    {admin&&permissions.includes('review')&&o.state==='pending_review'&&<Stack direction="row" spacing={2}>{['approve','reject'].map(action=><Button key={action} disabled={disabled||!note.trim()||!extraFeesValid} onClick={()=>submit(action,{orderId:o.id,revision:o.revision,note})}>{action==='approve'?'批准出金':'拒绝并释放'}</Button>)}</Stack>}
    {admin&&permissions.includes('recover')&&['reserving','processing','releasing'].includes(o.state)&&<Button disabled={disabled||!note.trim()||!extraFeesValid} onClick={()=>submit('recover',{orderId:o.id,revision:o.revision,note})}>恢复原任务</Button>}
    {!admin&&o.state==='pending_review'&&<Button disabled={disabled} onClick={()=>submit('cancel',{orderId:o.id,revision:o.revision})}>取消申请</Button>}
    <Divider/><Typography variant="h6">账本记录</Typography>{(detail.postings||[]).map((p,i)=><Box key={p.id+':'+i}><Typography>{cryptoMoney(p.amountMinor,p.currency)} · {label(p.state)}</Typography><Typography variant="caption" sx={{overflowWrap:'anywhere'}}>关联编号：{p.reference||p.id}</Typography></Box>)}<Divider/><Typography variant="h6">处理时间线</Typography>{detail.events.map((ev,i)=><Typography key={i} variant="body2">{new Date(ev.createdAt).toLocaleString()} · {label(ev.action)}</Typography>)}
   </Stack></Paper>)}
   {!orderId&&!admin&&tab==='deposit'&&<Paper variant="outlined" sx={{p:3}}><Stack spacing={2}><Typography variant="h6">USDT / TRON 充值</Typography><Alert severity="warning">此处为隔离地址标识，请勿向其转账。充值验证通过本地固定回执进行。</Alert>{snapshot.addresses.map(a=><Typography key={a.address} sx={{overflowWrap:'anywhere'}}>{a.address}</Typography>)}{!snapshot.addresses.length&&<Button disabled={disabled} onClick={()=>submit('addresses',{})}>建立隔离收款地址</Button>}</Stack></Paper>}
   {!orderId&&!admin&&['exchange','withdraw'].includes(tab)&&<Paper variant="outlined" sx={{p:3}}><Stack spacing={2}>
    <Typography variant="h6">{tab==='exchange'?'OTC 双向兑换':'USDT / TRON 提现'}</Typography>
    {tab==='exchange'&&<TextField select label="卖出资产" value={currency} onChange={e=>{setCurrency(e.target.value as 'USD'|'USDT');setQuote(null)}}><MenuItem value="USDT">USDT → USD</MenuItem><MenuItem value="USD">USD → USDT</MenuItem></TextField>}
    <TextField label="卖出 / 提现金额" value={amount} onChange={e=>{setAmount(e.target.value);setQuote(null)}} inputProps={{inputMode:'decimal'}}/>
    {tab==='withdraw'&&<TextField label="TRON 收款地址（本次不会发送真实交易）" value={address} onChange={e=>{setAddress(e.target.value);setQuote(null)}}/>}
    <Button variant="outlined" disabled={disabled} onClick={preview}>获取报价</Button>
    {quote&&<><Typography>支付 {cryptoMoney(quote.amountMinor,quote.currency)}，到账 {cryptoMoney(quote.receiveMinor,quote.toCurrency)}</Typography><Typography>手续费 {cryptoMoney(quote.feeMinor,quote.currency)} · 总扣款 {cryptoMoney((BigInt(quote.amountMinor)+BigInt(quote.feeMinor)).toString(),quote.currency)}</Typography>{quote.kind==='otc'&&<Typography>1 {quote.currency} = {quote.rate} {quote.toCurrency} · 费用包含在成交价中</Typography>}<Typography>有效至 {new Date(quote.expiresAt).toLocaleTimeString()}</Typography><Button variant="contained" disabled={disabled||Date.parse(quote.expiresAt)<=clock} onClick={()=>submit(quote.kind==='otc'?'otc/orders':'withdrawals/orders',{quoteId:quote.id,...(quote.kind==='withdrawal'?{address}:{})})}>确认{quote.kind==='otc'?'兑换':'提现申请'}</Button></>}
   </Stack></Paper>}
   {admin&&!orderId&&tab==='settings'&&permissions.includes('configure')&&settings&&<Paper className="finance-settings" variant="outlined" sx={{p:3}}><Stack spacing={2}><Typography variant="h6">费用与双向成交价</Typography><Typography variant="body2">当前资金范围共用此配置；更新后尚未提交的旧报价失效。OTC 无库存管理和人工审批。</Typography><TextField label="1 USDT 可获得 USD" value={settings.usdtToUsd} onChange={e=>setSettings({...settings,usdtToUsd:e.target.value})}/><TextField label="1 USD 可获得 USDT" value={settings.usdToUsdt} onChange={e=>setSettings({...settings,usdToUsdt:e.target.value})}/><TextField label="提现固定手续费（USDT）" helperText="留空表示未配置；0 表示免费" value={feeText??(settings.withdrawalFeeMinor===null?'':cryptoMoney(settings.withdrawalFeeMinor,'USDT').split(' ')[0])} onChange={e=>setFeeText(e.target.value)}/><div className="finance-wide finance-switches"><FormControlLabel label="启用 OTC" control={<Switch checked={settings.otcEnabled} onChange={(_,v)=>setSettings({...settings,otcEnabled:v})}/>}/><FormControlLabel label="启用提现" control={<Switch checked={settings.withdrawEnabled} onChange={(_,v)=>setSettings({...settings,withdrawEnabled:v})}/>}/></div><FundsFeeSettings key={feeReset} settings={settings} onChange={setSettings} onValidityChange={setExtraFeesValid} disabled={disabled}/><TextField className="finance-wide" label="修改原因" value={note} onChange={e=>setNote(e.target.value)}/><Stack direction="row"><Button variant="contained" disabled={disabled||!note.trim()||!extraFeesValid} onClick={()=>{try{const fee=feeText===null?settings.withdrawalFeeMinor:feeText.trim()===''?null:/^0(?:\.0{1,6})?$/.test(feeText)?'0':cryptoUnits(feeText,'USDT');submit('settings',{settings:{...settings,withdrawalFeeMinor:fee},note})}catch(e){setError(cryptoError(e))}}}>保存配置</Button><Button onClick={()=>{setSettings(snapshot.settings);setFeeText(null);setFeeReset(v=>v+1)}}>载入最新配置</Button></Stack></Stack></Paper>}
   {!orderId&&(!admin||tab!=='settings'||!permissions.includes('configure'))&&<div className={admin?'finance-section':undefined}><div className="finance-section-toolbar"><Typography variant="h6">资金订单（{snapshot.total}）</Typography><TextField select size="small" label="状态" value={status} onChange={e=>query({status:e.target.value,page:''})}><MenuItem value="">全部</MenuItem>{['reserving','pending_review','processing','completed','rejected','failed','unknown','cancelled'].map(s=><MenuItem key={s} value={s}>{label(s)}</MenuItem>)}</TextField></div><Box tabIndex={0} role="region" aria-label="资金订单，可横向滚动" sx={{overflowX:'auto'}}><Table className="finance-order-table"><TableHead><TableRow>{['类型','金额','到账','状态','创建时间','详情'].map(v=><TableCell key={v}>{v}</TableCell>)}</TableRow></TableHead><TableBody>{snapshot.orders.map(v=><TableRow key={v.id}><TableCell>{label(v.kind)}</TableCell><TableCell>{cryptoMoney(v.amountMinor,v.currency)}</TableCell><TableCell>{cryptoMoney(v.receiveMinor,v.toCurrency)}</TableCell><TableCell><span className="finance-status" data-state={v.state}>{label(v.state)}</span></TableCell><TableCell>{new Date(v.createdAt).toLocaleString()}</TableCell><TableCell><Button component={Link} to={orderLink(v.id)}>查看</Button></TableCell></TableRow>)}</TableBody></Table></Box>{!snapshot.orders.length&&<Alert severity="info">当前筛选范围没有订单。</Alert>}<div className="finance-pagination"><Button disabled={page<=0} onClick={()=>query({page:String(page-1)})}>上一页</Button><Typography>第 {page+1} 页</Typography><Button disabled={(page+1)*20>=snapshot.total} onClick={()=>query({page:String(page+1)})}>下一页</Button></div></div>}
  </>}
 </Stack>;
}
