import DepositAddress from './DepositAddress';
import {useEffect,useRef,useState} from 'react';
import {Alert,Box,Button,Chip,MenuItem,Paper,Stack,Table,TableBody,TableCell,TableContainer,TableHead,TableRow,TextField,Typography} from '@mui/material';
import {Link,useLocation,useNavigate} from 'react-router-dom';
import {QRCodeSVG} from 'qrcode.react';
import {useAuth} from '../auth/AuthContext';
import {cryptoRequest,cryptoError} from '../auth/cryptoApi';
import {SessionError} from '../auth/liveApi';
import {cryptoMoney,cryptoUnits,type CryptoSnapshot,type CryptoQuote,type CryptoOrder} from '../auth/cryptoContract';
const names:Record<string,string>={deposit:'USDT 充值',withdrawal:'USDT 提款',otc:'OTC',card_transfer:'法币充提',reserving:'资金预占中',pending_review:'待审核',processing:'处理中',releasing:'资金退回中',completed:'已完成',failed:'失败',rejected:'已拒绝',cancelled:'已取消',unknown:'结果待核实',posted:'已入账',reserved:'已预占',pending:'待处理',not_required:'无需审核',approved:'已批准',not_submitted:'未提交',not_verified:'待核验',not_applicable:'不适用'};
const label=(v:string)=>names[v]||v;
const nav=[['','总览'],['deposit','USDT 充值'],['fiat','法币充提'],['withdraw','USDT 提款'],['exchange','OTC'],['history','交易记录']];
type Pending={path:string;body:Record<string,unknown>;key:string};
type Card={id:string;name:string;last4:string;availableMinor:string|null;canOperate:boolean;reason:string};
type View=Omit<CryptoSnapshot,'mode'>&{mode:'shadow'|'live'|'disabled';executionEligible:boolean;cards?:Card[];canOperate?:boolean;addressJobs?:Record<string,string>;networks?:{network:string;depositEnabled:boolean;withdrawEnabled:boolean}[]};
export function CurrencyLogo({currency}:{currency:string}){return <Box component="svg" role="img" aria-label={`${currency} Logo`} viewBox="0 0 40 40" sx={{width:32,height:32,flexShrink:0}}><circle cx="20" cy="20" r="20" fill={currency==='USDT'?'#26A17B':'#2463B5'}/>{currency==='USDT'?<><path d="M10 9h20v5h-7v15h-6V14h-7z" fill="white"/><ellipse cx="20" cy="18" rx="13" ry="3" fill="none" stroke="white" strokeWidth="1.7"/></>:<text x="20" y="29" textAnchor="middle" fill="white" fontSize="29" fontFamily="Arial">$</text>}</Box>}
function FundsContent({customerId,basePath='/portal/funds',orderId}:{customerId:string;basePath?:string;orderId?:string}){
 const {session}=useAuth(),location=useLocation(),navigate=useNavigate();const params=new URLSearchParams(location.search);
 const suffix=location.pathname.slice(basePath.length).split('/')[1]||params.get('tab')||'';
 const section=suffix==='fiat-deposit'?'fiat':suffix;const operation=['deposit','fiat','withdraw','exchange'].includes(section)&&!orderId;
 const kind=operation?({deposit:'deposit',fiat:'card_transfer',withdraw:'withdrawal',exchange:'otc'} as Record<string,string>)[section]:params.get('kind')||'';
 const page=Math.max(0,Number(params.get('page'))||0),status=params.get('status')||'';
 const api=`/client-api/v1/customers/${customerId}/crypto`,storage=`funds-pending:${session?.id}:${customerId}`;
 const [data,setData]=useState<View|null>(null),[detail,setDetail]=useState<{order:CryptoOrder;events:{action:string;createdAt:string}[]}|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[tick,setTick]=useState(0);
 const [network,setNetwork]=useState('TRC20'),[currency,setCurrency]=useState<'USDT'|'USD'>('USDT'),[amount,setAmount]=useState(''),[address,setAddress]=useState(''),[cardId,setCardId]=useState(params.get('cardId')||''),[direction,setDirection]=useState('wallet_to_card'),[quote,setQuote]=useState<CryptoQuote|null>(null),[clock,setClock]=useState(Date.now());
 const [pending,setPending]=useState<Pending|null>(null),inFlight=useRef(false),generation=useRef(0),addressRequested=useRef(new Set<string>());
 useEffect(()=>{try{const p=JSON.parse(sessionStorage.getItem(storage)||'null');setPending(p)}catch{setError('无法恢复待确认请求，请联系运营核对。')}},[storage]);
 useEffect(()=>{generation.current++;setQuote(null);setAmount('');setAddress('');setMessage('');setError('')},[section]);
 useEffect(()=>{let active=true,running=false;setData(null);setDetail(null);const load=async()=>{if(running)return;running=true;try{
 const q=new URLSearchParams({page:String(operation?0:page),limit:operation?'5':'20',kind,status:operation?'':status});if((section==='fiat'||section==='history')&&cardId)q.set('cardId',cardId);
 const s=await cryptoRequest<View>(`${api}?${q}`);if(s.customerId!==customerId||s.mode!=='live')throw new Error('资金响应不一致');if(active){setData(s);setError('')}
 if(orderId){const d=await cryptoRequest<{order:CryptoOrder;events:{action:string;createdAt:string}[]}>(`${api}/orders/${orderId}`);if(active)setDetail(d)}
 }catch(e){if(active){if(e instanceof SessionError&&e.code==='crypto_disabled'&&!orderId){setData({mode:'disabled',executionEligible:false,customerId,canOperate:false,settings:{revision:0,otcEnabled:false,withdrawEnabled:false,usdtToUsd:'',usdToUsdt:'',withdrawalFeeMinor:null},ledger:{accounts:[],reconciliation:'unavailable',totalsMinor:{}},addresses:[],orders:[],total:0,page:0,cards:[],networks:[]});setError('')}else setError(cryptoError(e))}}finally{running=false}};void load();const timer=setInterval(()=>{setClock(Date.now());if(!document.hidden)void load()},5000);return()=>{active=false;clearInterval(timer)}},[api,customerId,orderId,section,kind,status,page,cardId,operation,tick]);
 useEffect(()=>{const timer=setInterval(()=>setClock(Date.now()),1000);return()=>clearInterval(timer)},[]);
 function invalidate(){generation.current++;setQuote(null);setMessage('')}
 async function run(p:Pending){if(inFlight.current)return;inFlight.current=true;setBusy(true);setError('');const requestGeneration=generation.current;
 try{sessionStorage.setItem(storage,JSON.stringify(p));setPending(p);const r=await cryptoRequest<Record<string,unknown>>(p.path,p.body,p.key);sessionStorage.removeItem(storage);setPending(null);
 if(p.path.endsWith('/quotes')){if(generation.current===requestGeneration){setClock(Date.now());setQuote(r as unknown as CryptoQuote)}}else{setTick(v=>v+1);if(typeof r.id==='string'&&typeof r.state==='string')navigate(`${basePath}/orders/${r.id}`,{state:{fundsReturn:location.pathname+location.search}});else setMessage('收款地址申请已保存，正在等待渠道返回。')}
 }catch(e){setError(cryptoError(e));if(e instanceof SessionError&&e.status>=400&&e.status<500&&e.code!=='invalid_api_response'){sessionStorage.removeItem(storage);setPending(null)}}finally{inFlight.current=false;setBusy(false)}}
 function submit(path:string,body:Record<string,unknown>){if(busy||pending)return;void run({path:api+'/'+path,body,key:crypto.randomUUID()})}
 function getQuote(){try{const c=section==='fiat'?'USD':section==='withdraw'?'USDT':currency;const body:Record<string,unknown>={currency:c,amountMinor:cryptoUnits(amount,c)};if(section==='withdraw')Object.assign(body,{network,address});if(section==='fiat')Object.assign(body,{cardId,direction});submit(section==='exchange'?'otc/quotes':section==='fiat'?'cards/quotes':'withdrawals/quotes',body)}catch(e){setError(cryptoError(e))}}
 const blocked=busy||!!pending,canOperate=data?.canOperate!==false,selectedCard=data?.cards?.find(c=>c.id===cardId);
 const selectedAddress=data?.addresses.find(a=>(a.network===network||network==='TRC20'&&a.network==='tron-fixture'||network==='ERC20'&&a.network==='ethereum-fixture')&&a.mode==='live');
 const capability=data?.networks?.find(n=>n.network===network);const balance=(c:string)=>{if(data?.mode==='disabled')return '尚未启用';const rows=data?.ledger.accounts.filter(a=>a.kind==='wallet'&&a.currency===c)||[];if(data?.ledger.reconciliation==='mismatch')return '余额核对中';return rows.length?cryptoMoney(rows.reduce((v,a)=>v+BigInt(a.ledgerAvailableMinor),0n).toString(),c):'尚未开通'};
 const addressState=data?.addressJobs?.[network];
 useEffect(()=>{const requestKey=customerId+':'+network;if(section!=='deposit'||orderId||!data||!data.canOperate||!capability?.depositEnabled||selectedAddress||addressState||blocked||addressRequested.current.has(requestKey))return;addressRequested.current.add(requestKey);submit('addresses',{currency:'USDT',network})},[section,orderId,customerId,network,data,capability?.depositEnabled,selectedAddress,addressState,blocked]);
 const current=section==='fiat'?'USD':section==='exchange'?currency:'USDT';const expired=!!quote&&Date.parse(quote.expiresAt)<=clock;
 function filter(k:string,v:string){const q=new URLSearchParams(location.search);v?q.set(k,v):q.delete(k);if(k!=='page')q.delete('page');navigate(`${basePath}/history?${q}`)}
 const shell=(children:React.ReactNode)=><Paper variant="outlined" sx={{p:{xs:2,md:3}}}>{children}</Paper>;
 const networks=<Stack direction={{xs:'column',sm:'row'}} spacing={2}><TextField select label="币种" value="USDT" disabled fullWidth><MenuItem value="USDT">USDT</MenuItem></TextField><TextField select label="网络" value={network} disabled={blocked} onChange={e=>{invalidate();setNetwork(e.target.value);setAddress('')}} fullWidth><MenuItem value="TRC20">TRON · TRC20</MenuItem><MenuItem value="ERC20">Ethereum · ERC20</MenuItem></TextField></Stack>;
 return <Stack spacing={3}>
 <Stack direction="row" spacing={1} flexWrap="wrap" useFlexGap>{nav.map(([path,title])=><Button key={path} component={Link} to={basePath+(path?'/'+path:'')} variant={!orderId&&section===path?'contained':'outlined'}>{title}</Button>)}<Button onClick={()=>setTick(v=>v+1)} disabled={busy}>刷新</Button></Stack>
 {data?.mode==='disabled'&&<Alert severity="info">资金服务尚未启用，请查看各业务页面的开通状态。</Alert>}
 {error&&<Alert severity="error" action={<Button onClick={()=>setTick(v=>v+1)}>重试查询</Button>}>{error}</Alert>}{message&&<Alert severity="success">{message}</Alert>}
 {pending&&<Alert severity="warning" action={<Button disabled={busy} onClick={()=>void run(pending)}>核对并重试原请求</Button>}>请求结果待确认，系统将沿用原请求编号核对，避免重复提交。</Alert>}
 {!data&&!error&&<Typography role="status">正在加载资金…</Typography>}
 {data&&<>
 {!section&&!orderId&&<><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'1fr 1fr'},gap:2}}>{(['USD','USDT'] as const).map(c=><Paper key={c} variant="outlined" sx={{p:3}}><Stack direction="row" spacing={1} alignItems="center"><CurrencyLogo currency={c}/><Typography>{c} 钱包可用余额</Typography></Stack><Typography variant="h4" sx={{my:2,overflowWrap:'anywhere'}}>{balance(c)}</Typography><Typography color="text.secondary">预占和在途资金不可重复使用</Typography></Paper>)}</Box>{shell(<Stack direction="row" spacing={2} useFlexGap flexWrap="wrap">{nav.slice(1,5).map(([p,t])=><Button key={p} component={Link} to={`${basePath}/${p}`}>{t}</Button>)}</Stack>)}</>}
 {operation&&data&&!data.canOperate&&<Alert severity="info">此业务尚未开通，暂不可提交。</Alert>}
 {operation&&<Typography color="text.secondary">钱包可用：{balance(current)}</Typography>}
 {operation&&!canOperate&&data?.mode!=='disabled'&&<Alert severity="warning">当前账户尚未启用资金办理，已有订单仍可查询。</Alert>}
 {section==='deposit'&&!orderId&&shell(<Stack spacing={3}><Typography variant="h5">USDT 充值</Typography>{networks}
 {selectedAddress?<Box sx={{display:'flex',gap:3,alignItems:'center',flexDirection:{xs:'column',sm:'row'}}}><Box sx={{p:2,bgcolor:'white'}}><QRCodeSVG value={selectedAddress.address} size={180} level="M" marginSize={2}/></Box><Stack spacing={2} sx={{minWidth:0,flex:1}}><Typography>{network} 充值地址</Typography><Typography sx={{overflowWrap:'anywhere',fontFamily:'monospace'}}>{selectedAddress.address}</Typography><Button variant="outlined" onClick={async()=>{try{await navigator.clipboard.writeText(selectedAddress.address);setMessage('充值地址已复制')}catch{setError('复制失败，请手动复制完整地址。')}}}>复制地址</Button><Typography color="text.secondary">仅向此地址充值所选网络的 USDT。确认到账后自动更新余额。</Typography></Stack></Box>:<Stack spacing={2}><Typography color="text.secondary">{addressState==='unknown'||addressState==='submitting'?'地址申请结果待核实，请稍后刷新或联系运营。':addressState==='queued'?'正在由 Cregis 为你生成专属充值地址…':capability?.depositEnabled?'正在申请该网络专属充值地址…':'该网络收款尚未启用。'}</Typography><Button variant="contained" disabled={blocked||!canOperate||!capability?.depositEnabled||!!addressState} onClick={()=>submit('addresses',{currency:'USDT',network})}>重新查询地址</Button></Stack>}
 </Stack>)}
 {section==='fiat'&&!orderId&&shell(<Stack spacing={2}><Typography variant="h5">法币充提</Typography><Stack direction="row" spacing={1}>{[['wallet_to_card','充值到卡'],['card_to_wallet','从卡提现']].map(([d,t])=><Button key={d} variant={direction===d?'contained':'outlined'} disabled={blocked} onClick={()=>{invalidate();setDirection(d)}}>{t}</Button>)}</Stack><TextField select label="选择卡片" value={cardId} disabled={blocked} onChange={e=>{invalidate();setCardId(e.target.value)}}><MenuItem value="">请选择卡片</MenuItem>{data.cards?.map(c=><MenuItem key={c.id} value={c.id}>{c.name} · 尾号 {c.last4}</MenuItem>)}</TextField>{!data.cards?.length&&<Alert severity="info">暂无已建立资金分户的卡片。存量卡核对完成前不开放充提。</Alert>}{selectedCard&&<Typography color="text.secondary">卡片可用：{selectedCard.availableMinor===null?'待核实':cryptoMoney(selectedCard.availableMinor,'USD')}{!selectedCard.canOperate?' · '+selectedCard.reason:''}</Typography>}<TextField label="金额（USD）" value={amount} disabled={blocked} inputProps={{inputMode:'decimal'}} onChange={e=>{invalidate();setAmount(e.target.value)}}/><Button variant="outlined" disabled={blocked||!canOperate||!amount||!selectedCard?.canOperate} onClick={getQuote}>查看费用</Button></Stack>)}
 {section==='withdraw'&&!orderId&&shell(<Stack spacing={2}><Typography variant="h5">USDT 提款</Typography>{networks}<TextField label="收款地址" value={address} disabled={blocked} autoComplete="off" onChange={e=>{invalidate();setAddress(e.target.value.trim())}}/><TextField label="提款金额（USDT）" value={amount} disabled={blocked} inputProps={{inputMode:'decimal'}} onChange={e=>{invalidate();setAmount(e.target.value)}}/><Button variant="outlined" disabled={blocked||!canOperate||!amount||!address||capability?.withdrawEnabled===false} onClick={getQuote}>查看费用</Button><Typography color="text.secondary">提交后预占本金与费用，运营审核通过后处理出金。</Typography></Stack>)}
 {section==='exchange'&&!orderId&&shell(<Stack spacing={2} sx={{maxWidth:640,mx:'auto'}}><Typography variant="h5">OTC</Typography><Paper variant="outlined" sx={{p:2}}><Stack spacing={2}><Typography color="text.secondary">卖出</Typography><Stack direction="row" alignItems="center" spacing={1}><CurrencyLogo currency={currency}/><Typography>{currency}</Typography></Stack><TextField label="卖出金额" value={amount} disabled={blocked} inputProps={{inputMode:'decimal'}} onChange={e=>{invalidate();setAmount(e.target.value)}}/></Stack></Paper><Button aria-label="切换兑换方向" disabled={blocked} onClick={()=>{invalidate();setCurrency(c=>c==='USDT'?'USD':'USDT');setAmount('')}} sx={{alignSelf:'center'}}>⇅</Button><Paper variant="outlined" sx={{p:2}}><Stack spacing={2}><Typography color="text.secondary">买入</Typography><Stack direction="row" alignItems="center" spacing={1}><CurrencyLogo currency={currency==='USDT'?'USD':'USDT'}/><Typography>{currency==='USDT'?'USD':'USDT'}</Typography></Stack><Typography variant="h5">{quote?cryptoMoney(quote.receiveMinor,quote.toCurrency):'—'}</Typography></Stack></Paper><Button variant="outlined" disabled={blocked||!canOperate||!amount} onClick={getQuote}>获取报价</Button></Stack>)}
 {operation&&quote&&shell(<Stack spacing={2}><Typography>本金 {cryptoMoney(quote.amountMinor,quote.currency)} · 费用 {cryptoMoney(quote.feeMinor,quote.currency)}</Typography><Typography>合计扣款 {cryptoMoney((BigInt(quote.amountMinor)+BigInt(quote.feeMinor)).toString(),quote.currency)}</Typography><Typography>到账 {cryptoMoney(quote.receiveMinor,quote.toCurrency)}</Typography>{quote.rate&&<Typography>成交价：1 {quote.currency} = {quote.rate} {quote.toCurrency}</Typography>}{section==='withdraw'&&<Typography sx={{overflowWrap:'anywhere'}}>网络：{network} · 收款地址：{address}</Typography>}<Typography color={expired?'error':'text.secondary'}>{expired?'报价已过期，请重新获取':`报价剩余 ${Math.max(0,Math.ceil((Date.parse(quote.expiresAt)-clock)/1000))} 秒`}</Typography><Button variant="contained" disabled={blocked||expired||!canOperate} onClick={()=>submit(section==='exchange'?'otc/orders':section==='fiat'?'cards/orders':'withdrawals/orders',{quoteId:quote.id,...(section==='withdraw'?{address,network}:{})})}>{section==='exchange'?'确认兑换':section==='fiat'?'确认划转':'发起提款'}</Button></Stack>)}
 {orderId&&detail&&shell(<Stack spacing={2}><Button component={Link} to={typeof location.state?.fundsReturn==='string'&&location.state.fundsReturn.startsWith(basePath+'/')?location.state.fundsReturn:basePath+'/history'} sx={{alignSelf:'start'}}>返回记录</Button><Typography variant="h5">{label(detail.order.kind)}详情</Typography><Chip label={label(detail.order.state)} sx={{alignSelf:'start'}}/><Typography sx={{overflowWrap:'anywhere'}}>订单 {detail.order.id}</Typography><Typography>本金 {cryptoMoney(detail.order.amountMinor,detail.order.currency)} · 费用 {cryptoMoney(detail.order.feeMinor,detail.order.currency)}</Typography><Typography>到账 {cryptoMoney(detail.order.receiveMinor,detail.order.toCurrency)}</Typography>{detail.order.network&&<Typography>网络：{detail.order.network}</Typography>}{detail.order.address&&<Typography sx={{overflowWrap:'anywhere'}}>地址：{detail.order.address}</Typography>}<Typography>审核：{label(detail.order.approvalStatus)} · 渠道：{label(detail.order.providerStatus)} · 记账：{label(detail.order.postingStatus)}</Typography>{detail.order.state==='unknown'&&<Alert severity="warning">结果待核实，资金继续预占，请勿重复发起。</Alert>}{detail.order.state==='pending_review'&&<Button disabled={blocked} onClick={()=>submit('cancel',{orderId:detail.order.id,revision:detail.order.revision})}>取消申请</Button>}<Typography variant="h6">处理记录</Typography>{detail.events.map((ev,i)=><Typography key={i}>{new Date(ev.createdAt).toLocaleString()} · {label(ev.action)}</Typography>)}</Stack>)}
 {!orderId&&shell(<Stack spacing={2}><Stack direction="row" justifyContent="space-between" alignItems="center"><Typography variant="h6">{operation?`最近 5 条${section==='exchange'?'交易':section==='deposit'?'充值':section==='fiat'?'充提':'提款'}记录`:'交易记录'}</Typography>{operation&&<Button component={Link} to={`${basePath}/history?kind=${kind}${section==='fiat'&&cardId?'&cardId='+encodeURIComponent(cardId):''}`}>查看全部</Button>}</Stack>{!operation&&<Stack direction="row" spacing={2}><TextField select label="类型" value={kind} onChange={e=>filter('kind',e.target.value)} sx={{minWidth:150}}><MenuItem value="">全部</MenuItem>{['deposit','card_transfer','withdrawal','otc'].map(k=><MenuItem key={k} value={k}>{label(k)}</MenuItem>)}</TextField><TextField select label="状态" value={status} onChange={e=>filter('status',e.target.value)} sx={{minWidth:150}}><MenuItem value="">全部</MenuItem>{['pending_review','processing','completed','failed','rejected','unknown','cancelled'].map(s=><MenuItem key={s} value={s}>{label(s)}</MenuItem>)}</TextField></Stack>}<TableContainer><Table size="small"><TableHead><TableRow>{['时间','类型 / 网络','金额','状态',''].map((v,i)=><TableCell key={i}>{v}</TableCell>)}</TableRow></TableHead><TableBody>{data.orders.map(o=><TableRow key={o.id}><TableCell>{new Date(o.createdAt).toLocaleString()}</TableCell><TableCell>{label(o.kind)}{o.network?' · '+o.network:''}</TableCell><TableCell sx={{whiteSpace:'nowrap'}}>{cryptoMoney(o.amountMinor,o.currency)}</TableCell><TableCell>{label(o.state)}</TableCell><TableCell><Button component={Link} to={`${basePath}/orders/${o.id}`} state={{fundsReturn:location.pathname+location.search}}>详情</Button></TableCell></TableRow>)}</TableBody></Table></TableContainer>{!data.orders.length&&<Typography color="text.secondary">{data.mode==='disabled'?'资金记录尚不可用':'暂无记录'}</Typography>}{!operation&&data.mode!=='disabled'&&<Stack direction="row" spacing={2}><Button disabled={page===0} onClick={()=>filter('page',String(page-1))}>上一页</Button><Typography>第 {page+1} 页 · 共 {data.total} 笔</Typography><Button disabled={(page+1)*20>=data.total} onClick={()=>filter('page',String(page+1))}>下一页</Button></Stack>}</Stack>)}
 </>}
 </Stack>
}

export default function CustomerFunds(props:{customerId:string;basePath?:string;orderId?:string}){const location=useLocation();const basePath=props.basePath||'/portal/funds';return !props.orderId&&(location.pathname===basePath+'/deposit'||new URLSearchParams(location.search).get('tab')==='deposit')?<DepositAddress customerId={props.customerId} basePath={basePath}/>:<FundsContent {...props}/>;}
