import {useEffect,useRef,useState} from 'react';
import {Alert,Button,Dialog,DialogActions,DialogContent,DialogTitle,MenuItem,Paper,Stack,Table,TableBody,TableCell,TableContainer,TableHead,TableRow,TextField,Typography} from '@mui/material';
import {Link,useLocation,useNavigate,useSearchParams} from 'react-router-dom';
import {useAuth} from '../auth/AuthContext';
import {SessionError} from '../auth/liveApi';
import {manualRequest,manualError} from '../auth/manualFundsApi';
import {manualLabels,type ManualOrder} from '../auth/manualFundsContract';
import {cryptoMoney,cryptoUnits} from '../auth/cryptoContract';
const label=(s:string)=>manualLabels[s]||s;
type Pending={path:string;body:Record<string,unknown>;key:string};
type List={orders:ManualOrder[];total:number;page:number;mode:string;enabled:boolean};
type Detail={order:ManualOrder;events:{action:string;createdAt:string;actorId?:string;data?:{note?:string}}[];eventsHasMore:boolean;mode:string;enabled:boolean};
type Props={customerId:string;admin?:boolean;orderId?:string;basePath:string;permissions?:string[];canOperate?:boolean;onChanged?:()=>void};
export default function ManualFunds({customerId,admin=false,orderId,basePath,permissions=[],canOperate=false,onChanged}:Props){
 const {session}=useAuth(),navigate=useNavigate(),location=useLocation();const [params,setParams]=useSearchParams();
 const page=Math.max(0,Number(params.get('manualPage'))||0),api=`/${admin?'admin':'client'}-api/v1/customers/${customerId}/manual-funds`,storage=`manual-funds:${session?.id}:${customerId}:${admin}`;
 const [list,setList]=useState<List|null>(null),[detail,setDetail]=useState<Detail|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[tick,setTick]=useState(0),[pending,setPending]=useState<Pending|null>(null);
 const [dialog,setDialog]=useState(''),[source,setSource]=useState('platform_advance'),[amount,setAmount]=useState(''),[note,setNote]=useState(''),[evidence,setEvidence]=useState(''),[original,setOriginal]=useState('');
 const flight=useRef(false),alive=useRef(true),changed=useRef(onChanged);changed.current=onChanged;
 useEffect(()=>{alive.current=true;try{const p=JSON.parse(sessionStorage.getItem(storage)||'null');if(p&&typeof p.path==='string'&&p.path.startsWith(api+'/orders')&&typeof p.key==='string'&&p.body)setPending(p)}catch{setError('无法恢复待确认请求，请核对订单。')}return()=>{alive.current=false}},[storage,api]);
 useEffect(()=>{let active=true,running=false;setList(null);setDetail(null);setError('');async function load(){if(running)return;running=true;setLoading(true);try{if(orderId){const d=await manualRequest<Detail>(api+'/orders/'+orderId);if(d.order.customerId!==customerId)throw new Error('订单归属不一致');if(active)setDetail(d)}else{const v=await manualRequest<List>(api+'?page='+page);if(active)setList(v)}if(active)setError('')}catch(e){if(active)setError(manualError(e))}finally{running=false;if(active)setLoading(false)}}void load();const timer=setInterval(()=>{if(!document.hidden)void load()},5000);return()=>{active=false;clearInterval(timer)}},[api,orderId,page,tick,customerId]);
 const suffix=location.search,orderLink=(id:string)=>`${basePath}/orders/${id}${suffix}`;
 async function run(p:Pending){if(flight.current)return;flight.current=true;setBusy(true);setError('');try{sessionStorage.setItem(storage,JSON.stringify(p));setPending(p);const o=await manualRequest<ManualOrder>(p.path,p.body,p.key);sessionStorage.removeItem(storage);if(alive.current){setPending(null);setDialog('');setTick(n=>n+1);changed.current?.();navigate(orderLink(o.id),{state:location.state})}}catch(e){if(alive.current){setError(manualError(e));if(e instanceof SessionError&&e.status>=400&&e.status<500){sessionStorage.removeItem(storage);setPending(null);setTick(n=>n+1)}}}finally{flight.current=false;if(alive.current)setBusy(false)}}
 function submit(){if(busy||pending)return;try{let body:Record<string,unknown>,path=api+'/orders';if(dialog==='credit'||dialog==='debit'||dialog==='reversal'){body={customerId,currency:'USD',amountMinor:cryptoUnits(amount,'USD'),source:dialog==='reversal'?'reversal':source,note:note.trim(),evidenceRef:evidence.trim(),...((source==='advance_recovery'||dialog==='reversal')?{originalId:original}:{})}}else{if(!detail)return;path+='/'+detail.order.id+'/'+dialog;body={revision:detail.order.revision,note:note.trim(),...(['confirm_payment','payment_failed'].includes(dialog)?{evidenceRef:evidence.trim()}:{})}}if(!body.note)throw new Error('请填写原因或备注');if((dialog==='credit'||dialog==='debit'||dialog==='reversal'||dialog.includes('payment'))&&!evidence.trim())throw new Error('请填写凭证引用');void run({path,body,key:crypto.randomUUID()})}catch(e){setError(manualError(e))}}
 function open(action:string){setDialog(action);setNote('');setEvidence('');setAmount(action==='reversal'&&detail?cryptoMoney(detail.order.amountMinor,'USD').replace(' USD',''):'');setOriginal(action==='reversal'&&detail?detail.order.id:'');setSource(action==='debit'?'advance_recovery':'platform_advance')}
 const o=detail?.order,enabled=(list?.enabled??detail?.enabled)===true,canCreate=admin&&permissions.includes('create')&&enabled&&canOperate,canReview=admin&&permissions.includes('review')&&enabled,canExecute=admin&&permissions.includes('execute')&&enabled;
 const disabled=busy||!!pending,actionNames:Record<string,string>={credit:'人工入金',debit:'人工出金',reversal:'申请冲正',approve:'批准',reject:'拒绝',cancel:'取消申请',confirm_payment:'确认线下已付款',payment_failed:'确认付款失败',reconcile:'重新核对原单'};
 return <Stack spacing={2}>
 <Stack direction="row" gap={1} flexWrap="wrap" alignItems="center"><Typography variant="h6" sx={{flex:1}}>人工出入金记录</Typography>{admin&&<><Button variant="contained" disabled={!canCreate||disabled} onClick={()=>open('credit')}>人工入金</Button><Button variant="outlined" disabled={!canCreate||disabled} onClick={()=>open('debit')}>人工出金</Button></>}<Button disabled={loading} onClick={()=>setTick(n=>n+1)}>刷新记录</Button></Stack>
 {(list?.mode==='shadow'||detail?.mode==='shadow')&&<Alert severity="info">隔离账本验证环境，记录不代表真实到账。</Alert>}
 {admin&&!enabled&&!loading&&<Alert severity="info">人工出入金服务尚未启用。</Alert>}
 {error&&<Alert severity="error" action={<Button onClick={()=>setTick(n=>n+1)}>重试查询</Button>}>{error}</Alert>}
 {pending&&<Alert severity="warning" action={<Button disabled={busy} onClick={()=>void run(pending)}>重试同一请求</Button>}>上次提交结果待确认，请查询原单或使用同一请求重试。</Alert>}
 {loading&&!list&&!detail&&<Typography>正在读取记录…</Typography>}
 {o&&<Paper variant="outlined" sx={{p:{xs:2,md:3},minWidth:0}}><Stack spacing={2}><Button component={Link} state={location.state} to={basePath+suffix} sx={{alignSelf:'start'}}>返回人工出入金记录</Button><Typography variant="h5">{label(o.source)} · {label(o.direction)}</Typography><Typography>{label(o.state)} · {cryptoMoney(o.amountMinor,o.currency)}</Typography><Typography sx={{overflowWrap:'anywhere'}}>订单：{o.id}</Typography>{o.originalId&&<Button component={Link} state={location.state} to={orderLink(o.originalId)}>查看关联原单</Button>}<Typography>钱包变动：{o.walletBeforeMinor===null?'待记账':cryptoMoney(o.walletBeforeMinor,o.currency)} → {o.walletAfterMinor===null?'待记账':cryptoMoney(o.walletAfterMinor,o.currency)}</Typography>{o.direction==='debit'&&<Typography color="text.secondary">出金钱包变动显示预占时的余额变化，结算完成后预占资金才转出；拒绝或取消会另行释放。</Typography>}{admin&&<><Typography>原因：{o.note}</Typography><Typography sx={{overflowWrap:'anywhere'}}>凭证：{o.evidenceRef}</Typography>{o.paymentEvidence&&<Typography>付款结果凭证：{o.paymentEvidence}</Typography>}</>}{o.error&&<Alert severity="warning">{o.error==='insufficient_balance'?'余额不足，订单未执行。':'资金结果待核实，原单将按同一记账编号恢复。'}</Alert>}
 <Stack direction="row" gap={1} flexWrap="wrap" alignItems="center">{o.state==='pending_review'&&canReview&&<><Button disabled={disabled||!canOperate} onClick={()=>open('approve')}>批准</Button><Button color="error" disabled={disabled} onClick={()=>open('reject')}>拒绝</Button></>}{o.state==='pending_review'&&admin&&o.actorId===session?.id&&permissions.includes('create')&&<Button disabled={disabled} onClick={()=>open('cancel')}>取消申请</Button>}{o.state==='awaiting_payment'&&canExecute&&<><Button disabled={disabled} onClick={()=>open('confirm_payment')}>确认线下已付款</Button><Button color="error" disabled={disabled} onClick={()=>open('payment_failed')}>确认付款失败</Button></>}{['processing','reserving','releasing'].includes(o.state)&&canExecute&&<Button disabled={disabled} onClick={()=>open('reconcile')}>重新核对原单</Button>}{o.state==='completed'&&canCreate&&['platform_advance','advance_recovery'].includes(o.source)&&<Button disabled={disabled} onClick={()=>open('reversal')}>申请冲正</Button>}</Stack>
 <Typography variant="h6">处理记录</Typography>{detail.events.map((e,i)=><Typography key={i}>{new Date(e.createdAt).toLocaleString()} · {actionNames[e.action]||({create:'创建申请',worker:'账务处理',read:'查询记录'} as Record<string,string>)[e.action]||e.action}{admin&&e.data?.note?' · '+e.data.note:''}</Typography>)}{detail.eventsHasMore&&<Typography color="text.secondary">仅显示最近 100 条处理记录。</Typography>}</Stack></Paper>}
 {!orderId&&list&&<><TableContainer component={Paper} variant="outlined" tabIndex={0} aria-label="人工出入金记录，可横向滚动"><Table size="small" sx={{minWidth:600}}><TableHead><TableRow>{['时间','类型','金额','状态',''].map((s,i)=><TableCell key={i}>{s}</TableCell>)}</TableRow></TableHead><TableBody>{list.orders.map(o=><TableRow key={o.id}><TableCell>{new Date(o.createdAt).toLocaleString()}</TableCell><TableCell>{label(o.source)} · {label(o.direction)}</TableCell><TableCell>{cryptoMoney(o.amountMinor,o.currency)}</TableCell><TableCell>{label(o.state)}</TableCell><TableCell><Button component={Link} state={location.state} to={orderLink(o.id)}>详情</Button></TableCell></TableRow>)}</TableBody></Table></TableContainer>{!list.orders.length&&<Typography color="text.secondary">{list.mode==='disabled'?'人工出入金服务尚未启用':'暂无人工出入金记录'}</Typography>}<Stack direction="row" gap={1} flexWrap="wrap" alignItems="center" justifyContent="space-between"><Button disabled={page===0||loading} onClick={()=>{const q=new URLSearchParams(params);q.set('manualPage',String(page-1));setParams(q,{state:location.state})}}>上一页</Button><Typography>第 {page+1} 页 · 共 {list.total} 笔</Typography><Button disabled={(page+1)*20>=list.total||loading} onClick={()=>{const q=new URLSearchParams(params);q.set('manualPage',String(page+1));setParams(q,{state:location.state})}}>下一页</Button></Stack></>}
 <Dialog open={!!dialog} onClose={()=>{if(!disabled)setDialog('')}} fullWidth maxWidth="sm"><DialogTitle>{actionNames[dialog]}</DialogTitle><DialogContent><Stack spacing={2} mt={1}><Typography sx={{overflowWrap:'anywhere'}}>账户：{customerId}</Typography>{['credit','debit','reversal'].includes(dialog)&&<><TextField label="币种" value="USD" disabled/>{dialog!=='reversal'&&<TextField select label={dialog==='credit'?'资金来源':'出金类型'} value={source} disabled={disabled} onChange={e=>setSource(e.target.value)}>{(dialog==='credit'?['platform_advance','offline_receipt']:['advance_recovery','offline_payout']).map(s=><MenuItem key={s} value={s}>{label(s)}</MenuItem>)}</TextField>}<TextField label="金额（USD）" value={amount} disabled={disabled||dialog==='reversal'} onChange={e=>setAmount(e.target.value)} inputProps={{inputMode:'decimal'}}/>{(source==='advance_recovery'||dialog==='reversal')&&<TextField label="原入账订单 ID" value={original} disabled={disabled||dialog==='reversal'} onChange={e=>setOriginal(e.target.value)}/>}</>}
 <TextField label="原因 / 备注" value={note} disabled={disabled} onChange={e=>setNote(e.target.value)} multiline minRows={2} inputProps={{maxLength:500}}/>{(['credit','debit','reversal','confirm_payment','payment_failed'].includes(dialog))&&<TextField label="凭证引用" value={evidence} disabled={disabled} onChange={e=>setEvidence(e.target.value)} inputProps={{maxLength:180}}/>}
 <Alert severity="info">{dialog==='debit'?'出金先预占可用余额，再由有权运营审核，同一操作员可完成。线下付款需登记真实结果；此操作不自动向外部账户付款。':dialog==='credit'?'审核通过并记账成功后才增加余额。请核对来源凭证，避免与渠道自动入账重复。':dialog==='confirm_payment'?'仅在已核实线下实际付款后确认；批准申请不代表已经付款。':'操作保留完整审计记录，请核对当前订单。'}</Alert>{error&&<Alert severity="error">{error}</Alert>}</Stack></DialogContent><DialogActions><Button disabled={disabled} onClick={()=>setDialog('')}>返回</Button><Button variant="contained" disabled={disabled||!note.trim()} onClick={submit}>确认提交</Button></DialogActions></Dialog>
 </Stack>;
}
